### ISSUE TITLE
Create new tab with specified existing kernel

### ISSUE THREAD

**Issue by tmr232** [jupyter/qtconsole#101]
I want to be able to create a new tab and connect it to an existing kernel.
Searching for a solution, the only thing I found is [this](http://stackoverflow.com/questions/10496562/is-it-possible-to-connect-to-several-backends-with-one-ipython-qtconsole-fronten) StackOverflow thread.

**Comment by rexdwyer** [comment]
Just create a new tab, and cut and paste the address from the old tab.

**Comment by takluyver** [comment]
@rexdwyer this repo is for the Qt console, which isn't running in the browser, so there are no URLs to copy and paste. ;-)
