### ISSUE TITLE
PyPI packages?

### ISSUE THREAD

**Issue by jakirkham** [jupyter/qtconsole#102]
Would be really great to see released source tarballs of this on PyPI.

**Comment by takluyver** [comment]
https://pypi.python.org/pypi/qtconsole ?

**Comment by jakirkham** [comment]
I guess with the plethora of packages prefixed with `jupyter_` I expected this to be the same story. Also, the fact that there was such a package, but it hasn't seen an update since its dev release made this a bit more confusing ( https://pypi.python.org/pypi/jupyter_qtconsole/ ).

**Comment by takluyver** [comment]
We grabbed the name, but changed our mind about it later. There is no release uploaded to PyPI under that name.

The [installation instructions](http://qtconsole.readthedocs.org/en/latest/#installation) refer to the correct name, and you can also check the [setup.py file](https://github.com/jupyter/qtconsole/blob/19b2137fd86197af0f6f337a39004aaab9bd1486/setup.py#L9).

**Comment by minrk** [comment]
It was the original plan to call it jupyter_qtconsole, but that changed. I've updated the `jupyter_qtconsole` PyPI page to point to the right place, in case anyone else goes down the same path.

**Comment by jakirkham** [comment]
Sure, makes sense. Clearly, I was just confused.

Unrelated, but I also noticed that there are a few other cases of this [jupyter_notebook]( https://pypi.python.org/pypi/jupyter_notebook/ ), [jupyter_nbconvert]( https://pypi.python.org/pypi/jupyter_nbconvert/ ), [jupyter_nbformat]( https://pypi.python.org/pypi/jupyter_nbformat/4.0.0.dev ).
