### ISSUE TITLE
qtconsole 'freezing' after using `?`, need to type many characters before hitting return works again

### ISSUE THREAD

**Issue by ianozsvald** [jupyter/qtconsole#107]
This is an odd one. I've had this issue in QTConsole for approx. 6 months. At first it was very intermittent and I thought it was my system, now I'm having it very frequently (e.g. every 10 minutes) and colleagues have also noted the issue. I've changed my workflow in recent months and now do investigative plotting (with pandas+seaborne) most frequently using a Notebook and qtconsole.

I'll log this, maybe someone can make sense of this?

Here's an example from today's session. I can't hit return, sometimes, until I've typed lots of rubbish characters. In this case I've used auto-repeat and I've tried hitting return several times, in the end it works and I get a carriage return, then I'm back in business:

![qtconsole_typing_bugscreenshot from 2016-03-10 16 49 57](https://cloud.githubusercontent.com/assets/273210/13677855/cb7af6b6-e6e3-11e5-9457-bbc97a992dd8.png)

I'm on Linux (Mint 17.2 based on Ubuntu 14.04 64 bit) using Anaconda 2.5.0 (today's latest). I'm using Python 3.5, this was occurring with Python 3.4 before (I only switched to Python 3.5 this week).
- Jupyter == 4.0.6. 
- qtconsole == 4.1.1
- seaborn == 0.7.0
- matplotlib == 1.5.1
- pandas == 0.17.1

The behaviour: 

I have a `%qtconsole style==monokai`, I often work interactively and then copy/paste results back to my Notebook. If I use `?` for help e.g. `sns.countplot?`, typically I can hit return and get help _but_ afterwards (having used `q` to exit help), my console is temporarily broken.

At this point I can type but cannot hit return (or ctrl-retrurn, alt-return etc - I've bashed the keyboard a lot trying to get any carriage-return behaviour). If I type "a lot of characters" and keep hitting return, after I've typed "enough characters" the return registers and I'm back in business.

At the same time if I ignore this qtconsole and use the Notebook, everything executes still (no freeze/locking in the Notebook). I can also kill the qtconsole and start a new one. 

For the last 3 occurrences of this bug in the last 30 minutes I've typed 107, 89, 106 characters each before I could hit return. These weren't _minimum_ values, I just held my finger on the keyboard and tried return intermittently. I'll do an experiment to see if I can figure out a minimum that's required.

This _might_ be an issue on my machine, I'm logging it to see if anyone else notes a similar freezing behaviour. I'm happy to dig into other info if you tell me what you need.

Addition 1 - I've just had the same issue, I tried counting the characters, after 20 characters (having pressed return twice) the console just froze, I've had to kill it (I waited 1 minute, nothing seems to happen). This was the end state. I've just checked the underlying command console (the one that started `jupyter`) - no errors/logs out of th usual. I started the problem by using `?` on seaborn:
![qtconsole_frozen](https://cloud.githubusercontent.com/assets/273210/13678884/fec1376a-e6e8-11e5-9b18-508cf14864cb.png)

In the above state I can move the window, if I resize it then the resized areas go grey (there's no redraw), I can't drag the sliders or select text. It looks like the gui loop has failed. To close it I had to 'force quit'.

**Comment by jonsedar** [comment]
I've noticed this before too, and as it happens it does seem to be happening more frequently now. 

I've found that entering a string longer than 78 chars lets me break the lock.

My `conda list` output:
```
jupyter                   1.0.0                    py35_1    defaults
jupyter-client            4.1.1                     <pip>
jupyter-console           4.1.0                     <pip>
jupyter-core              4.0.6                     <pip>
```

**Comment by takluyver** [comment]
The Qt console has had several of these kind of locking up bugs, though I'm a bit surprised you don't see the "Position '...' out of range" messages in the terminal (as in #94, for instance).

**Comment by jonsedar** [comment]
Thanks that does look quite familiar, although I don't get any reported "Position '...' out of range" messages. I'm spawning the qtconsole from inside the Notebook though. Perhaps I'd see that if I have a real terminal and connect... let me see

**Comment by ianozsvald** [comment]
I got up to 72 characters and tried to hit return and it worked. I couldn't use backspace this time. Just before I'd used `pandas` to looking help with `myseries.plot?`:

![screenshot from 2016-03-17 15 09 26](https://cloud.githubusercontent.com/assets/273210/13850539/4b1c1bd4-ec52-11e5-8ce9-189987e83b96.png)

**Comment by ianozsvald** [comment]
Tell me if these aren't useful! I'm *only* doing `pandas` / `mpl` / `np` work at present, I've not used Notebooks without these tools in the last couple of weeks. Also to note that, as Jon, I start my `%qtconsole` from within a Notebook.

This time I had to type approx 167 chars to get a Return that worked:

![screenshot from 2016-03-17 18 08 35](https://cloud.githubusercontent.com/assets/273210/13856053/566ec324-ec6b-11e5-8071-8cd262e927d7.png)

**Comment by wmvanvliet** [comment]
May be related to #145
