### ISSUE TITLE
The value of WM_CLASS in IPython qtconsole is empty.

### ISSUE THREAD

**Issue by 183amir** [jupyter/qtconsole#11]
'WM_CLASS' variable is used in some desktop environments to associate apps with their corresponding '.desktop' file. IPython qtconsole's WM_CLASS seems to be empty.

    xprop WM_CLASS
    WM_CLASS(STRING) = "", ""

This makes the app to have no title in Gnome Shell.

Reference: https://wiki.gnome.org/Projects/GnomeShell/ApplicationBased

**Comment by takluyver** [comment]
That page has an example to set it for PyGObject code. If there's a simple equivalent you can find for PyQt, pull requests are welcome.

**Comment by 183amir** [comment]
Please take a look at [here](http://www.qtcentre.org/threads/31012-How-to-change-default-windows-class-name), [here](http://stackoverflow.com/questions/11846029/customize-wm-name-and-wm-class-as-shown-by-xprop-in-pyqt4), and [here](https://bugreports.qt.io/browse/QTBUG-29013).
These are not solutions but they may be useful.

**Comment by takluyver** [comment]
On my GNOME 3 desktop (Debian testing), I do already see a title:

![screenshot from 2015-05-27 11 03 37](https://cloud.githubusercontent.com/assets/327925/7843702/2af3006e-0460-11e5-8ce8-c9816051fe20.png)

**Comment by ccordoba12** [comment]
@takluyver, I think the problem is with KDE.

**Comment by takluyver** [comment]
The OP said "This makes the app to have no title in Gnome Shell."

**Comment by ccordoba12** [comment]
Oops, sorry, didn't read that part. I said it because we had a report from a KDE guy about this problem a couple of months ago.

**Comment by takluyver** [comment]
It's entirely possible that there's something similar going on in KDE.

**Comment by damianavila** [comment]
Just to add... I am in gnome-shell since two days ago (still looking "my" perfect desk env), and I can see the logo as @takluyver mentioned...

**Comment by damianavila** [comment]
But I can not see the title... at least with IPython 3.1.0:

![captura de pantalla de 2015-05-27 17 41 07](https://cloud.githubusercontent.com/assets/1640669/7847028/99f94b08-0497-11e5-8c25-73cf45575031.png)

**Comment by takluyver** [comment]
@damianavila - are you launching that from a terminal, or from the launcher? What version of GNOME do you have? I seem to be on 3.14.4.

**Comment by damianavila** [comment]
@takluyver, from a terminal.... GNOME Shell 3.10.4, maybe that's the issue...

**Comment by takluyver** [comment]
When I launch it from a terminal, I see the name `Qtconsoleapp.py`. I'm not sure exactly how it's getting that - maybe PyQt can use the name of the file that instantiates the QApplication.

**Comment by 183amir** [comment]
@takluyver try restarting your Gnome shell (alt+F2, type `r` and press `enter`); will the title go away or change to `Qtconsoleapp.py`? I am using Arch Linux + Gnome 3.16.
