### ISSUE TITLE
Segmentation fault with latest stable versions of qtconsole and traitlets

### ISSUE THREAD

**Issue by astrofrog** [jupyter/qtconsole#117]
The following code causes a segmentation fault when using the latest version of qconsole (4.2.0) with the latest version of traitlets (4.2.1):

```python
from PyQt4 import QtGui

from qtconsole.inprocess import QtInProcessKernelManager
from qtconsole.rich_jupyter_widget import RichJupyterWidget as RichIPythonWidget

qapp = QtGui.QApplication([''])
qapp.setQuitOnLastWindowClosed(True)

def in_process_console(console_class=RichIPythonWidget, **kwargs):

    km = QtInProcessKernelManager()
    km.start_kernel()

    kernel = km.kernel
    kernel.gui = 'qt4'

    client = km.client()
    client.start_channels()

    control = console_class()
    control.kernel_manager = km
    control.kernel_client = client
    control.shell = kernel.shell
    control.shell.user_ns.update(**kwargs)

    return control

for i in range(50):
    print("Starting console {0}".format(i))
    in_process_console()

print("Before setting icon")
qapp.setWindowIcon(QtGui.QIcon())
print("After setting icon")
```

The output is:

```
...
Starting console 47
Starting console 48
Starting console 49
Before setting icon
Segmentation fault: 11
```

It looks like this is because of the following changes:

- traitlets: https://github.com/ipython/traitlets/commit/e53a6f52708b6bd5e5470ec43a0535494bbe4888
- qtconsole: 3c984b55427338a24ab8ea15afb15458976ea7b0

Traitlets has had a release since then but not qtconsole. Would it be possible to release a new version of qtconsole to prevent this issue? (this is currently causing segmentation faults in Glue)

Alternatively, is there a workaround?

(just to be clear, I'm not instantiating 50 consoles in Glue, but when running the tests there are a number of consoles created, and this is where I am seeing the issue)

cc @rmorshea @minrk

**Comment by ccordoba12** [comment]
So 3c984b5 fixes your issue or causes it?

**Comment by astrofrog** [comment]
https://github.com/jupyter/qtconsole/commit/3c984b55427338a24ab8ea15afb15458976ea7b0 fixes it, but it happened after the latest stable release of qtconsole. So all the code in master is fine, but we need a qtconsole release to avoid the segfault.

**Comment by ccordoba12** [comment]
Then I think we need to ask @minrk for a `4.2.1` release :-)

**Comment by minrk** [comment]
I'll do that today.

**Comment by minrk** [comment]
Released 4.2.1 with the superQ fix

**Comment by astrofrog** [comment]
@minrk - thanks for the quick release!

**Comment by akdiem** [comment]
I still have the problem, even though 
`jupyter qtconsole --version`
gives 4.2.1. I have already tried uninstalling and reinstalling all of qt and jupyter, but it doesn't fix it.

**Comment by minrk** [comment]
@akdiem sorry about that. Can you give a complete `conda list` or `pip list`, and Python version, OS, etc.? It might be a version of PySide/PyQt I didn't test with. The band-aid while we figure it out is to pin traitlets to 4.1: `pip install 'traitlets<4.2'`.

**Comment by astrofrog** [comment]
Could it also be that traitlets *needs* to be 4.2.1 if qtconsole is 4.2.1? (and maybe this is not the case here?)

**Comment by akdiem** [comment]
@minrk See below for complete pip list, I use Python 2.7.6 on Linux Mint 17.1
@astrofrog traitlets is version 4.2.1 on my machine, see pip list output below

`alabaster (0.7.7)
APLpy (1.0)
apptools (4.1.0)
apt-xapian-index (0.45)
apturl (0.4.1ubuntu4)
argparse (1.2.1)
astropy (1.1.2)
Babel (2.2.0)
backports-abc (0.4)
backports.ssl-match-hostname (3.5.0.1)
BeautifulSoup (3.2.1)
brainnetwork (0.0.0)
certifi (2016.2.28)
chardet (2.0.1)
colorama (0.2.5)
command-not-found (0.3)
configglue (1.1.2)
configobj (4.7.2)
configparser (3.3.0r2)
cycler (0.10.0)
debtagshw (0.1)
decorator (3.4.0)
defer (1.0.6)
dirspec (13.10)
distribute (0.7.3)
dnspython (1.11.1)
docutils (0.11)
duplicity (0.6.23)
envisage (4.1.0)
feedparser (5.1.3)
ferari (1.0.0)
FFC (1.3.0)
FIAT (1.3.0)
functools32 (3.2.3-2)
futures (3.0.5)
h5py (2.3.1)
html5lib (0.999)
httplib2 (0.8)
imagesize (0.7.0)
instant (1.3.0)
ipykernel (4.3.1)
ipyparallel (5.0.1)
ipython (4.1.2)
ipython-genutils (0.1.0)
ipywidgets (4.1.1)
Jinja2 (2.7.2)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.2.2)
jupyter-console (4.1.1)
jupyter-core (4.1.0)
lockfile (0.8)
lxml (3.3.3)
Mako (0.9.1)
MarkupSafe (0.18)
matplotlib (1.5.1)
mayavi (4.1.0)
mglob (0.4)
mistune (0.7.2)
mpi4py (2.0.0)
nbconvert (4.1.0)
nbformat (4.0.1)
nemo-emblems (0.0.1)
netcdf (0.2.1)
netCDF4 (1.1.0)
networkx (1.8.1)
nose (1.3.7)
notebook (4.1.0)
numpy (1.8.0)
oauthlib (0.6.1)
oneconf (0.3.7.14.04.1)
openshot (1.4.3)
PAM (0.4.2)
pandas (0.13.1)
paramiko (1.10.1)
path.py (8.1.2)
pexpect (3.1)
pickleshare (0.6)
Pillow (2.3.0)
pip (1.5.4)
piston-mini-client (0.7.5)
Pivy (0.5.0)
pkginfo (1.2.1)
ply (3.4)
protobuf (2.5.0)
ptyprocess (0.5.1)
py (1.4.31)
pyandoc (0.0.1)
pycollada (0.4)
pycrypto (2.6.1)
pycups (1.9.66)
pycurl (7.19.3)
pyface (4.1.0)
Pygments (1.6)
pygobject (3.12.0)
pyinotify (0.9.4)
pyOpenSSL (0.13)
pyparsing (2.0.1)
pyregion (1.1.4)
pyserial (2.6)
PySide (1.2.4)
pysmbc (1.0.14.1)
pytest (2.8.5)
python-apt (0.9.3.5ubuntu2)
python-dateutil (1.5)
python-debian (0.1.21-nmu2ubuntu2)
pytz (2012c)
pyxdg (0.25)
pyzmq (14.0.1)
qtconsole (4.2.1)
reportlab (3.0)
requests (2.2.1)
requests-toolbelt (0.6.0)
roman (2.0.0)
ScientificPython (2.9.4)
scipy (0.13.3)
seaborn (0.7.0)
sessioninstaller (0.0.0)
setuptools (3.3)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.5.2)
snowballstemmer (1.2.1)
Sphinx (1.2.2)
spyder (2.3.8)
sympy (0.7.6.1)
system-service (0.1.6)
terminado (0.6)
testpath (0.3)
tornado (4.3)
traitlets (4.2.1)
traits (4.1.0)
traitsui (4.1.0)
twine (1.6.5)
Twisted-Core (13.2.0)
Twisted-Names (13.2.0)
Twisted-Web (13.2.0)
UFL (1.3.0)
urllib3 (1.7.1)
uTidylib (0.2)
VTK (5.8.0)
wsgiref (0.1.2)
wxPython (2.8.12.1)
wxPython-common (2.8.12.1)
zmq (0.0.0)
zope.interface (4.0.5)`
