### ISSUE TITLE
ConsoleWidget width/height traits override Qt properties 

### ISSUE THREAD

**Issue by rkern** [jupyter/qtconsole#124]
https://github.com/jupyter/qtconsole/blob/master/qtconsole/console_widget.py#L135-L143

These override the `width()` and `height()` Qt properties that are required to use this as a `QWidget` in many places. Can we rename them to `console_width/console_height`? I don't know how often these traits are actually used downstream. We override them right back to work around the problem.

**Comment by takluyver** [comment]
Longer term (if qtconsole development goes that far), I think it would be best to separate the configurable objects with traitlets from the Qt classes, to avoid clashes like this and the need for metaclass multiple inheritance. But renaming them sounds like a sensible fix in the meantime.
