### ISSUE TITLE
Copying text from qt console and pasting is missing In [?]: prefix

### ISSUE THREAD

**Issue by astrofrog** [jupyter/qtconsole#132]
If I copy text from a qtconsole:

![screen shot 2016-07-20 at 4 22 47 pm](https://cloud.githubusercontent.com/assets/314716/17001726/3c7e0bfe-4e96-11e6-81d6-529a19988cb4.png)

and paste it:

```
a = 1

a
Out[2]: 1
```

then the `In [?]` prefixes are missing but the `Out [?]` ones are not. In my case I want the `In [?]` prefixes to be included (I don't think removing `Out [?]` is an option since the log would then be really confusing.

**Comment by takluyver** [comment]
IIRC, stripping the in prompts is deliberate, but if you right click,
there's an option called something like copy raw.

**Comment by astrofrog** [comment]
@takluyver - ah yes, that does indeed work. I personally would have made the stripping of the prompts the non-default option, but I'm fine with this issue being closed if people are happy with the way things are currently.

**Comment by wmvanvliet** [comment]
I copy/paste things all the time between my text editor and the qtconsole. I really appreciate the default being what it is.
