### ISSUE TITLE
Startup script?

### ISSUE THREAD

**Issue by LindyBalboa** [jupyter/qtconsole#134]
I have a certain batch of imports that I almost always run upon startup, but I can't seem to figure out how to make this automatic? I tried putting the imports in .jupyter/jupyter_qtconsole_config.py but that was of no use. Any suggestions?

**Comment by takluyver** [comment]
Code to run on startup is configured as part of IPython, not Jupyter, because it's specific to Python.

http://ipython.readthedocs.io/en/stable/config/options/kernel.html

**Comment by LindyBalboa** [comment]
Okay, I tried creating a file in ~/.ipython/profile_default/startup but that seemed to have no effect either, and I have not created any other profiles.

**Comment by takluyver** [comment]
Is it possible that you missed the `.py` extension the first time? I think it only finds .py files. Anyway, glad it works now.
