### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by nonamedotc** [jupyter/qtconsole#142]
I am packaging qtconsole for Fedora and have a question regarding licenses. The PyPi page mentions BSD license but several files are missing license headers. Can the developers please add license headers and eliminate any potential confusion.

List of files without license header is attached.

Thanks!

[licensecheck.txt](https://github.com/jupyter/qtconsole/files/491441/licensecheck.txt)

**Comment by takluyver** [comment]
In all of our projects, we use a license file in the top level of the repo, rather than copying the license text into each file. You can find it here:

https://github.com/jupyter/qtconsole/blob/master/COPYING.md

**Comment by nonamedotc** [comment]
Thank you! Clarification is appreciated.

:+1:
