### ISSUE TITLE
startup commands for Jupyter QtConsole.-

### ISSUE THREAD

**Issue by jimsrc** [jupyter/qtconsole#144]
I'm having issues migrating my IPython startup configuration settings to Jupyter QtConsole.
Specifically, before Jupyter, I used very much startup commands so I have a lot of tools ready for fast analysis and plots in the QtConsole.
This specific issue has already been addressed [here](https://groups.google.com/forum/#!topic/jupyter/kzEws9ZeCFE), and the solution was to use the `ipython_config.py`.

My problem is that I need: 
```
%matplotlib inline
...other-qtconsole-specifics
```
in QtConsole, but **not** in IPython.
So the problem with using `ipython_config.py` is that, they commands there are executed for both QTConsole and IPython (*).

Is there a way to set startup commands **only** for QtConsole (and not for IPython)?
I understand that there's a way out for this issue by configuraing kernels in Jupyter (looks a little messy when I read the documentation)?

Thanks!
---
(*): IPython doesn't like `%matplotlib inline`, because when I do:
```
$ ipython myscript.py
```
I get lots of `AttributesErrors`, and my script doesn't run.

**Comment by takluyver** [comment]
If you have IPython settings that should affect IPython when used as a kernel, but not the terminal interface, you can put them in `ipython_kernel_config.py` ([docs](http://ipython.readthedocs.io/en/stable/config/options/kernel.html)). E.g. you can set:

```python
c.InteractiveShellApp.matplotlib = 'inline'
```

**Comment by jimsrc** [comment]
o_O!
Awesome! Works great for me...
