### ISSUE TITLE
[ OS X ] Shortcuts for moving between tabs don't work 

### ISSUE THREAD

**Issue by temok-mx** [jupyter/qtconsole#155]
Dear All,

The shortcuts for moving between tabs (Shift-Command-left or -right) on qtconsole don't work on my installation (they are OK if I click on the 'Window' menu, but I wish not to depend on the mouse for this simple action). I am using OS X and these same shortcuts work fine on other applications, such as Finder.app, or different web browsers, like Safari and Chrome.

I have installed everything using anaconda's `conda.` The snapshot shows what version of python, qtconsole and ipython I have. I reviewed `Systems Preferences > Keyboard > Shortcuts` and did not find any conflicts (duplicated definitions) of  Shift-Command-left and -right. I would appreciate any suggestions to make these shortcuts work!

Thanks,
Temok

![qtconsole](https://cloud.githubusercontent.com/assets/7350062/19712639/9b4bc266-9b0d-11e6-8450-176ed33b1d01.jpg)

**Comment by wmvanvliet** [comment]
confirmed. Something weird is going on. When I remap the shortcut to anything else (e.g. Ctrl+Left or Ctrl+Shift+L) it works, but somehow Ctrl+Shift+Left does not.

**Comment by ccordoba12** [comment]
Maybe the shortcut is taken from at the OS level?

**Comment by temok-mx** [comment]
Dear Marijn, how can I re-map those shortcuts as you did? 

Dear Carlos, I reviewed the OS X Systems Preferences > Keyboard > Shortcuts and did not find any conflicts (duplicated definitions) of Shift-Command-left and -right. 

Thank you!

**Comment by wmvanvliet** [comment]
@ccordoba12 that could very well be the case, any thoughts on how to stop the OS from doing that?

@temok-mx you can't without modifying the source code.

**Comment by takluyver** [comment]
If they are taken at the OS level, we'll probably have to pick some other shortcuts. I've no idea if that's the case, though.
