### ISSUE TITLE
no PEP 528/ PEP 529  effect ?

### ISSUE THREAD

**Issue by stonebig** [jupyter/qtconsole#159]
I don't see a positive effect from these PEP with Python3.6.0b3:
- is there something to do in QtConsole code ? 
- or did I misunderstood these PEP effect ("utf-8" on Windows).

![pep_528-529_where_are_you_you](https://cloud.githubusercontent.com/assets/4312421/20240304/5590d570-a915-11e6-91d3-c803e67ad2e2.PNG)

**Comment by takluyver** [comment]
I don't think either of those PEPs would affect this:

- [528](https://www.python.org/dev/peps/pep-0528/) is about input and output from the Windows console. The Qt console doesn't use a Windows console - it draws its own console interface - and it already handles unicode output similar to what that PEP brings.
- [529](https://www.python.org/dev/peps/pep-0529/) is about using unicode for interacting with the filesystem. That's a win for Python code in general, but doesn't affect what you're doing in the screenshot.

The issue AIUI is that `!dir` runs as a subprocess from which we capture stdout and stderr as bytes. We then have to guess the encoding of those bytes, and we're evidently guessing wrong in this case. I don't think it's possible to run a subprocess on Windows and capture unicode stdout/stderr. So we just need to try to work out why our encoding guess is going wrong, and if we can do it better.

**Comment by stonebig** [comment]
in the mean time, weren't you suppose to do an imminent qtconsole-4.3 release ? no hint in today hackpad

**Comment by ccordoba12** [comment]
I'm the one supposed to do that, but haven't had time so far :-)

**Comment by wmvanvliet** [comment]
Can we close this issue?
