### ISSUE TITLE
Error: PyQt5.QtWidgets has not attribute QPrinter

### ISSUE THREAD

**Issue by Sonic-boom** [jupyter/qtconsole#160]
I don't konw what's wrong with the `help('modules')`
![default](https://cloud.githubusercontent.com/assets/22865951/20243287/8e2338a2-a98c-11e6-91f7-8000aba2de27.PNG)
I think  (Ctrl+Shift+P) make it do someting wrong  and how can I make it right 

Thanks

**Comment by takluyver** [comment]
I think the `QPrinter` class was in QtGui in Qt4, but was moved to a separate `QtPrintSupport` module for Qt5 ([source](http://pyqt.sourceforge.net/Docs/PyQt5/api/qprinter.html)). The easiest, if rather hackish, way to fix it is to add QtPrintSupport to the compatibility code here:

https://github.com/jupyter/qtconsole/blob/f3f96b6f91883a448d3915b65d0aecd106327ad3/qtconsole/qt_loaders.py#L233

**Comment by takluyver** [comment]
@ccordoba12 sorry to add another issue to 4.3, but I think this should be an easy fix!

**Comment by takluyver** [comment]
#162 should fix this.
