### ISSUE TITLE
Unable to open qtconsole - RuntimeError

### ISSUE THREAD

**Issue by chrisjcameron** [jupyter/qtconsole#168]
In Python 3.5 I am having an issue launching qtconsole. imp.py expects the `mod.__path__` to be of type list but `__import__` is packaging the `__path__` inside a `_NamespacePath` with a `._path` attribute. I suspect a lot of the issue is using a depreciated module (`imp.py`). 

I was able to workaround in `qt_loaders.py` by modifying `has_binding(api)` to detect namespace objects and send the expected input to `find_module`:
Line 126:

```
        path = mod.__path__
        if hasattr(mod.__path__, '_path' ):
            path = mod.__path__._path
        imp.find_module('QtCore', path )
        imp.find_module('QtGui', path)
        imp.find_module('QtSvg', path)
        if api == QT_API_PYQT5:
            # QT5 requires QtWidgets too
            imp.find_module('QtWidgets', path)

```

The error: 

```
bureaucratic-node-160$ jupyter qtconsole
_NamespacePath(['/Users/cjc73/anaconda/lib/python3.5/site-packages/PyQt5'])
Traceback (most recent call last):
  File "/Users/cjc73/anaconda/bin/jupyter-qtconsole", line 2, in <module>
    from qtconsole.qtconsoleapp import main
  File "/Users/cjc73/anaconda/lib/python3.5/site-packages/qtconsole/qtconsoleapp.py", line 60, in <module>
    from qtconsole.qt import QtCore, QtGui
  File "/Users/cjc73/anaconda/lib/python3.5/site-packages/qtconsole/qt.py", line 23, in <module>
    QtCore, QtGui, QtSvg, QT_API = load_qt(api_opts)
  File "/Users/cjc73/anaconda/lib/python3.5/site-packages/qtconsole/qt_loaders.py", line 286, in load_qt
    if not can_import(api):
  File "/Users/cjc73/anaconda/lib/python3.5/site-packages/qtconsole/qt_loaders.py", line 161, in can_import
    if not has_binding(api):
  File "/Users/cjc73/anaconda/lib/python3.5/site-packages/qtconsole/qt_loaders.py", line 126, in has_binding
    imp.find_module('QtCore', mod.__path__)
  File "/Users/cjc73/anaconda/lib/python3.5/imp.py", line 271, in find_module
    "not {}".format(type(name)))
RuntimeError: 'list' must be None or a list, not <class 'str'>
```

**Comment by takluyver** [comment]
Can you look at what is required to do the same with [importlib.util.find_spec()](https://docs.python.org/3/library/importlib.html#importlib.util.find_spec)? If the `imp` version isn't working, it may be best to have 'old Python' and 'new Python' versions of the `has_binding()` function.

**Comment by pletnes** [comment]
I'm getting the same RuntimeError and traceback, so this affects me, too. I'm on PyQt4 if that matters - for now I need to stick to that, as we've got some GUI apps using PyQt4.

**Comment by wmvanvliet** [comment]
what versions of python do we officially support? 2.7 also has `importlib`

**Comment by takluyver** [comment]
It's there, but it only has one function, which is not the one we need: https://docs.python.org/2/library/importlib.html

What this needs is a way to check for the existence of an importable module without actually importing it.

We're already dropping support for Python 2.7 in IPython. I'd be OK with dropping Py2 support in Qt console too - users can still run their code in a Py2 kernel, even if the UI runs in Py3. But that's primarily up to @ccordoba12 and how long he wants to support Spyder running on Py2.

**Comment by wmvanvliet** [comment]
> It's there, but it only has one function, which is not the one we need: 

Ah, I missed that.

Installing a python3.5 anaconda environment on my OSX installation (with PyQt4) doesn't seem to reproduce the mentioned issue. Can any of you give me any tips on how to reproduce this?

**Comment by pletnes** [comment]
I've got an environment that reproduces, but it's 240 packages (woops) since I've been playing with too many things. I'll see if I can cut it down...

I'm on ubuntu 16.04, python 3.5, pyqt4 FWIW. I can't reproduce it in my "root" conda env, FYI.

**Comment by takluyver** [comment]
I can't reproduce the error to test, but I think #183 should fix it.
