### ISSUE TITLE
The qt install requires is missing

### ISSUE THREAD

**Issue by picca** [jupyter/qtconsole#169]
Hello, while preparing the Debian packages, I noticed that the qt5 dependency is missing

setuptools_args = {}
install_requires = setuptools_args['install_requires'] = [
    'traitlets',
    'jupyter_core',
    'jupyter_client>=4.1',
    'pygments',
    'ipykernel>=4.1', # not a real dependency, but require the reference kernel
]

could you add it

**Comment by takluyver** [comment]
It's tricky because it requires one of three different packages: PyQt5, PyQt4 or PySide. Unlike Debian, Python does not have a way to express alternative dependencies. I have been considering just putting a dependency on PyQt5, however, because that is pip installable.

**Comment by picca** [comment]
> It's tricky because it requires one of three different packages: PyQt5, PyQt4 or PySide. Unlike Debian, Python does not have a way to express alternative dependencies. I have been considering just putting a dependency on PyQt5, however, because > that is pip installable.

I did not know that pip does not have alternatives.
Maybe it is better to not decide which version of PyQt is requiered by our users...

this is quite unfortunate.

cheers
