### ISSUE TITLE
Compatible with python3.6?

### ISSUE THREAD

**Issue by rob-gordon** [jupyter/qtconsole#176]
When I try to run `jupyter qtconsole` I get

    zsh: /usr/local/bin/jupyter: bad interpreter: /usr/local/opt/python3/bin/python3.5: no such file or directory

This isn't my default python though (nor is it installed at all). I installed with qtconsole with pip, pyqt5 and python3 with homebrew.

    ➜  session-1 git:(master) ✗ which python3
    /usr/local/bin/python3
    ➜  session-1 git:(master) ✗ python3 -V
    Python 3.6.0

**Comment by ccordoba12** [comment]
Most probably pyqt5 is still not compatible with Python 3.6.

And there's nothing qtconsole can do about it.

**Comment by rob-gordon** [comment]
Yes, that was the case. Thanks!

**Comment by takluyver** [comment]
The error message looks like you installed it with `pip` in Python 3.5, and then removed Python 3.5. You need to do the installation with pip running on the Python you want to install to.
