### ISSUE TITLE
Can't find windows qt pluign

### ISSUE THREAD

**Issue by spcsmrf** [jupyter/qtconsole#181]
When i try to start qtconsole i get this error:

> This application failed to start because it could not find or load the Qt platform plugin "windows" in "".

I have tried everything that i have found reinstalling, updating, installing pyqt but nothing works.

Here's some extra information:

{'commit_hash': u'5c9c918',
 'commit_source': 'installation',
 'default_encoding': 'cp850',
 'ipython_path': 'E:\\Freshprg\\IDEs, Interpreters, Programs\\Python2\\Anaconda2\\lib\\site-packages\\IPython',
 'ipython_version': '5.1.0',
 'os_name': 'nt',
 'platform': 'Windows-10-10.0.10586',
 'sys_executable': 'E:\\Freshprg\\IDEs, Interpreters, Programs\\Python2\\Anaconda2\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '2.7.12 |Anaconda custom (64-bit)| (default, Jun 29 2016, 11:07:13) [MSC v.1500 64 bit (AMD64)]'}

**Comment by ccordoba12** [comment]
Please change the directory of your Anaconda installation. Instead of using

    ...\IDEs, Interpreters, Programs\...

Use a directory without spaces and commas on it.

**Comment by spcsmrf** [comment]
Thanks so much!

**Comment by ccordoba12** [comment]
@spcsmrf, glad to know it worked for you!
