### ISSUE TITLE
Cannot install qt console

### ISSUE THREAD

**Issue by jimbasquiat** [jupyter/qtconsole#185]
Hi,

I receive the following error:
UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - qtconsole

When trying to install QTConsole. What are my options here?

**Comment by takluyver** [comment]
That means that there isn't a conda package of the Qt console for Python 3.6 yet. Your options are:

- Use Python 3.5 until people have done the packaging.
- Create a Python 3.6 env with PySide/PyQt, and then use `pip` to install qtconsole.
