### ISSUE TITLE
conda search qtconsole: not yet  4.3.0 

### ISSUE THREAD

**Issue by temok-mx** [jupyter/qtconsole#186]
Dear All,

It seems the current version of qtconsole is
   ` Release:	4.3.0`
   ` Date:	January 17, 2017`
(See [http://qtconsole.readthedocs.io/en/latest/](url) )

However, doing 
   ` conda update conda`
   ` conda search qtconsole`
still points to 
   ` *  4.2.1                    py27_1  defaults`

Am I missing something?
Thanks,
Temok

**Comment by ccordoba12** [comment]
We haven't released it yet, sorry. I've been very busy to do it, but I'll try to do it today or tomorrow.

**Comment by temok-mx** [comment]
Thanks!

**Comment by temok-mx** [comment]
Dear All --  I'm sorry to get back to this question: I wonder if there is any update regarding version 4.3.0 of  qtconsole. Doing `conda update conda` followed by `conda search qtconsole` still indicates that version 4.2.1 is the latest available install. Is this the case or am I missing something? Thank you, Temok

**Comment by mbakker7** [comment]
Hello ccordoba. It doesn't look like 4.3.0 has been released yet (right?), although the doc pages show a 4.3.0 release for Feb. 20. Any chance you will have time to release 4.3 in the coming days?
