### ISSUE TITLE
conda search qtconsole: not yet 4.3.0 (2)

### ISSUE THREAD

**Issue by temok-mx** [jupyter/qtconsole#191]
Dear All -- I'm sorry to get back to this question (#186 ): I wonder if there is any update regarding version 4.3.0 of qtconsole. Doing `conda update conda` followed by `conda search qtconsole `still indicates that version 4.2.1 is the latest available install. Is this right, or am I missing something? Thank you, Temok

**Comment by ccordoba12** [comment]
That's because that's the last version available. I'm in charge of releasing a new qtconsole, I just haven't had time for it, sorry. I'll try to do it soon.

**Comment by temok-mx** [comment]
Thank you Carlos!
