### ISSUE TITLE
Release 4.3

### ISSUE THREAD

**Issue by ccordoba12** [jupyter/qtconsole#199]
4.3 contains important fixes and it's time to release it. @wmvanvliet, do you agree?

CC @JamiesHQ from the Jupyter management side.

**Comment by JamiesHQ** [comment]
cc'ing @minrk @takluyver @Carreau @willingc

**Comment by willingc** [comment]
Seems reasonable to me. I would like bit more documentation/clarification in the changelog.

For example, is this [warning](https://github.com/jupyter/qtconsole/blame/master/docs/source/changelog.rst#L15) re: potential compatibility breakage still needed?

**Comment by ccordoba12** [comment]
@willingc, I think it's important to leave it. That change doesn't cause problems in Spyder but it could cause them for people in other projects.

I still have to update our changelog with stuff that has happened during the last months ;-)

**Comment by willingc** [comment]
Thanks @ccordoba12. I'll send along a PR to adjust the wording slightly for your review.

**Comment by wmvanvliet** [comment]
Yes, a release is long overdue. We should update the changelog to include the bugfixes we did.

**Comment by wmvanvliet** [comment]
maybe merge #195 before we release :)

**Comment by ccordoba12** [comment]
Yes, I agree.

**Comment by ccordoba12** [comment]
I think everything is ready for the release. If everyone is ok, I'll do it this weekend, if not please say it here :-)

**Comment by willingc** [comment]
:ship:

**Comment by ccordoba12** [comment]
4.3 has been released!! Thank you all for your help!!

**Comment by willingc** [comment]
Congrats @ccordoba12 and all who contributed. :tada:

**Comment by temok-mx** [comment]
Dear All, -- I'm a qtconsle user,  thanks a lot for this release. I just did `conda update conda; conda search qtconsole` and still the latest version listed is 4.2.1. Is this because some time is needed for the repositories/servers to sync? BTW, [readthedocs](https://qtconsole.readthedocs.io/en/latest/) reads that version 4.4 is the latest. Is this a typo, or is there a rationale for this?. That you all, Temok

**Comment by minrk** [comment]
Great! 🎉

**Comment by ccordoba12** [comment]
@temok-mx, packages in the official conda channels take a couple of days to appear, please be patient. We don't have any control on that because it's up to Continuum (the creators of Anaconda).

**Comment by willingc** [comment]
@temok-mx Thanks for pointing out the readthedocs issue. I've updated the configuration for the default to be the stable version 4.3.

**Comment by temok-mx** [comment]
Dear @willingc and @ccordoba12, thanks for your replies!

**Comment by takluyver** [comment]
If you choose to use [conda-forge](http://conda-forge.github.io/), you may get updates sooner. It means trusting a nebulous community rather than Continuum, which may not be appropriate in all situations - although if you install anything with pip or npm, you're also relying on the community.

**Comment by ccordoba12** [comment]
The problem with conda-forge is that you need to create a new environment for conda-forge because Continuum and conda-forge packages hae different build specs.

**Comment by mbakker7** [comment]
Thank you so much for the new qtconsole release. It installs fine with conda on my Mac. The only thing that is odd is the message that conda prints to the screen:

The following packages will be UPDATED:

qtconsole: 4.2.1-py36_1 --> 4.3.0-py36_0

I guess that means the new release is called 4.3.0-py36_0, while the previous one was for py36_1? I guess it doesn't really matter, just a small inconsistency.

Thanks again. I am already enjoying the new 4.3 !

**Comment by minrk** [comment]
@mbakker7 the last number is the build number of the conda package itself, which is reset on each new release. Parsing out the whole package version:

    qtconsole version 4.3.1 for Python 3.6, build number 0.

The build number is incremented when we rebuild the conda package for the same version of qtconsole, such as changing the pinning of qt in the dependencies, etc.

**Comment by willingc** [comment]
Thanks @minrk. I learned something new from your response to @mbakker7's observation.
