### ISSUE TITLE
Qt Console suppressing errors for module imports, but shows up for IPython console

### ISSUE THREAD

**Issue by u2berggeist** [jupyter/qtconsole#205]
When I run a script that is importing a module I am working on, it returns no errors. However, when I run it with IPython console, it returns the error I need to see.

Seems kinda weird that this would be a normal bug. If this is due to a default setting, I propose that it needs to be changed as it goes against the Zen of Python:

> Errors should never pass silently.
>Unless explicitly silenced.

Regardless, we should fix it.

![jupyter qtconsole vs ipython console error suppresion](https://cloud.githubusercontent.com/assets/20801821/24614110/3e14403c-1858-11e7-9a82-9b05f90eb928.PNG)

**Comment by takluyver** [comment]
Do you have the latest version of all the packages that could be involved (qtconsole, jupyter_client, ipykernel, ipython)?

**Comment by ccordoba12** [comment]
This was fixed in qtconsole 4.3, if I'm not mistaken so please update.

**Comment by u2berggeist** [comment]
I am currently running QtConsole 4.2.1. I'll upgrade and see if that solves the issue.

**Comment by u2berggeist** [comment]
Yep, solved it. Sorry for the trouble.

**Comment by ccordoba12** [comment]
No worries ;-)
