### ISSUE TITLE
How could I put my own pyqt widget into embed inprocess qtconsole just like inline matplotlib?

### ISSUE THREAD

**Issue by testmana2** [jupyter/qtconsole#206]
Hi, all! I am very exciting with the awesome qtconsole.

I had a inprocess qtconsole embed in my pyqt app and I want to show some pyqt widgets in the qtconsole.
I want to do this:
widget = MyWidget()
widget.show()

Then the widget will be rendered in the qtconsole just like inline matplotlib plot.show()

How could I implement this?

**Comment by wmvanvliet** [comment]
The main widget of qtconsole is a QTextEdit, which doesn't support embedding arbitrary widgets, as far as I know. So unfortunately, this would be quite complicated.

**Comment by testmana2** [comment]
thank you.
