### ISSUE TITLE
feature request for closing qtconsole window without confirm 

### ISSUE THREAD

**Issue by redstoneleo** [jupyter/qtconsole#209]

**Comment by espdev** [comment]
@redstoneleo you can use the following config value:
```
c.JupyterConsoleApp.confirm_exit = False
```

**Comment by ccordoba12** [comment]
Thanks @espdev.

**Comment by redstoneleo** [comment]
add the line to 
`C:\Users\i\AppData\Local\Programs\Python\Python35-32\Lib\site-packages\jupyter_core\tests\dotipython\profile_default\ipython_config.py`
or
`C:\Users\i\AppData\Local\Programs\Python\Python35-32\Lib\site-packages\jupyter_core\tests\dotipython_empty\profile_default\ipython_config.py`?

**Comment by espdev** [comment]
@redstoneleo you need to create config profile:
```
ipython profile create [profilename]
```
You can create the `default` profile if you leave out the profile name.

Please, see also: http://ipython.readthedocs.io/en/stable/config/intro.html#introduction-to-ipython-configuration

**Comment by takluyver** [comment]
You actually don't need the IPython config for this, as far as I know - it should be just the Jupyter Qtconsole config.

**Comment by redstoneleo** [comment]
Thanks @espdev and @takluyver !
For me, just run
`jupyter qtconsole --generate-config`
then add
`c.JupyterConsoleApp.confirm_exit = False` to `C:\Users\i\.jupyter\jupyter_qtconsole_config.py`  works
