### ISSUE TITLE
Payload missing should be handled

### ISSUE THREAD

**Issue by Carreau** [jupyter/qtconsole#21]
See https://github.com/JuliaLang/IJulia.jl/pull/325#issuecomment-117329536 where `qtconsole --kernel julia crashes`

**Comment by stevengj** [comment]
Also `console`

**Comment by stevengj** [comment]
Note that I was using IPython 3.0.0, so it would be good to check whether this has already been fixed.

**Comment by stevengj** [comment]
Got the same error in IPython 3.2.0:
```
  File "/Users/stevenj/anaconda/lib/python2.7/site-packages/IPython/qt/console/frontend_widget.py", line 767, in _process_execute_ok
    payload = msg['content']['payload']
KeyError: 'payload'
```

**Comment by stevengj** [comment]
Looks like the unqualified access of the payload key [is still in git master](https://github.com/jupyter/qtconsole/blob/6b023ccfb77a12fc40cabc2666ebaff9bd001452/qtconsole/frontend_widget.py#L767).
