### ISSUE TITLE
Jedi-based autocompletion does not work in QtConsole

### ISSUE THREAD

**Issue by espdev** [jupyter/qtconsole#210]
I'm using QtConsole with IPython 6.0 and new Jedi-based autocompletion does not work.
![qtconsole](https://cloud.githubusercontent.com/assets/1299189/25369951/24d8f218-2990-11e7-8c5f-f00987edc2ac.png)

**Comment by takluyver** [comment]
Ping @Carreau 

Issues about finding the completions are likely to be part of IPython, while issues about the UI for displaying and selecting them will be in this repo.

**Comment by wmvanvliet** [comment]
Reading the docs, the jedi-completion seems to implemented at the client level, not the kernel. Hence, only the console client supports it and not any other client such as QtConsole. There seem to be plans to implement it on the kernel side, which would mean it would become available to QtConsole as well.

**Comment by takluyver** [comment]
I'm not 100% sure, but I think that we use the same completion machinery for the kernel as for terminal IPython. The same thing happens in terminal IPython as well.

**Comment by ccordoba12** [comment]
The blog post announcing IPython 6 says that changes need to be made to ipykernel for Jedi completions to appear in Jupyter frontends.

So there's nothing we can do about it here.

**Comment by Carreau** [comment]
See https://github.com/ipython/ipykernel/pull/222 , but the API is still experimental. 
It's easy to make a conditional completer that uses either the  normal protocol or the `_experimental` key if present. 

It's also possible to fold the jedi completions into the normal protocol (without the types and bells and whistle). I just didn't got enough feedback on the IPython side API which is still marked as unstable.

It will take even more time to stabilize a change in the protocol. I'm also working on Jedi's side to see if we can get more information like the function signature during completion.
