### ISSUE TITLE
Python 3.6: TypeError in RichJupyterWidget class

### ISSUE THREAD

**Issue by TheHubbit** [jupyter/qtconsole#211]
Trying to instantiate an object of type RichJupyterWidget with Python 3.6 causes a type error.

```
    _supported_format = [bytes(f) for f in QtGui.QImageReader.supportedImageFormats()]
TypeError: 'bytes' object cannot be interpreted as an integer

```

This program will reproduce the issue:

```
#!/usr/bin/python
import sys
from PySide.QtCore import *
from PySide.QtGui import *
from qtconsole.rich_jupyter_widget import RichJupyterWidget

app = QApplication(sys.argv)
widget = RichJupyterWidget()
widget.show()
app.exec_()
sys.exit()
```

**Comment by takluyver** [comment]
How did you install PySide? It hasn't had a release in over a year, so I wonder if it's not compatible with Python 3.6. It looks like there's work on PySide2, and you might be able to use PyQt in the meantime.

**Comment by TheHubbit** [comment]
I installed Python 3.6.1 and the package py36-pyside via MacPorts. Besides this one here I haven't had any issues with it.
