### ISSUE TITLE
check if kernel is busy

### ISSUE THREAD

**Issue by luoy2** [jupyter/qtconsole#219]
Hi,
First of all, thank you for the code. I could successfully embed a jupyter qt gui inside my qt gui.
The thing is, I need to create multiple kernel and interact with them. In this case, I choosed QtkernelManager instead of InprocessKernelManager. 

Everything works great, except that when I want to `get_iopub_msg` to check if my kernel is busy runing code from my kernel client, I got an error message saying that
```
AttributeError: 'QtZMQSocketChannel' object has no attribute 'get_msg'
```

To replicate my program:

qt_jupyter.py:
```python
import sys
from PyQt5.QtWidgets import *
from qtconsole.rich_ipython_widget import RichJupyterWidget
from qtconsole.manager import QtKernelManager

class QIPythonWidget(RichJupyterWidget):
    """ Convenience class for a live IPython console widget. We can replace the standard banner using the
    customBanner argument"""

    def __init__(self, customBanner=None, *args, **kwargs):
        if customBanner != None:
            self.banner = customBanner
        super().__init__()

        self.font_size = 6
        self.kernel_manager = QtKernelManager()
        self.kernel_manager.start_kernel()
        self.kernel_manager.kernel.gui = 'qt'
        self.kernel_client = self._kernel_manager.client()
        self.kernel_client.start_channels()


        def stop():
            self.kernel_client.stop_channels()
            self.kernel_manager.shutdown_kernel()

        self.exit_requested.connect(stop)

    def shutdown_kernel(self):
        self.kernel_client.stop_channels()
        self.kernel_manager.shutdown_kernel()

    def restart_kernel(self):
        self.kernel_client.stop_channels()
        self.kernel_manager.shutdown_kernel()
        self.kernel_manager = QtKernelManager()
        self.kernel_manager.start_kernel()
        self.kernel_manager.kernel.gui = 'qt'
        self.kernel_client = self._kernel_manager.client()
        self.kernel_client.start_channels()


if __name__ == "__main__":
    app = QApplication(sys.argv)
    main = QIPythonWidget()
    main.show()
    sys.exit(app.exec_())

```

and then type `%run dummy_test2.py` in the console:
dummy_test2.py
```python
import time
import logging

logging.basicConfig(level=0)
while 1:
    print('foo')
    time.sleep(1)
    logging.debug('foo')
```

Could you please tell me how can I know if dummytest2 is finished rather than `get_iopub_msg` -> `state`? and is there anyway I can catch the level of logs?

Thank you so much!

**Comment by takluyver** [comment]
(I don't see `get_iopub_msg` anywhere in the code you show :-S )

You generally don't want to use the `get_msg` APIs in a Qt application; those are designed to block until they can return the necessary message, which will lock up your application while it waits. The Qt channels will emit a `message_received` signal when they receive a message: you should connect a handler to that signal and watch for kernel status messages.

**Comment by luoy2** [comment]
Thank you taluyver. so you mean I need to over right _handle_execute_result function in the rich_jupyter_widget?

**Comment by luoy2** [comment]
So the approach I am using now is overwriting the handle error reply message from the jupyter_widget class and summit a signal if there is an execution error. Is this the only way to detect a kernel statue? If there is other better ways, could you please have me some leads?

Thanks!

**Comment by takluyver** [comment]
I'm not very familiar with the Qt console architecture, so you may need some info from someone else, but briefly: `self.kernel_client.iopub_channel.message_received` should be a Qt signal object, i.e. a class of event which you can connect a callback to. Among the messages that gets will be the [kernel status messages](http://jupyter-client.readthedocs.io/en/latest/messaging.html#kernel-status) which tell you when the kernel changes between busy and idle. You shouldn't need to override other functions, just listen for those messages in your own code and use them to update your variable tracking the kernel status. Something like:


```python
# UNTESTED
def update_kernel_status(self, msg):
    if msg['header']['msg_type'] == 'status':
        self.kernel_status = msg['content']['execution_state']

self.kernel_client.iopub_channel.message_received.connect(self.update_kernel_status)
```

**Comment by luoy2** [comment]
Thank you for your help!

**Comment by luoy2** [comment]
Hi, I created a python script monitor app based on your qt_console class. It is basically a python script runner with some auditing functions. Would you mind if I post that repo on github? I will create a link in `readme.md` to referring to your repo.

**Comment by takluyver** [comment]
Go for it! :-). The Qt console, like all the Jupyter code, is open source, so reusing the code for something else and then sharing your code is positively encouraged.

**Comment by luoy2** [comment]
Thanks!
