### ISSUE TITLE
qtconsole fails to launch with Gtk-CRITICAL

### ISSUE THREAD

**Issue by apodemus** [jupyter/qtconsole#221]
I usually launch from terminal with: `jupyter qtconsole &` to run qtconsole in background.  However, since upgrading to ubuntu 17.04 I've started experiencing strange behaviour in which the following message is repeated about 100 times:

> (python3:31079):` Gtk-CRITICAL **: IA__gtk_widget_style_get: assertion 'GTK_IS_WIDGET (widget)' failed

... and interspersed with:
> QWidget::setMinimumSize:` (/MainWindow) The largest allowed size is (16777215,16777215)

The window that launches is transparent, flickers rapidly and is unresponsive.  I've tried to make a screencast to show what I mean by this, but that didn't manage to captured what is happening.  Also, the process consumes more than 1Gb of RAM which seems strange. 

Would appreciate some help in debugging this since I have no idea where to start!

**Version info:**
`uname -a`  Linux prometheus 4.10.0-22-generic #24-Ubuntu SMP Mon May 22 17:43:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
`python3 --version` Python 3.5.3
`ipython --version` 5.3.0
`qmake --version` Using Qt version 5.7.1 in /usr/lib/x86_64-linux-gnu
`pip freeze | grep PyQt5`  PyQt5==5.6
`jupyter --version` 4.3.0
`jupyter qtconsole --version` 4.2.1

**Comment by ccordoba12** [comment]
Please update PyQt5 and try again.

**Comment by apodemus** [comment]
That did it! Thanks for the tip!
