### ISSUE TITLE
%clear doesn't work on Windows

### ISSUE THREAD

**Issue by ccordoba12** [jupyter/qtconsole#223]
Unfortunately, the %clear magic doesn't clear consoles on Windows, and we'd like to have this working for Spyder.

@andfoy, please work on this one.

**Comment by andfoy** [comment]
I'll check it right away!

**Comment by andfoy** [comment]
@ccordoba12 I can't reproduce this issue:

![peek 06-07-2017 14-36](https://user-images.githubusercontent.com/1878982/27929474-ce08701a-6258-11e7-81fc-9a5996838914.gif)

**Comment by ccordoba12** [comment]
When you run `%clear` on Windows, the previous output is not removed, instead the prompt is moved to the top.

But on Linux and Mac, all output is removed on `%clear`, and that's what I'd like to see on Windows too.
