### ISSUE TITLE
qtconsole does not send is_complete_request

### ISSUE THREAD

**Issue by stevengj** [jupyter/qtconsole#23]
I was implementing the latest protocol in JuliaLang/IJulia.jl#325, and I wanted to test out my handling of the `is_complete_request message`. However, the qtconsole front-end does not seem to send this message to check whether inputs are complete; it just sends an execute_request whenever you hit <enter>.

See also jupyter/jupyter_console#11

**Comment by takluyver** [comment]
Closed by #20.

We introduced the `is_complete` message types before we made any of our own frontends use them. We just merged Min's changes in here to use it.
