### ISSUE TITLE
Release 4.3.1

### ISSUE THREAD

**Issue by ccordoba12** [jupyter/qtconsole#230]
This is a simple bugfix release.

cc'ing @minrk, @takluyver, @Carreau, @willingc and @JamiesHQ

**Comment by willingc** [comment]
Thanks @ccordoba12 for letting us know. I'm sure that Windows users appreciate the fix. 👍

**Comment by ccordoba12** [comment]
Yep, several frustrated Spyder users asked us for that fix ;-)

**Comment by ccordoba12** [comment]
Just as a side note: conda-forge is semi-broken right now, as reported here:

https://github.com/conda-forge/conda-forge.github.io/issues/426

So for now conda-forge users won't get this update.

Since I don't have time to resubmit the qtconsole recipe to staged-recipes, I'll wait for a fix to come the feedstock (I don't know how much time it could take, sorry).

**Comment by ccordoba12** [comment]
At the end I decided to readd the recipe to conda-forge to fix the problem:

https://github.com/conda-forge/staged-recipes/pull/3538

**Comment by JamiesHQ** [comment]
way to go @ccordoba12 !
