### ISSUE TITLE
Shortcut keys

### ISSUE THREAD

**Issue by ybouterfa** [jupyter/qtconsole#240]
Is there a way to modify the keyboard shortcuts in the qtconsole? I'd like to use the Emacs ones if possible.

Thanks.

**Comment by ccordoba12** [comment]
No, it's not possible right now, sorry.

**Comment by takluyver** [comment]
If you want to dig into the code, I think shortcuts are scattered through different files, but quite a few of them are defined in [console_widget.py](https://github.com/jupyter/qtconsole/blob/master/qtconsole/console_widget.py) - search for 'shortcut' in there and you'll find some.
