### ISSUE TITLE
Ctrl-Backspace behaves inconsistently in iPython qtconsole (within Spyder)

### ISSUE THREAD

**Issue by CAM-Gerlach** [jupyter/qtconsole#241]
I first submitted this over on the Spyder repo, but was helpfully informed the issue lies on this end. Thus:

## Description

Often, when sending or copying code to the console, I might want to delete a blank line or clean it up to all be on one line. However, unlike in the Spyder editor and most all other editors/consoles, Ctrl-Backspace doesn't just delete extra spaces and such from the current cursor position to the beginning of the line, but also the line break and the last word on the previous line. 

In the (perhaps uncommon) case one might actually want to delete either of these as well, another one or two taps on backspace key will do the trick, but conversely there is no easy way to replicate the other behavior, and given the inconsistency with the editor and most other applications it often leads to mistaken deletions. 

Therefore, the newline character and the blank spaces in a line should each be treated as separate words for the purposes of Ctrl-Backspace, as they are elsewhere.

**What steps will reproduce the problem?**

1. Copy or type a multiline statement into the console, e.g.
```
foo = ["foo", "foo", "foo",
          "foo", foo", "bar"]
```
2. Place cursor at beginning of second line text (e.g. with Home)
3. Hit Ctrl-Backspace

**What is the expected output? What do you see instead?**

Expected: Blank spaces are deleted, up to the beginning of the line, as in the Spyder editor and most other decent consoles
e.g.
```
foo = ["foo", "foo", "foo",
"foo", foo", "bar"]
```
and then an additional tap of Ctrl-Backspace gives
```
foo = ["foo", "foo", "foo","foo", foo", "bar"]
```
with further such keystrokes deleting successive "word" elements as normal.

Instead, with only one press of Ctrl-Backspace, I get
```
foo = ["foo", "foo", ""foo", foo", "bar"]
```
i.e. the blank spaces, the line break, and the last "word" element all deleted.

## Version and main components

* qtconsole 4.3.1
* IPython 6.1.0
* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows 8.1 x64

sys_info():
```
{'commit_hash': 'd86648c5d',
 'commit_source': 'installation',
 'default_encoding': 'utf-8',
 'ipython_path': 'C:\\Anaconda3\\lib\\site-packages\\IPython',
 'ipython_version': '6.1.0',
 'os_name': 'nt',
 'platform': 'Windows-8.1-6.3.9600-SP0',
 'sys_executable': 'C:\\Anaconda3\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSCv.1900 64 bit (AMD64)]'}
```

## Spyder/Jupyter Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by wmvanvliet** [comment]
Good catch. I'm working on a PR>

**Comment by ccordoba12** [comment]
@CAM-Gerlach, could you verify that PR #242 fixes this problem? Thanks!

**Comment by CAM-Gerlach** [comment]
Thanks! Will do, just need to get to my dev machine...

**Comment by CAMGerlach-Baron** [comment]
@ccordoba12 All fixed, except for another directly related case I didn't explictly mention above. See my reply on the PR #242 Thanks!
