### ISSUE TITLE
Is it possible to connect to other kernels ?

### ISSUE THREAD

**Issue by daegontaven** [jupyter/qtconsole#243]
Hi, I'm building an application that embeds an in-process qtconsole. I was wondering If i can connect QtConsole to IRuby or any kernels of my choosing. Could you provide any documentation for it ?

**Comment by daegontaven** [comment]
@minrk Could you please look into this ? According to the example provided:
https://github.com/jupyter/qtconsole/blob/6b099f7f128766ec905d5a8dd18dba763d4ac54a/examples/inprocess_qtconsole.py#L20-L23

`QtInProcessKernelManager()` seems to be a wrapper around `ipykernel` of IPython. It's already possible to connect to other kernels(eg for IRPython `jupyter qtconsole --kernel=ir`) from jupyter. My question is whether it can be done using in-process. Perhaps I could launch a subprocess of IRPython's kernel from my PyQt application and connect to it using methods provided by `RichJupyterWidget()`. However, I can't seem to find any public methods in that class. Also more worrying is the fact that it is inheriting from an `IpythonWidget` dummy class.

Does this imply there is no current in-process support for qtconsole ? If not, how can I start contributing to make it more general purpose ?

Thank you in advance ✌️

**Comment by takluyver** [comment]
You cannot run another kernel in-process (to be honest it doesn't work well even for Python). The supported way to use kernels is for them to be in a separate process.

**Comment by daegontaven** [comment]
@takluyver are there example on how to do it as a separate process(I think i meant separate process instead of in-process)? I see no examples in the documentation given [here](https://qtconsole.readthedocs.io/en/stable/#embedding-the-qtconsole-in-a-qt-application). How would I connect to a separate kernel ? How would I start the kernel(subprocess using jupyter command ?) ? Can you point to me to any information ?

**Comment by takluyver** [comment]
There should be examples, but there aren't, unfortunately. And I don't actually know how to do it. @ccordoba12 uses the Qt console embedded in Spyder, he might have a better idea what's needed.

**Comment by ccordoba12** [comment]
We have our own implementation of `qtconsole` and it's a complicated setup, but here it goes:

1. We have our own kernel spec to start our kernels:

    https://github.com/spyder-ide/spyder/blob/3.x/spyder/utils/ipython/kernelspec.py

2. We use it to create our kernel managers and clients, in the `create_kernel_manager_and_kernel_client` method of

    https://github.com/spyder-ide/spyder/blob/3.x/spyder/plugins/ipythonconsole.py

3. And finally, we connect our own clients (composed of a subclass of `RichJupyterWidget`, plus a web widget to give pertinent info to users) to those kernels, in the `connect_client_to_kernel` method of

    https://github.com/spyder-ide/spyder/blob/3.x/spyder/plugins/ipythonconsole.py

Hope it helps :-)

**Comment by takluyver** [comment]
I've opened #244 to add an example of embedding RichJupyterWidget with a kernel in a separate process.

**Comment by daegontaven** [comment]
@takluyver @ccordoba12 Thanks this is just what I needed. I think for my case [`MultiKernelManager`](https://jupyter-client.readthedocs.io/en/stable/api/manager.html#jupyter_client.MultiKernelManager) is more suitable. But I think I can adapt the code. Thanks you very much once again !

^_^
