### ISSUE TITLE
Rightarrow at the end of a line of a multiline input sends cursor all the way to end of input

### ISSUE THREAD

**Issue by CAM-Gerlach** [jupyter/qtconsole#245]
## Description

In `qtconsole`, either launched standalone or within Spyder, if I paste (or type) a multiline statement into the console, put my cursor at the end of any line, and press rightarrow, instead of going to the first char on the next line as one would expect, the cursor will instead jump all the way to the end of the last line of the statement (as if I pressed Ctrl-End). 

There seems to be no logical reason why this would be a feature, as one could simply press the aforementioned shortcut for the same effect, and it leaves no easy way to go to the first char on the next line other then downarrow + home; moreover, it breaks basic user expectations on how such text-based interfaces generally behave. As @wmvanvliet helpfully suggested it was probably a bug, I'm posting it here. I've tested this on multiple m,achines, OS versions and spyder/qtconsole installs, including a fresh anaconda install and the latest dev version as of two weeks ago, and all experienced the same behavior. As far as I'm aware, this has been the case for as long as I've been using qtconsole; only a couple months now.

**What steps will reproduce the problem?**

1. Copy or type a multiline statement into the console, e.g.
```
print("foo" + "bar"
      + "This is a "|
      + "test string "
      + "for qtconsole.")
```
2. Place cursor where indicated with "|" (or at the end of any other line)
3. Press rightarrow once

**What is the expected output? What do you see instead?**
For the above example, Expected:
```
print("foo" + "bar"
      + "This is a "
     |+ "test string "
      + "for qtconsole.")
```
Actual:
```
print("foo" + "bar"
      + "This is a "
      + "test string "
      + "for qtconsole.")|
```

## Version and main components

* qtconsole 4.3.1 and 4.4.0-dev (as of 2 weeks ago)
* IPython 6.1.0
* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows 8.1 Pro x64 and Windows 10 Ent x64

sys_info():
```
{'commit_hash': 'd86648c5d',
 'commit_source': 'installation',
 'default_encoding': 'utf-8',
 'ipython_path': 'C:\\Anaconda3\\lib\\site-packages\\IPython',
 'ipython_version': '6.1.0',
 'os_name': 'nt',
 'platform': 'Windows-8.1-6.3.9600-SP0',
 'sys_executable': 'C:\\Anaconda3\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSCv.1900 64 bit (AMD64)]'}
```

## Spyder/Jupyter Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment]
I posted this as requested; any updates? Anything more you need from me? Thanks!

**Comment by wmvanvliet** [comment]
Sorry for being so slow on this. We work on qtconsole only occasionally. I can reproduce the error. Thank you for raising the issue.

**Comment by CAM-Gerlach** [comment]
No worries! You're the one helping me out. Just wanted to make sure it didn't get lost or there was something more I could do on my end. Thanks!

**Comment by CAM-Gerlach** [comment]
@wmvanvliet If you want me to test the PR I can later today.

**Comment by wmvanvliet** [comment]
> If you want me to test the PR I can later today.

yes please!

**Comment by CAM-Gerlach** [comment]
Tested successfully, as noted on the PR thread.
