### ISSUE TITLE
Opening parentheses sometimes get swallowed

### ISSUE THREAD

**Issue by kohr-h** [jupyter/qtconsole#248]
This is a forward of https://github.com/spyder-ide/spyder/issues/5841. The sort version:

In the console, when typing
```python
>>> for name in dir():
...     if isinstance(getattr
```
the next opening parenthesis is swallowed, and the next ~248 as well. Then an exception occurs, and when entering the next opening paren, all the buffered ones are dumped at once. See the Spyder bug report for full details.

**Comment by CAMGerlach-Baron** [comment]
@kohr-h Suggest you just copy and paste the full report over here into your original issue post, as the Spyder one's likely to get closed (not that it goes anywhere; its just cleaner to have everything where it belongs). Thanks.

**Comment by kohr-h** [comment]
Alright, here it comes:

## Description

**What steps will reproduce the problem?**

1. Type
   ```python
   >>> for name in dir():
   ...     if isinstance(getattr
   ```
2. When trying to enter the next `(` nothing happens (apparently). No new character appears.
   If I keep my finger on the `(` button ("Let's crash this thing!"), after a while the below exception occurs:
   ```
     File "[...]/qtconsole/console_widget.py", line 413, in eventFilter
       return self._event_filter_console_keypress(event)
     File "[...]/spyder/widgets/ipythonconsole/debugging.py", line 108, in _event_filter_console_keypress
       self)._event_filter_console_keypress(event)
     File "[...]/qtconsole/frontend_widget.py", line 381, in _event_filter_console_keypress
       return super(FrontendWidget, self)._event_filter_console_keypress(event)
     File "[...]/qtconsole/console_widget.py", line 1444, in _event_filter_console_keypress
       self._keep_cursor_in_buffer()
     File "[...]/qtconsole/console_widget.py", line 1924, in _keep_cursor_in_buffer
       moved = not self._in_buffer()
     File "[...]/qtconsole/console_widget.py", line 1911, in _in_buffer
       prompt_line = self._get_prompt_cursor().blockNumber()
     File "[...]/qtconsole/console_widget.py", line 1693, in _get_prompt_cursor
       cursor.setPosition(self._prompt_pos)
     File "[...]/qtconsole/console_widget.py", line 1681, in _prompt_pos
       return min(self._prompt_cursor.position() + 1, self._get_end_pos())
     File "[...]/qtconsole/console_widget.py", line 1583, in _get_end_pos
       return self._get_end_cursor().position()
   RecursionError: maximum recursion depth exceeded
   ```
3. Then I delete the old input and type
   ```python
   >>> for name in dir
   ```
   and an opening `(`. The latter will freeze the console for a couple of seconds, and then the following output appears:
   ```
   for name in dir(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((
   ```
   These are 249 open parens.

I don't know if this occurs in other situations as well, but this is the only one I've seen so far.

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.4.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by kohr-h** [comment]
Just tested plain `jupyter qtconsole`, and there it doesn't happen. So that makes it more likely to be a Spyder bug.

**Comment by kohr-h** [comment]
Old issue, and it's in fact a Spyder issue. Closing this.
