### ISSUE TITLE
Implementing Block indent in qtconsole

### ISSUE THREAD

**Issue by JeremySikes73** [jupyter/qtconsole#249]
(Was https://github.com/ipython/ipython/issues/10927)

I'd like to see block indent implemented in qtconsole, it's a pet peeve I hit every day.
Wrapping a piece of code in an if tediously involves manually indenting N lines. Pasting in an indented
position also doesn't preserve the indentation of the block pasted.

If one of the developers would kindly point me in the right direction, I'll like to code this up. And If there's interest, a PR may follow.

**Comment by CAM-Gerlach** [comment]
Thanks for your interest in helping out! I'm not one of the developers, but the right direction would be likely  be submitting an issue (and PR, etc) on the actual qtconsole repo itself, as that is in fact a separate project; this one can be closed.

**Comment by CAM-Gerlach** [comment]
(My silly mistake; I got my tabs mixed up and though I was on the Spyder repo instead. Joke's on me, hah.) I'll delete this in a bit but wanted to minimize any confusion I'd caused).

**Comment by wmvanvliet** [comment]
Great that you would like to take a stab at this!

Take at look at `qtconsole/console_widget.py:1137`, the `_event_filter_console_keypress` function. This function intercepts the key presses. Look for the handling for the `Key_Tab` keypress (line 1334). You probably want to make this more intelligent, e.g. if text is selected, indent the selected lines. If this piece of code gets long-ish (say more than 4 lines), you want to put it into a private method (maybe `ConsoleWidget._indent()` or something) and call it.

Good luck! Let me know if you need more help.

**Comment by wmvanvliet** [comment]
Oh, and pasting indented code indeed strips the indentation. This is by design and is very useful for copy-pasting a snipped from a script and running it, without having to worry about indentation. This is something I myself and I expect many others do very frequently.

**Comment by JeremySikes73** [comment]
Thank you kindly for the pointer, I was hoping someone would save me time and narrow things down.

**Comment by JeremySikes73** [comment]
@wmvanvliet, about indentation: I agree that strippping the original indenation is the right thing, but "just" stripping it does the wrong thing when pasting into an indented position. An example should help clarify what I mean:

Source file:
```
class Foo(object):
   def bar(self):
         print("Look at me, I'm code!")   # line A, double indentation
         print("Me too! Me too!")         # line B
```
Say I copy Block AB, with indentation and paste it into qtconsole:
```
If True:
    _ # cursor here, <paste>
```
I'd expect to get:
```
If True:
    print("Look at me, I'm code!")   # line A, single indentation
    print("Me too! Me too!")            # line B, single indentation
```
But the actual result is:
```
If True:
    print("Look at me, I'm code!")   # line A, single indentation
print("Me too! Me too!")            # line B, single indentation
```
Indentation has meaning in python, change indentation and you change the meaning of the program. So this behaviour corrupts the meaning of the code snippet I pasted which Is why I say it's wrong.
