### ISSUE TITLE
On the many absent virtues of "Select All"

### ISSUE THREAD

**Issue by JeremySikes73** [jupyter/qtconsole#257]
In 5+ years of using qtconsole, I have never once used Ctrl+A/Select all. Except when I forget that it doesn't what I expect, which is to select the entire contents of the current cell.

Copying the whole buffer, with the banner and all seems like a very rare need indeed. Selecting an entire cell, on the other hand, is something I want to do several times an hour. 

Adding another "Select Cell" action is easy enough, but I wanted to suggest going further and having that take over <kbd>Ctrl-Shift-A</kbd> entirely. 

Is it just my minority opinion, or do the developers feel the same way? I'd be happy to submit the PR, it's a trivial change code-wise.

@ccordoba12 @takluyver @wmvanvliet

**Comment by takluyver** [comment]
If Ctrl-Shift-A doesn't conflict with anything, I'd say go for that. I'd be reluctant to change what Ctrl-A does after it's done it for so long - someone is bound to be using it, and consistency is a good thing.

**Comment by wmvanvliet** [comment]
Isn't CTRL+A bound to act as HOME key (consistent with emacs bindings)?

**Comment by JeremySikes73** [comment]
I originaly wrote Ctrl-A by mistake, Ctrl-Shift-A  is currently bound to "select all". Ctrl-A really can't be changed (goto start of line), I agree.

How about turning Ctrl-Shift-A from "select all" to "select cell" first, than if pressed again while the cell is selected, extending the selection to the the whole document? that seems minimally disruptive.

**Comment by takluyver** [comment]
That sounds reasonable.

**Comment by ccordoba12** [comment]
+1 from me too.

**Comment by CAM-Gerlach** [comment]
Would be very useful; I had a similar issue in the Spyder repo a while back. Seems to make far more sense just to select the code than all the decoration around it.

**Comment by Kentzo** [comment]
It looks like on macOS Cmd-A still select whole content of the notebook. Cmd-Shift-A does nothing.

**Comment by CAM-Gerlach** [comment]
@Kentzo Are you using QtConsole 4.4.0 or 4.4.1? Also, I assume by ``notebook`` you mean "session", unless you are referring to Jupyter Notebook which is a different application entirely from QtConsole.

**Comment by Kentzo** [comment]
`qtconsole.__version__` is 4.4.1. You're correct, I meant the current interactive session.

**Comment by CAM-Gerlach** [comment]
@Kentzo Okay, thanks. I tested it just now on both Windows (8.1 x64) and Linux (Fedora 28 LXQt) with QtConsole 4.4.1 and Qt/PyQt 5.9.6/5.9.2, and it worked as advertised. As such, this appears likely to be a platform-specific issue. Is there someone on macOS who could test/look into this?

**Comment by Kentzo** [comment]
Before anyone will spend time on it, I'd like to ensure I'm using it correctly.

With non-empty cell pressing the Cmd-A shortcut should first select the cell and only then select all, correct? Are there any perquisites, e.g. a mode one should enter?

**Comment by Kentzo** [comment]
The Select Cell/All action from the context menu is working as expected: first it selects cell, then it selects all.

**Comment by CAM-Gerlach** [comment]
Good thinking to check! However, I believe you are.

> With non-empty cell pressing the Cmd-A shortcut should first select the cell and only then select all, correct?

Yes. There's an example on the [Jupyter blog post](https://blog.jupyter.org/jupyter-qtconsole-4-4-81f2eaad5706) I wrote about the new release.

> The Select Cell/All action from the context menu is working as expected: first it selects cell, then it selects all.

As I suspected, it sounds like its an issue with something to do with the macOS keyboard bindings. Try different combinations of modifier keys (Shift, Control, Command, Alt) and A to see if any of them trigger it.

**Comment by CAM-Gerlach** [comment]
Okay, thanks @Kentzo for looking into it! Do you have any additional thoughts on if/how this could be better handled by QtConsole itself, if that's possible within the OS constraints? If so, and @ccordoba12 agrees, perhaps you could consider creating a PR to implement such, since I don't know if any of the main devs are Mac users...and I'm neither of which myself; I just do some minor stuff with the Spyder project. QtConsole is written in Python, so assuming that's what you use it for it shouldn't be too terribly difficult.

**Comment by Kentzo** [comment]
My best guess is that QTextEdit (and likely QPlainTextEdit) handle Cmd-A on their own.

**Comment by ccordoba12** [comment]
@Kentzo, did you try Ctrl+A instead of Cmd+A?

**Comment by Kentzo** [comment]
Ctrl+A is handled as Meta-A, i.e. moves cursor to the beginning of the page.

**Comment by CAM-Gerlach** [comment]
> Ctrl+A is handled as Meta-A, i.e. moves cursor to the beginning of the line.

That's as expected, since ``Control`` is effectively the ``Meta`` key on macOS, while ``Command`` = ``Ctrl``.

**Comment by Kentzo** [comment]
Apparently, QWidgetTextControl overrides standard shortcuts like Select All (ctrl-A or cmd-A). The event then does not reach neither qmainwindow nor qconsolewidget.

I guess change from Ctrl-A to Ctrl-Shift-A is related to this problem. Although I'm still puzzled why it's disabled for macOS.

**Comment by Kentzo** [comment]
The solution I propose is:

1. Remove conditional mapping in [console_widget.py](https://github.com/jupyter/qtconsole/blob/cd35c71854dbf0b5ac89523f06cc39b93c68ec69/qtconsole/console_widget.py#L322-L325) and [mainwindow.py](https://github.com/jupyter/qtconsole/blob/cd35c71854dbf0b5ac89523f06cc39b93c68ec69/qtconsole/mainwindow.py#L502-L505)
2. Reject Select All events coming into [the control](https://github.com/jupyter/qtconsole/blob/master/qtconsole/console_widget.py#L406) by adding
    ```
    if obj == self._control and event == QtGui.QKeySequence.SelectAll:
        return True
    ```

**Comment by Kentzo** [comment]
@minrk Could you given an insight what specific problem these overrides (https://github.com/jupyter/qtconsole/commit/478f2437cd6b48f156031a58969678a716646d40 and https://github.com/jupyter/qtconsole/commit/f2785541618a940ad74363e6b28d0a542e3c1a87a) solved?
