### ISSUE TITLE
IndexError when copying only the "In [1]: " part of an input line with Ctrl+C

### ISSUE THREAD

**Issue by CAM-Gerlach** [jupyter/qtconsole#264]
Credit to @BlckKnght in [Spyder #5095](https://github.com/spyder-ide/spyder/issues/5095) for providing a detailed description of the issue. Created an issue here per @ccordoba12 's request.

## Description

If the user tries to copy only the prompt and its trailing space from ``qtconsole`` with <kbd>Ctrl</kbd>+<kbd>c</kbd>, an IndexError is generated. The text does get copied; also the error does not occur with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>c</kbd>.

**What steps will reproduce the problem?**

1. Run any line of code in an IPython console (it can be a trivial expression, like `42` or `"spam"`).
2. Select the "In [1]: " prompt from the previous line. Make sure to include the space between the prompt and the actual statement in the selection.
3. Press <kbd>Ctrl</kbd>+<kbd>c</kbd> to copy the selected text.

**What is the expected output? What do you see instead?**

The user expected the prompt to be copied silently. Instead, an error is thrown, with the traceback below. The text *is* successfully copied to the clipboard however. @BlckKnght suggested guessed it might be occurring because "the program tries to trim out the prompt (as it does successfully if I select a larger amount of text including some of the statement on the line). I'd guess there's an off-by-one error in the code somewhere."

**Please provide any additional information below**

  File "S:\Python36\lib\site-packages\qtconsole\console_widget.py", line 412, in eventFilter
    return self._event_filter_console_keypress(event)
  File "S:\Python36\lib\site-packages\spyder\widgets\ipythonconsole\debugging.py", line 103, in _event_filter_console_keypress
    self)._event_filter_console_keypress(event)
  File "S:\Python36\lib\site-packages\qtconsole\frontend_widget.py", line 381, in _event_filter_console_keypress
    return super(FrontendWidget, self)._event_filter_console_keypress(event)
  File "S:\Python36\lib\site-packages\qtconsole\console_widget.py", line 1424, in _event_filter_console_keypress
    self.copy()
  File "S:\Python36\lib\site-packages\qtconsole\frontend_widget.py", line 249, in copy
    was_newline = text[-1] == '\n'
IndexError: string index out of range

## Version and main components

* Spyder Version: <=3.2.0-3.2.6
* Python Version: <=3.6.2-3.6.4
* Qt Versions: 5.7.1, PyQt5 5.7.1 and 5.6.2/5.6 on Windows 8.1 x64 Pro
* qtconsole Version: <=4.3.0? - 4.3.1

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one. Let's catch `IndexError` here

https://github.com/jupyter/qtconsole/blob/master/qtconsole/frontend_widget.py#L238

and make `was_newline = False` in the except part.

**Comment by CAM-Gerlach** [comment]
Thanks!
