### ISSUE TITLE
Qtconsole hangs at exit after update to Tornado 5.0

### ISSUE THREAD

**Issue by ccordoba12** [jupyter/qtconsole#275]
Simply starting qtconsole from a terminal and then closing it makes it hang. You need to press `Ctrl+C` to interrupt a hanging thread and make it finish.

@minrk, the same thing happens to Spyder. Could you help us with this one? I really don't understand how to fix it.

By the way, `jupyter-console` doesn't show this behavior. That's why I didn't fill this report in `ipykernel`.

**Comment by minrk** [comment]
@ccordoba12 I believe this is fixed by https://github.com/jupyter/jupyter_client/pull/352 can you test?

**Comment by ccordoba12** [comment]
On it, thanks!
