### ISSUE TITLE
Notebook in qt

### ISSUE THREAD

**Issue by gkvoelkl** [jupyter/qtconsole#277]
I embedded qtconsole in my qt application and it works great.

Is there a way to use Jupyter notebooks in an own qt application?

**Comment by takluyver** [comment]
You would have to embed a web browser widget. The browser included as QtWebkit is also not very modern; I can't remember if it supports all the features the notebook needs.

**Comment by ccordoba12** [comment]
Yes, you can. For an example, please see

https://github.com/spyder-ide/spyder-notebook

Closing because this is not a bug report.
