### ISSUE TITLE
Infinite loop after using pyinstaller

### ISSUE THREAD

**Issue by kakirolooooo** [jupyter/qtconsole#281]
I'm trying to make a .exe of an application created with pyqt and qtconsole. I get the same error with my code as with this example -> https://github.com/jupyter/qtconsole/blob/master/examples/embed_qtconsole.py 
Here is a picture of the execute.
![imagen](https://user-images.githubusercontent.com/12657528/38863687-b6e3900c-4238-11e8-88e8-69d2a83e744b.png)

The program works fine executing the code in the normal way. I tried to add this line: multiprocessing.freeze_support() like the wiki of pyinstaller says but without any effect
https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing

Can anybody help? 
So much thanks

**Comment by ccordoba12** [comment]
Sorry, this is out of scope for the help we can offer you, which is about problems with qtconsole itself, not when it's embedded by bundle creators like Pyinstaller.
