### ISSUE TITLE
Wrong kernel uses python.exe instead of pythonw.exe

### ISSUE THREAD

**Issue by dashesy** [jupyter/qtconsole#283]
I have Anaconda (Python3, conda 4.5.1) with Python2 installed as a virtual environment called py27.
```text
Jupyter QtConsole 4.3.1
Python 2.7.14 |Anaconda custom (64-bit)| (default, Nov  8 2017, 13:40:45) [MSC v.1500 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 5.4.1 -- An enhanced Interactive Python.
```

There is kernel.json file here at C:\Anaconda3\envs\py27\share\jupyter\kernels\python2

With this content:
 
```json
{
 "display_name": "Python 2", 
 "language": "python", 
 "argv": [
  "C:\\Anaconda3\\envs\\py27\\python.exe", 
  "-m", 
  "ipykernel_launcher", 
  "-f", 
  "{connection_file}"
 ]
}
```  

The generated shortcut for `Jupyter QTConsole (py27)` (menuinst) uses this:

C:\Anaconda3\envs\py27\pythonw.exe C:\Anaconda3\cwp.py C:\Anaconda3\envs\py27 "C:/Anaconda3/envs/py27/pythonw.exe" "C:/Anaconda3/envs/py27/Scripts/jupyter-qtconsole-script.py"

Even though pythonw is used there a console was opening. I also tried 

C:\Anaconda3\pythonw.exe C:\Anaconda3\cwp.py C:\Anaconda3\envs\py27 "C:/Anaconda3/envs/py27/pythonw.exe" "C:/Anaconda3/envs/py27/Scripts/jupyter-qtconsole-script.py"

and various other incantations, but none got rid of the MSDos console. Finally I looked at: 

```bash
jupyter kernelspec list
```

from [here](https://stackoverflow.com/questions/38909209/ipython-qtconsole-starts-wrong-python-environment) and saw why pythonw was replaced with python.

I wonder how that kernel was created, and why it is not using pythonw, when I change it to pythonw everything works. Also, this whole combination of `cwp.py` pythonw.exe from root, or `pythonw.exe` from environment is already too confusing, addition of a kernel that can change the executable is an extra complexity.

**Comment by ccordoba12** [comment]
Qtconsole is not in charge of creating `kernel.json` files, so there's nothing we can do about it, sorry.

**Comment by takluyver** [comment]
An upcoming release of jupyter_client will prevent it from creating console windows: https://github.com/jupyter/jupyter_client/pull/346

**Comment by dashesy** [comment]
@takluyver that is great! I just created another conda environment and sure enough the kernel was using `python.exe` again.

**Comment by Taza53** [comment]
help this is not working

Jupyter QtConsole 4.3.1
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.0.1 -- An enhanced Interactive Python. Type '?' for help.

import tensorflow
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-d6579f534729> in <module>
----> 1 import tensorflow

D:\program_file_x\Anaconda2\envs\anaconda3\lib\site-packages\tensorflow\__init__.py in <module>
     20 
     21 # pylint: disable=g-bad-import-order
---> 22 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     23 
     24 try:

D:\program_file_x\Anaconda2\envs\anaconda3\lib\site-packages\tensorflow\python\__init__.py in <module>
     79 # Bring in subpackages.
     80 from tensorflow.python import data
---> 81 from tensorflow.python import keras
     82 from tensorflow.python.feature_column import feature_column_lib as feature_column
     83 from tensorflow.python.layers import layers

D:\program_file_x\Anaconda2\envs\anaconda3\lib\site-packages\tensorflow\python\keras\__init__.py in <module>
     22 from __future__ import print_function
     23 
---> 24 from tensorflow.python.keras import activations
     25 from tensorflow.python.keras import applications
     26 from tensorflow.python.keras import backend

D:\program_file_x\Anaconda2\envs\anaconda3\lib\site-packages\tensorflow\python\keras\activations\__init__.py in <module>
     20 
     21 # Activation functions.
---> 22 from tensorflow.python.keras._impl.keras.activations import elu
     23 from tensorflow.python.keras._impl.keras.activations import hard_sigmoid
     24 from tensorflow.python.keras._impl.keras.activations import linear

D:\program_file_x\Anaconda2\envs\anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\__init__.py in <module>
     19 from __future__ import print_function
     20 
---> 21 from tensorflow.python.keras._impl.keras import activations
     22 from tensorflow.python.keras._impl.keras import applications
     23 from tensorflow.python.keras._impl.keras import backend

D:\program_file_x\Anaconda2\envs\anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\activations.py in <module>
     21 import six
     22 
---> 23 from tensorflow.python.keras._impl.keras import backend as K
     24 from tensorflow.python.keras._impl.keras.utils.generic_utils import deserialize_keras_object
     25 from tensorflow.python.layers.base import Layer

D:\program_file_x\Anaconda2\envs\anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\backend.py in <module>
     36 from tensorflow.python.framework import sparse_tensor
     37 from tensorflow.python.framework import tensor_util
---> 38 from tensorflow.python.layers import base as tf_base_layers
     39 from tensorflow.python.ops import array_ops
     40 from tensorflow.python.ops import clip_ops

D:\program_file_x\Anaconda2\envs\anaconda3\lib\site-packages\tensorflow\python\layers\base.py in <module>
     23 from tensorflow.python.framework import dtypes
     24 from tensorflow.python.framework import ops
---> 25 from tensorflow.python.keras.engine import base_layer
     26 from tensorflow.python.ops import variable_scope as vs
     27 from tensorflow.python.ops import variables as tf_variables

D:\program_file_x\Anaconda2\envs\anaconda3\lib\site-packages\tensorflow\python\keras\engine\__init__.py in <module>
     21 # TODO(fchollet): Remove hourglass imports once external code is done importing
     22 # non-public APIs.
---> 23 from tensorflow.python.keras.engine.base_layer import InputSpec
     24 from tensorflow.python.keras.engine.base_layer import Layer
     25 from tensorflow.python.keras.engine.input_layer import Input

D:\program_file_x\Anaconda2\envs\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py in <module>
     32 from tensorflow.python.framework import tensor_shape
     33 from tensorflow.python.framework import tensor_util
---> 34 from tensorflow.python.keras import backend
     35 from tensorflow.python.keras import constraints
     36 from tensorflow.python.keras import initializers

D:\program_file_x\Anaconda2\envs\anaconda3\lib\site-packages\tensorflow\python\keras\backend\__init__.py in <module>
     20 
     21 # pylint: disable=redefined-builtin
---> 22 from tensorflow.python.keras._impl.keras.backend import abs
     23 from tensorflow.python.keras._impl.keras.backend import all
     24 from tensorflow.python.keras._impl.keras.backend import any

ImportError: cannot import name 'abs'
