### ISSUE TITLE
Cannot exit ipdb interactive mode with out restarting the console

### ISSUE THREAD

**Issue by bcolsen** [jupyter/qtconsole#289]
## Problem Description

If you enter pdb interactive mode there is no way to return to ipdb or ipython. The proper way to exit is by using `ctrl-d`.  `ctrl-d` works as it should in the ipython terminal console but not the qtconsole. 

This bug was discovered while solving this: https://github.com/spyder-ide/spyder/issues/7386

### What steps reproduce the problem?

1. enter debugging `%debug print()`
2. type `interact` at the `ipdb>` prompt
3. press `ctrl-d`

### What is the expected output? What do you see instead?

The interactive ipdb prompt doesn't close so there is no way to exit 

### Versions
'commit_hash': '7f10f7bb3',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/home/user/anaconda3/lib/python3.6/site-packages/IPython',
 'ipython_version': '6.4.0',
 'os_name': 'posix',
 'platform': 'Linux-4.13.0-45-generic-x86_64-with-debian-stretch-sid',
 'sys_executable': '/home/user/anaconda3/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.6.5 |Anaconda custom (64-bit)| (default, Apr 29 2018, '
                '16:14:56) \n'
                '[GCC 7.2.0]'}
Jupyter QtConsole 4.3.1

**Comment by ccordoba12** [comment]
Thanks @bcolsen. No idea how to address this one though.

**Comment by bcolsen** [comment]
@ccordoba12 It looks like ctrl-d inputs the [EOT](https://en.wikipedia.org/wiki/End-of-Transmission_character) character `0x4`.

If I type an EOT into the qtconsole and press enter it works as expected.

![eof](https://user-images.githubusercontent.com/10513354/42398584-9af64640-8127-11e8-840b-cb9a9e8c238a.png)

I guess ctrl-d could be used as a short cut to "execute" a EOT character

**Comment by ccordoba12** [comment]
Nice! Thanks for digging this one up!

Would you mind to create a PR to implement this?
