### ISSUE TITLE
Release 4.4

### ISSUE THREAD

**Issue by ccordoba12** [jupyter/qtconsole#293]
4.4 contains important fixes and it's time to release it.

cc'ing @minrk, @takluyver, @Carreau, @willingc and @JamiesHQ

**Comment by ccordoba12** [comment]
I'm going to do the release right now.

**Comment by Carreau** [comment]
Thanks ! Awesome !

**Comment by Carreau** [comment]
BTW do you want /need access to the Jupyter Blog to make annouces ?

**Comment by ccordoba12** [comment]
I don't have time to do that but probably our blog/docs maintainer does. @CAM-Gerlach, are you interested in @Carreau's offer?

**Comment by ccordoba12** [comment]
> Any particular changes from changelog.rst you'd like me to focus on

* Syntax highlighting
* Fix an error when copying code with a prompt inside it.
* Fix the behavior of Ctrl+Backspace and Ctrl+Del (I think you were the one who reported this).
* Fix input from other clients. @wmvanvliet, could you explain us what that change was about? I didn't completely get it.

**Comment by Carreau** [comment]
@CAM-Gerlach it's hosted on medium, so I just need your medium username to give you access. 
No particular format style, what you think will fit for your audience.

**Comment by CAM-Gerlach** [comment]
@Carreau Okay, I created one. 

``<rant>``
Their account system is totally bonkers; all their docs say they accept Facebook, Google, Twitter and email methods but only the first two are listed anywhere—and even in their docs, the "email" system is bananas and requires you to click a link in an email every time you sign in, but no password required...absurd. So I guess I have to "link" my Google account...ugh. Then it tries to force me to select at least three "interests" for their analytics algorithm. However, I enter the root URL and am able to escape the screen and am apparently signed in, judging by my logo in the corner. However, once I search for and load the Jupyter page, now all of sudden I'm not signed in again. I click "sign in" again and now I'm signed in.
``</rant>``

Man, I should post that on Medium about how hard it was to sign up to post that on Medium. Gives "Medium Difficulty" a whole new meaning. So meta...

Anyway, my username is ``@widenetservices``

Thanks!

**Comment by wmvanvliet** [comment]
## Input from other clients

One of the cool things about the Jupyter client/server architecture is that potentially you can integrate any text editor you want with any Python console (IPython, QtConsole) you want. Build your own Spyder/MATLAB-like IDE from the components you want. Most editors have a plugin to send text to the kernel.

When you send a snippet of text to the kernel, it is often useful to have it printed to the console as well as the output. Spyder and MATLAB both do this. This behaviour can be activated by setting `c.ConsoleWidget.include_other_output = True`. Unfortunately, the output was broken in QtConsole. The "output from other clients" was not properly syntax highlighted and indented.

The changes in QtConsole 4.4.0 make the output from other clients (e.g. your text editor) super nice:
https://www.youtube.com/watch?v=Fi_Xd6h4ncw

**Comment by Carreau** [comment]
> Anyway, my username is @widenetservices

Added you you should be able to login at https://blog.jupyter.org/ ... I guess. Let me know if you need anything else.

> `<rant>`

Well you don't need to try to convince me, I'm not a [huge fan](https://xkcd.com/1378/) of medium. As for login with other than facebook/gmail, they hide it pretty well. You need to sign in while you sign in so that you can sign in while you sign in
![medium](https://user-images.githubusercontent.com/335567/44108045-0fc1e386-9fae-11e8-8db2-cc1c22b96264.gif)

**Comment by CAM-Gerlach** [comment]
@Carreau Nice, thanks! I'll try to write it up by this weekend, so hopefully it will be up by around the time the updated packages hit conda ``defaults``. I can also x-post a link to it and a short paragraph or two about its relevance to Spyder on [our blog](https://www.spyder-ide.org/blog/) after it and our 3.3.0/3.3.1 post goes up.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 @Carreau Hey; after being rather busy with the start of classes, starting in a new research position, and getting several organizations' websites up and running, and some Spyder stuff, I've written up the post. Please review it [here](https://medium.com/@CAM.Gerlach/jupyter-qtconsole-4-4-81f2eaad5706) for accuracy, style and typos, etc. Thanks!

**Comment by willingc** [comment]
Nicely done @CAM-Gerlach 👍

**Comment by CAM-Gerlach** [comment]
@Carreau Will do as after @ccordoba12 gets his comments in; he has a few but won't be able to submit them until tomorrow. Thanks!

**Comment by CAM-Gerlach** [comment]
@Carreau FYI, I added a final paragraph to wrap it up properly. I planned to from the beginning, but wanted to come at it with a fresh pair of eyes so I was happy with it.

**Comment by wmvanvliet** [comment]
Nice post! One thing though:

> check out Marjin’s blog post

Marjin -> Marijn

**Comment by CAM-Gerlach** [comment]
@wmvanvliet Really sorry about that; I copied and pasted from your name on Github to try to make absolutely sure I wouldn't make that mistake, but somehow still screwed it up anyway in that spot. Fixed now.

**Comment by CAM-Gerlach** [comment]
@Carreau Carlos just finished his review, so I'll submit it for final approval as requested. Thanks!

**Comment by Carreau** [comment]
Scheduled for Tuesday 8am Pacific (I think). That's apparently around the right time to get lots of clicks.

**Comment by CAM-Gerlach** [comment]
Okay, nice!

**Comment by ccordoba12** [comment]
Thanks @Carreau!

**Comment by CAM-Gerlach** [comment]
@Carreau Just FYI, I'm planning on submitting short blurb to the Spyder blog linking to the Jupyter post, since many of these new features were developed, suggested, and will have a significant positive impact on Spyder users, and is a once a year major update.
