### ISSUE TITLE
How to get separate input and output

### ISSUE THREAD

**Issue by pdeffebach** [jupyter/qtconsole#300]
I am wondering if in qtconsole it is possible to have input be at the bottom of your screen always and output always above it, like the console more in Jupyter Lab. 

```
x = 1
Out[7]: 1

x = rand(10)
Out[8]: 
10-element Array{Float64,1}:
 0.6512810853906847  
 0.008043873199802487
 0.38312297400487005 
 0.8295295112579473  
 0.874572921737717   
 0.213512780800462   
 0.3438725160467879  
 0.2816542992108786  
 0.31351256371583114 
 0.5612601363375331  

y = x .+ 1
Out[9]: 
10-element Array{Float64,1}:
 1.6512810853906847
 1.0080438731998025
 1.38312297400487  
 1.8295295112579473
 1.874572921737717 
 1.213512780800462 
 1.343872516046788 
 1.2816542992108786
 1.3135125637158311
 1.5612601363375331

---------------------------------------------------
In[10]: The input is always down here... and the top part 
scrolls separately than this part. 
```

**Comment by wmvanvliet** [comment]
Currently, QtConsole doesn't do this, but it could be implemented. I can see the utility in this.

@ccordoba12 WDYT? It makes sense. Right now, we have a single text buffer for both input and output, and we have to rely on tricky markers to keep track of the position of the prompt and input location. A lot of logic is devoted to separating our input field from the output. If we instead make two text buffers, one for input and one for output, it would actually greatly simplify the code. It would be a major change in the way QtConsole looks and behaves though.

**Comment by ccordoba12** [comment]
I like the current approach. I agree with this change only if it's optional but not if it's the only approach from now on.

**Comment by pdeffebach** [comment]
Sometimes you want to input a command based on the output you see. If that output is long, you have to scroll up to see the output then scroll back down to input it. This is a bit of a pain. 

Stata and the Jupyterlab console behave like this, and I like it a lot. It doesn't seem to be on many people's radar though. I'm glad you are open to the idea of implementing this.

**Comment by wmvanvliet** [comment]
> I like the current approach. I agree with this change only if it's optional but not if it's the only approach from now on.

Then we probably shouldn't do it. I feel that breaking off the input in a separate textbuffer would require too big changes to be kept alongside the current implementation.

**Comment by pdeffebach** [comment]
Fair enough. Thanks for considering it.  Though next time you work in qtconsole, think about how much time you spend scrolling! It's a feature I'm shopping around for, so to speak.
