### ISSUE TITLE
Kernel Uninterruptible on Python 3.7

### ISSUE THREAD

**Issue by spauka** [jupyter/qtconsole#310]
Kernels are uninterruptible in QtConsole using Python 3.7.

For example, the following code is run inside the terminal:
```py
In [1]: import time

In [2]: while True:
   ...:     time.sleep(0.1)
```
following which I am unable to stop execution, either by pressing `Ctrl-C` or the "Interrupt current Kernel" menu item.

Running the same code in ipython in a console window succeeds in stopping execution.

This issue appears in the latest Spyder as well, and is reported here: https://github.com/spyder-ide/spyder/issues/8013 but seems to be a QtConsole bug.

### System Information
Windows 10
Python 3.7.1 (default, Oct 23 2018, 22:56:47) [MSC v.1912 64 bit (AMD64)]
IPython 7.1.1
ipykernel 5.1.0
qtconsole 4.4.2

### To Reproduce failing version
```cmd
conda create -n py37clean python=3.7
conda install qtconsole
jupyter qtconsole
```

### To Reproduce working version 3.6
```
conda create -n py36clean python=3.6
conda install qtconsole
jupyter qtconsole
```

**Comment by ccordoba12** [comment]
@spauka, does this also happen in the Jupyter notebook?

**Comment by spauka** [comment]
@ccordoba12 Just tried it out, and it does! The kernel is uninterruptible with both "Ctrl-C" and the various interrupt buttons.

Looks like the issue might run even deeper than qtconsole. Any idea what the source might be?

**Comment by ccordoba12** [comment]
Yes, that's correct.
