### ISSUE TITLE
inprocess kernel - "ERROR: execution aborted" after any exception

### ISSUE THREAD

**Issue by kubaraczkowski** [jupyter/qtconsole#318]
Hi, 

I've just switched to macOS and have troubles with qtconsole's inprocess kernel used for embedding the console in an existing application. On Windows/Linux all is fine.

Trying to run https://github.com/jupyter/qtconsole/blob/master/examples/inprocess_qtconsole.py yields a working console window, however...

After _any_ exception (e.g. 1/0) the console only replies with:

> ERROR: execution aborted

Restarting kernel doesn't work, no commands get executed, matching crashes on:

> qtconsole/jupyter_widget.py", line 152, in _handle_complete_reply
>     matches = content['matches']
> KeyError: 'matches'
> Abort trap: 6

Any suggestions?

**Comment by ccordoba12** [comment]
A pull request is welcome to fix this because we don't have time to address it right now.

**Comment by rayosborn** [comment]
We use the inprocess kernel in [NeXpy](http://nexpy.github.io/nexpy/), and strangely enough I have had no problem on Macs or Linux, but a Windows user has reported the issue. Unfortunately, I debug on a Mac, and the in-process kernel is a very low priority for the Jupyter developers, even though it's extremely useful as the only way of embedding an IPython shell in a GUI with shared namespace. 

A quick look at the code suggests that the message content status is not being updated after an error is raised. The relevant lines are [here](https://github.com/jupyter/qtconsole/blob/06cd5441fa5ac975bfad6d9076962e138060354f/qtconsole/frontend_widget.py#L439-L444). I will have to investigate where the status needs to be reset, but it's a puzzle why it should vary from system to system. Can you please post what version of the qtconsole you are running?

**Comment by rayosborn** [comment]
I have found out that the error is associated with updates to the [ipykernel](https://github.com/ipython/ipykernel) library. Upgrading it from v4.10.0 to v5.0.0 causes the problem on my Mac. I think it's unfortunate that it is necessary to individually update so many different libraries separately - it's not enough to update IPython to v7.2 or qtconsole to v4.4.3. You also have to update ipykernel as well. That means that a quick fix is to downgrade to ipykernel v4.10.0.

This issue has already been reported as an ipykernel issue - see ipython/ipykernel#370.

**Comment by rayosborn** [comment]
I have submitted a Pull Request (ipython/ipykernel#376), which I hope will fix this issue. It's not really a qtconsole issue so this issue should probably be closed.

**Comment by ccordoba12** [comment]
Thanks!
