### ISSUE TITLE
Completion detection no longer works with InProcessKernel

### ISSUE THREAD

**Issue by rabryan** [jupyter/qtconsole#32]
When using an InProcessKernel, completion detection no longer works (i.e. hitting the Enter key always results in a continuation line, even though a complete python statement has been entered).  

A workaround is to use Shift+Enter instead of Enter to execute commands.  

I think this bug was introduced by changes to frontend_widget.is_complete() from:

https://github.com/jupyter/qtconsole/commit/c5f2ea47bc68275aa60b86329fb6737f9a168c23

**Comment by minrk** [comment]
We'll need to change how the InProcessKernel works so that it properly responds to `is_complete_request`s.

**Comment by minrk** [comment]
Needs a patch in a few places, but should work after #33 and a couple patches to client and inprocess.

Boy, do I wish inprocess were its own repo...

**Comment by johnw3d** [comment]
The current master (4.1.0.dev) with the above patch doesn't seem to resolve this issue, I'm still getting msg timeouts and no completion-checking.  Or do I need to get the latest dev version of the rest of jupyter?

**Comment by minrk** [comment]
It will require a release of ipykernel and jupyter-client before this is fully resolved.

**Comment by rabryan** [comment]
Yeah, I installed the latest master of ipykernel and jupyter-client and
everything works as expected.

On Sat, Sep 26, 2015 at 10:38 AM, johnw3d <notifications@github.com> wrote:

> The current master (4.1.0.dev) with the above patch doesn't seem to
> resolve this issue, I'm still getting msg timeouts and no
> completion-checking. Or do I need to get the latest dev version of the rest
> of jupyter?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/qtconsole/issues/32#issuecomment-143456691>.
>



-- 
Richard A Bryan
r@rabryan.org

404.939.3821 (google voice)
404.578.2121 (cell)

**Comment by minrk** [comment]
I'll try to remember to ping this issue when there's been a release of everything with the necessary fixes (I wouldn't count on me to remember, though). 4.1 of each should do it.

**Comment by chadawagner** [comment]
Seems to still be an issue for me, with jupyter-client and ipykernel both 4.1.1. Is there anything else I should update?

**Comment by chrisgee** [comment]
Hey, I am on 

certifi-2016.2.28 ipykernel-4.3.1 jupyter-client-4.2.2 jupyter-console-4.1.1 jupyter-core-4.1.0 mistune-0.7.2 notebook-4.1.0 pygments-2.1.3 pyzmq-15.2.0 qtconsole-4.2.0 terminado-0.6  ipython-4.1.2

and seeing similar things in qtconsole. as for example
------------------
Jupyter QtConsole 4.2.0
Python 2.7.11 (default, Dec 26 2015, 17:47:15) 
Type "copyright", "credits" or "license" for more information.

IPython 4.1.2 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from sympy import init_printing, init_session

In [3]: init_session()
IPython console for SymPy 1.0 (Python 2.7.11-64-bit) (ground types: python)

These commands were executed:
>>> from __future__ import division
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> init_printing()

Documentation can be found at http://docs.sympy.org/1.0/

In [4]: f = sin(x)/x

In [5]: f.series()
Out[5]: 

￼
 

In [5]: 

In [6]: integrate(f,x)
Out[6]: 

￼
 

In [7]: f.series()
   ...: 
   ...: 
Out[7]: 
-------------------
I was hitting tab once on the way.
