### ISSUE TITLE
%edit magic not executing contents in workspace?

### ISSUE THREAD

**Issue by reckoner** [jupyter/qtconsole#324]
I'm on Ubuntu 18.04. I set 'vim.gtk3 -g' as my editor in jupyter config. When I do `%edit` in the console, the editor opens and works fine, but the contents of the editor are not executed in the workspace. I have ensured to save the file, per the documentation on the `%edit` magic.

**Comment by ccordoba12** [comment]
`%edit` just edits the contents of a file. You need to rerun it again with `%run` to execute it again.

**Comment by reckoner** [comment]
According to the docs,

    Usage:
      %edit [options] [args]

    %edit runs an external text editor. You will need to set the command for
    this editor via the ``TerminalInteractiveShell.editor`` option in your
    configuration file before it will work.

    This command allows you to conveniently edit multi-line code right in
    your IPython session.

    If called without arguments, %edit opens up an empty editor with a
    temporary file and **will execute the contents of this file** when you
    close it (don't forget to save it!).


I cam calling it without a filename argument. Thanks!

**Comment by ccordoba12** [comment]
I think that's only true for the terminal version of IPython, not for qtconsole nor the notebook.
