### ISSUE TITLE
Pytest issues warning about deprecation in traitlets

### ISSUE THREAD

**Issue by ntoll** [jupyter/qtconsole#329]
Hi Folks,

When running the Mu test suite (Mu uses QtConsole), we see the following warnings from PyTest:

```
tests/interface/test_panes.py::test_JupyterREPLPane_set_zoom
  /home/ntoll/.virtualenvs/mu/lib/python3.7/site-packages/qtconsole/jupyter_widget.py:561: DeprecationWarning: JupyterREPLPane._style_sheet_changed is deprecated in traitlets 4.1: use @observe and @unobserve instead.
    def _style_sheet_changed(self):
```

Not quite sure what it means, but it looks like something is going to change in the not-too-distant future and break things.

Thank you for all your amazing work on this project... please don't get in touch if you need anything from me -- I'll help in any way I can.

**Comment by ccordoba12** [comment]
We're also seeing this warning in Spyder but I'm unsure how to solve it.

Pinging @minrk and @SylvainCorlay about this one. Could you give me some pointers about what to do here? Thanks!

**Comment by takluyver** [comment]
Yeah, that's not the most informative warning.

The old interface for watching for changes to a traitlet `style_sheet` was to define a method with the name `_style_sheet_changed` - it would be recognised based on the name and hooked up. That naming-based system is being replaced by a decorator `@observe('style_sheet')`. It looks like qtconsole hasn't been updated to the new API.

Traitlets docs: https://traitlets.readthedocs.io/en/stable/using_traitlets.html#observe

**Comment by ccordoba12** [comment]
Thanks Thomas for the pointers! I'll solve this in the next qtconsole version.

**Comment by ccordoba12** [comment]
@dalthviz, please work on this one to solve it as soon as possible, so we can release 4.5
