### ISSUE TITLE
QSocketNotifier warning in terminal

### ISSUE THREAD

**Issue by FHTMitchell** [jupyter/qtconsole#332]
When running `jupyer qtconsole` from the terminal ,  every time I type a command in the GUI I get a warning (in the original terminal):

    QSocketNotifier: Multiple socket notifiers for same socket 520 and type Read

This is especially annoying if I want to do other things in the the original terminal while also having a qtconsole instance running.

Jupyter QtConsole 4.4.3
Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]
IPython 7.2.0

**Comment by hmaarrfk** [comment]
Is this happening to you when you `%gui qt` and `%matplotlib qt` magics???
