### ISSUE TITLE
Config editing from the UI

### ISSUE THREAD

**Issue by OneAdder** [jupyter/qtconsole#335]
Hello, I have a feature request. It would be nice if it were possible to edit the configuration file (the one from `jupyter-qtconsole --generate-config`) from another window that opens if you click on something like `Customization` in the app menu.  
I mean at least the color schemes and font-size. Are you interested?  
If yes, I could probably write some code for it and make a pull request for you (not right now though, in a month or two).

**Comment by ccordoba12** [comment]
Sure, please go ahead :+1:

**Comment by OneAdder** [comment]
Cool, I'll do it when I'm free (June-July)
