### ISSUE TITLE
Update documentation builds

### ISSUE THREAD

**Issue by willingc** [jupyter/qtconsole#346]
Hi @ccordoba12,

I noticed that you had a new release :tada: I also realized that the webhook to RTD was not set up. I set that up and triggered a rebuild of latest, stable, and the past 3 versions' docs.

I also added you to RTD as a maintainer there for the qtconsole docs.

Give things a look and if all looks fine to you, then feel free to close this issue. :sunny:

**Comment by ccordoba12** [comment]
> I set that up and triggered a rebuild of latest, stable, and the past 3 versions' docs.

Ok, thanks a lot!

> I also added you to RTD as a maintainer there for the qtconsole docs.

Thanks for that too.

> Give things a look and if all looks fine to you, then feel free to close this issue

Yep, everything looks fine now :+1:
