### ISSUE TITLE
console does not scroll down when output is produced by a remote command

### ISSUE THREAD

**Issue by donchema** [jupyter/qtconsole#347]
![qtconsole_scrolling_issue](https://user-images.githubusercontent.com/49959603/60255454-184f9900-98d0-11e9-9f3f-b9e2eaf1da59.gif)

I've actually been looking for a possible solution as it seems an easy fix. However I'm a little lost as I'm not too familiar with the code. I can have a look if you can give me some starting point.

**Comment by ajtam** [comment]
Hi,

I have solved your problem.

**Comment by wmvanvliet** [comment]
Hi @ajtam, thanks for looking into this. The change looks reasonable to me.

Could you make this a pull request? (follow [your link](https://github.com/jupyter/qtconsole/compare/master...ajtam:master) and press the big green button).

**Comment by donchema** [comment]
Hi @ajtam 
Thank you for providing the solution!
