### ISSUE TITLE
ANSI escape sequences other than color

### ISSUE THREAD

**Issue by mdietrich16** [jupyter/qtconsole#350]
I am using the jupyter qtconsole through spyder, but I have tested the following in a standalone console aswell.

I know that certain ANSI escape sequences are being parsed, like simple colors and TrueColors, but is it possible to use stuff like _'\027[A'_ (cursor up) or implement it myself?

I'm not very profound in stuff like this, but if I could get a little nudge in the right direction I might be able to at least help myself if it is not overly complicated and hard to pull off.

Oh, and I saw that line 27 in ansi_code_processor.py actually says
`# FIXME: Not implemented in AnsiCodeProcessor.`

So do you just need people or good ideas, because I would happy to fix the first :)

**Comment by ccordoba12** [comment]
We need people, so you're more than welcome to help us to improve this.

**Comment by wmvanvliet** [comment]
PRs are always welcome!

**Comment by PropagandaP4nd4** [comment]
Well, seeing that I have never worked with the intrinsics of this project, I would need some pointer as to what and where to look to _try_ to improve this, as I said. But other than the first steps, happy to help!

**Comment by sylvain-bougnoux** [comment]
Yes, same for erase line, eg:
`print('Hello','\x1b[2K\rBye')`
Should print 'Bye' and not 'Byelo'.
It does work on a windows terminal (both with python & ipython).

**Comment by ma-sadeghi** [comment]
Can I ask what's the status of this issue? Is it hard to fix?

**Comment by ccordoba12** [comment]
It shouldn't be too hard to fix, we just haven't had time to sit down and do it.

**Comment by ma-sadeghi** [comment]
Could you please give me some pointers so I can take a crack at it? I don't know where to start.

**Comment by ccordoba12** [comment]
Our ANSI processor is implemented here:

https://github.com/jupyter/qtconsole/blob/master/qtconsole/ansi_code_processor.py
