### ISSUE TITLE
Prompt automatically scrolling down to the bottom of the window on execution

### ISSUE THREAD

**Issue by Gauler** [jupyter/qtconsole#351]
I would like the prompt to stay where it is while executing. Rapidly auto-scrolling to the bottom gets annoying/jarring quickly. Any way to do it?  (Ubuntu 19.10, QtConsole 4.5.1 running Python 3.7.3)

**Comment by ccordoba12** [comment]
If your code generates a lot of output, then it's not possible to maintain the current prompt on view. That's because qtconsole only displays 500 lines by default (this can be increased in our options) at any moment to avoid serious performance issues when code generates a lot of text.

**Comment by Gauler** [comment]
That's not the problem. Even if you execute a statement with no output like "import math" it goes to the bottom of the window and does not stay at the point where you scrolled up to. This does not happen in QtConsole on windows.

I even compared, jupyter_qtconsole_config.py file in ubuntu and windows -- no difference.

**Comment by ccordoba12** [comment]
If things on Windows work as expected, then this is not a problem in qtconsole but probably with the Qt version you're using.

**Comment by espdev** [comment]
@ccordoba12 
I'm using QtConsole on Windows and have the same problem with `QtConsole>= 4.4.4`, `PyQt5 >= 5.12.3` and above. Since `QtConsole 4.4.4` scrolling behavior was changed and this new behavior is inconvenient.

`QtConsole==4.4.3`:
![qt-console-4-4-3](https://user-images.githubusercontent.com/1299189/62426246-ee696d80-b6ea-11e9-890c-696c1b8d316d.gif)

`QtConsole==4.4.4`:
![qt-console-4-4-4](https://user-images.githubusercontent.com/1299189/62426249-f75a3f00-b6ea-11e9-9380-74695c30b44e.gif)

**Comment by ccordoba12** [comment]
@espdev, thanks for the screenshot! That's really a regression.

@dalthviz, please take a look at this one.

**Comment by dalthviz** [comment]
I think this is related with the fix proposed at #347 and added [here](https://github.com/jupyter/qtconsole/commit/49f1d666a03cf67dcf71c5e07ada80b76354fdb1), what should we do in this case @ccordoba12 ?

**Comment by ccordoba12** [comment]
But that was introduced in version 4.5.2 and @espdev says that this problem appeared in version 4.4.4.

Please use `git bisect` instead to detect the faulty change and try to fix it.

**Comment by espdev** [comment]
It seems I have found the PR and the commit which changes the scrolling behavior:

https://github.com/jupyter/qtconsole/pull/331
https://github.com/jupyter/qtconsole/pull/331/commits/51cc753f5b477d9be96333deb5e4790f8b9ddae2
