### ISSUE TITLE
Broken scrolling behaviour when debugging

### ISSUE THREAD

**Issue by wmvanvliet** [jupyter/qtconsole#353]
When entering the debugger (e.g. by doing `%debug` after an exception), the Qt window is constantly attempting to scroll to the position of the last input prompt *before* debugging mode was entered. Probably related to #349, in which we forgot that in debug mode, we don't update the prompt position.

(On current master only)

**Comment by ccordoba12** [comment]
@wmvanvliet, do you have time to take a look at this one?

**Comment by wmvanvliet** [comment]
Yes, I'll file a PR soonish.

**Comment by ccordoba12** [comment]
Thanks a lot!

**Comment by ccordoba12** [comment]
@wmvanvliet, any progress with this one? The thing is I'd like to release a new qtconsole version for Spyder as soon as possible.

**Comment by wmvanvliet** [comment]
I haven't ran into the issue anymore. Either I was wrong or it was some weird race condition. Anyway, closing this until I encounter it again.

Yay for new release!
