### ISSUE TITLE
Improve path completion options display

### ISSUE THREAD

**Issue by dalthviz** [jupyter/qtconsole#358]
@ccordoba12 the issue we discussed on the meeting

**Comment by ccordoba12** [comment]
Hey @dalthviz, you can see the problem I was referring to in the screenshot below

![Selección_011](https://user-images.githubusercontent.com/365293/62718235-bf623d00-ba05-11e9-9e6b-86cf531f6f7b.png)

We're showing the entire paths that can be completed, instead of only showing the endings of them.
