### ISSUE TITLE
Error when closing comms

### ISSUE THREAD

**Issue by ccordoba12** [jupyter/qtconsole#363]
I'm seeing the following error when closing comm's in the Spyder test suite in Travis:

```python
Exception ignored in: <function Comm.__del__ at 0x7fa708aac8c8>
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python3.7/site-packages/qtconsole/comms.py", line 198, in __del__
    self.close()
  File "/home/travis/miniconda/envs/test/lib/python3.7/site-packages/qtconsole/comms.py", line 231, in close
    self.sig_is_closing.emit(self)
AttributeError: 'Comm' does not have a signal with the signature sig_is_closing(PyQt_PyObject)
```

You can see this error reported at the end of [this log](https://travis-ci.org/spyder-ide/spyder/jobs/571676656).

@impact27, please take a look at this one. It seems you explicitly need to declare that `sig_is_closing` accepts a `QObject` instead of an `object`.

**Comment by impact27** [comment]
Well the problem is that I should not be sending messages while the comms is being destroyed. If __del__ is called, the comms is anyway not registered in the comms manager, so sending this is useless.
