### ISSUE TITLE
Disable undo and edit after input.

### ISSUE THREAD

**Issue by impact27** [jupyter/qtconsole#370]
1) Run this code:
![Screenshot 2019-08-28 at 16 17 21](https://user-images.githubusercontent.com/6740194/63869225-aec33800-c9af-11e9-9af2-5bd7eb6fc903.png)
 2) Enter any string:
![Screenshot 2019-08-28 at 16 18 14](https://user-images.githubusercontent.com/6740194/63869226-aec33800-c9af-11e9-9f76-aac32211f0fe.png)
3) Ctrl + Z
![Screenshot 2019-08-28 at 16 18 22](https://user-images.githubusercontent.com/6740194/63869227-aec33800-c9af-11e9-8526-ba1adf3ee2fa.png)
4) backspace multiple times
![Screenshot 2019-08-28 at 16 18 28](https://user-images.githubusercontent.com/6740194/63869228-af5bce80-c9af-11e9-81b1-aeb0daa8efb7.png)

**Comment by ccordoba12** [comment]
Good point. I agree with this.
