### ISSUE TITLE
Prompt is slow to come back under some conditions

### ISSUE THREAD

**Issue by impact27** [jupyter/qtconsole#379]
Sometimes, the prompt is slow to come back after processing something. I have this problem on the current master of qtconsole and ipykernel:

 - open qtconsole with `jupyter qtconsole`
 - Enter:
    - `%matplotlib qt5`
    - `import matplotlib.pyplot as plt`
    - `plt.plot([1, 2, 3])`
    - Then, minimize qtconsole and wait fot 1 minute
    - `1 + 1`

At that point, I get immediately `Out[5]: 2`, but I have to wait 10 seconds to get `In [6]: `.

My setup: Python 3.7.3 64-bit | Qt 5.12.3 | PyQt5 5.12.2 | Darwin 18.7.0 

![Screenshot 2019-09-19 at 18 34 40](https://user-images.githubusercontent.com/6740194/65267036-29452a80-db0c-11e9-87b4-fbff2a32d9c0.png)

**Comment by impact27** [comment]
It looks like `execute_reply` is delayed for some reason.

**Comment by wmvanvliet** [comment]
Could this be related to OSXs app-nap?

**Comment by impact27** [comment]
I tried the following:
1) launch `jupyter qtconsole`
2) `%matplotlib qt5`
3) type `1` + enter repetitively

After 30 seconds or so, the prompt starts to be slow to come back

**Comment by impact27** [comment]
- with `%matplotlib qt5`,  after 30 seconds, the `Out[]` comes immediatly, and I have to wait 10s for and for the `In[]`
 - with `%matplotlib osx`,  after 30 seconds,  I have to wait 10s for the `Out[]` and for the `In[]`
 - with `%matplotlib inline`, the error doesn't trigger
 - If I start with `%matplotlib inline` and then go to `%matplotlib qt5` after 30 seconds, , the error triggers after 30 additional seconds.
 - If I start with `%matplotlib qt5`, wait 30 seconds, then go to `%matplotlib inline`, I still get the error
 - If I start with `%matplotlib qt5`, then go to `%matplotlib inline` immediately, I don't get this error.
 - If I start with `%matplotlib qt5`, then go to `%matplotlib inline` immediately, then wait 30 seconds, then go back to `%matplotlib qt5`, I get this error immediately (after two prompts).

**Comment by impact27** [comment]
If I modify `ipykernel.kernelbase.Kernel.execute_request` by adding prints, I see the messages printing until `sys.stdout.flush()` (`ipykernel.iostream.OutStream.flush`)

**Comment by impact27** [comment]
Sorry the actual line that takes time is `time.sleep(self._execute_sleep)` in `ipykernel.kernelbase.Kernel.execute_request`:

While debugging:
```
(Pdb) start = time.time(); time.sleep(0.0005); print(time.time() - start)
10.000818967819214
```

**Comment by ccordoba12** [comment]
I think this is caused by an unhandled(?) interaction between the Qt event loop and the asyncio event loop that `ipykernel` uses by default since version 5. This is also the cause of spyder-ide/spyder#2902, which has been reported a lot of times.

@impact27, you could look try to use the [asyncqt](https://github.com/gmarull/asyncqt) package to see if the problem can be solved with its help.

Pinging @minrk and @takluyver about this one because they are the ones that know the most about event loops in the Jupyter community.

**Comment by impact27** [comment]
This is a duplicate of This is a duplicate of ipython/ipython#11602, so closing

**Comment by impact27** [comment]
The issue is purely matplotlib related, so I am opening an issue here:
https://github.com/matplotlib/matplotlib/issues/15314
