### ISSUE TITLE
%colors magic has no effect in qtconsole 4.0.0

### ISSUE THREAD

**Issue by lebedov** [jupyter/qtconsole#38]
I have qtconsole 4.0.0 installed via pip in a conda environment with Python 2.7.10 and PyQT 4.11.3. When I try to specify a color at the command line explicitly, e.g., `jupyter qtconsole --colors=linux`, the console starts but I observe the following warning:

```
[JupyterQtConsoleApp] WARNING | Unrecognized alias: '--colors=Linux', it will probably have no effect.
```

The specified colors do not take effect. Attempting to set the color via the `%colors` magic within the running console also has no effect.

Relevant installed packages:
```
$ yolk -l | egrep 'ipython|qtconsole|jupyter|ipykernel'
ipykernel       - 4.0.3        - active 
ipython-genutils - 0.1.0        - active 
ipython         - 4.0.0        - active 
jupyter-client  - 4.0.0        - active 
jupyter-console - 4.0.0        - active 
jupyter-core    - 4.0.2        - active 
jupyter         - 1.0.0        - active 
qtconsole       - 4.0.0        - active 
```

**Comment by lebedov** [comment]
As per [this remark](https://groups.google.com/forum/#!topic/jupyter/nHfgUmoZyBM), the `--colors option` is no longer supported (although the `--style` option is still available). The problem with the `%colors magic` still exists, though.

**Comment by takluyver** [comment]
I think it does actually do something - do `%colors nocolor`, for instance, and then look at some help information (e.g. `%colors?`).

It doesn't affect the Qt console prompts, because those are rendered by the frontend, and it doesn't affect subprocesses like `ls`, because they choose their own colours.

**Comment by lebedov** [comment]
I see - I was looking for the functionality now associated with the `--style` option.
