### ISSUE TITLE
%matplotlib qt5 causes time.sleep to hang for 10 seconds

### ISSUE THREAD

**Issue by impact27** [jupyter/qtconsole#380]
<img width="631" alt="Screenshot 2019-09-20 at 10 38 31" src="https://user-images.githubusercontent.com/6740194/65317014-e2e6de80-db92-11e9-8082-22cba1f463a6.png">

**Comment by impact27** [comment]
This is the root cause of https://github.com/jupyter/qtconsole/issues/379

**Comment by impact27** [comment]
Even smaller code:

`from ipykernel.eventloops import loop_map`
`from ipykernel.eventloops import loop_map`

**Comment by impact27** [comment]
Having an active figure turns this bug off

**Comment by impact27** [comment]
<img width="643" alt="Screenshot 2019-09-20 at 12 27 59" src="https://user-images.githubusercontent.com/6740194/65323738-1aa95280-dba2-11e9-8cda-069432a522e1.png">

**Comment by ccordoba12** [comment]
We could maintain a hidden figure in the namespace to avoid this. What do you think?

**Comment by impact27** [comment]
I am not sure if that would work, the figure needs to be in focus every 30 seconds. This looks like a big issue, and not even limited to qt5. Indeed `%matplotlib osx` triggers it as well. So it might not be triggered only by matplotlib. The problem is somewhere on the mac gui. 

I don't think python code can alter the waiting time of `time.sleep` that much. The doc says

> the suspension time may be longer than requested by an arbitrary amount because of the scheduling of other activity in the system.

My guess is that the workaround solution would be to generate gui events for whatever backend is used every 20 seconds.

**Comment by impact27** [comment]
Or to force the backend to be inline ...
Or to replace the event loop by periodic calls to flush_event()
Is this event loop used by anything else than matplotlib?

**Comment by impact27** [comment]
An issue is already open in https://github.com/ipython/ipython/issues/11602

**Comment by impact27** [comment]
Closing as I opened https://github.com/ipython/ipython/issues/11891

**Comment by impact27** [comment]
The simplest solution would be to disallow / print a warning if the user wants to use `qt`, `qt5`, or `osx` backends.
