### ISSUE TITLE
Importing qtconsole RichJupyterWidget in IPython breaks syntax highlighting

### ISSUE THREAD

**Issue by jni** [jupyter/qtconsole#388]
If I import RichJupyterWidget in an IPython terminal (ie the classic ipython in-process terminal), the syntax highlighting is broken in that terminal. The most visible sign is that the highlighter's determination of what is and isn't a string breaks, and it oscillates between thinking the text inside and outside of the string delimiters are strings. Depending on the length of the input string, the final highlighting will be correct or inverted.

To reproduce, launch IPython, then run:

```python
from qtconsole.rich_jupyter_widget import RichJupyterWidget
```

(You might need to launch IPython with `--gui=qt`.)

Then type:

```python
x = 'hello I am a long string'
```

and watch the highlighting flicker. The highlighting will be exactly inverted at the end.

![terminal-flicker](https://user-images.githubusercontent.com/492549/67453306-0d382a00-f672-11e9-8102-1f7afc9671cd.gif)

**Comment by ccordoba12** [comment]
I think both qtconsole and IPython use Pygments for syntax highlighting (qtconsole certainly does, not sure about IPython). So my guess is that that import has (through other imports) the side effect of messing with the Pygments instance in IPython.

@jni, this is very low priority for us, so if you want to see this fixed you should play with the imports in `rich_jupyter_widget` to see which one is creating the problem. When you discover the culprit, you should move it from the top to the point where it's really need it.

**Comment by jni** [comment]
> this is very low priority for us, so if you want to see this fixed

No worries, thank you for the heads-up and for pointing me in the right direction!

**Comment by Carreau** [comment]
It's triggered by import `qtconsole/pygments_highlighter.py`:

```
# Monkeypatch!
RegexLexer.get_tokens_unprocessed = get_tokens_unprocessed
```

**Comment by Carreau** [comment]
@goanpeca
