### ISSUE TITLE
Extremely slow startup

### ISSUE THREAD

**Issue by jorgenthode** [jupyter/qtconsole#389]
The launch time on qtconsole has been extremely slow (5-10 minutes) since I installed this package:

https://pypi.org/project/qats/

The package had dependency conflicts with spyder which I believe started the whole thing. Since everything worked properly before the installation, I removed the entire anaconda installation and installed it from scratch, but even with the fresh anaconda install, the startup time for Spyder and QTconsole remains painfully slow.  It is also extremely slow to restart the kernel, but when it is done loading, everything works as expected. When I run qtconsole in debugging mode, I get the following output. Every time the output says "connecting to tcp:" the app gets stuck for several minutes.

Please let me know how I can provide  more info if needed. 

Best regards, 
Joergen 

(base) C:\>jupyter qtconsole --debug
[JupyterQtConsoleApp] Searching ['C:\\', 'C:\\Users\\jortho\\.jupyter', 'C:\\Anaconda3\\etc\\jupyter', 'C:\\ProgramData\\jupyter'] for config files
[JupyterQtConsoleApp] Looking for jupyter_config in C:\ProgramData\jupyter
[JupyterQtConsoleApp] Looking for jupyter_config in C:\Anaconda3\etc\jupyter
[JupyterQtConsoleApp] Looking for jupyter_config in C:\Users\jortho\.jupyter
[JupyterQtConsoleApp] Looking for jupyter_config in C:\
[JupyterQtConsoleApp] Looking for jupyter_qtconsole_config in C:\ProgramData\jupyter
[JupyterQtConsoleApp] Looking for jupyter_qtconsole_config in C:\Anaconda3\etc\jupyter
[JupyterQtConsoleApp] Looking for jupyter_qtconsole_config in C:\Users\jortho\.jupyter
[JupyterQtConsoleApp] Looking for jupyter_qtconsole_config in C:\
[JupyterQtConsoleApp] Connection File not found: C:\Users\jortho\AppData\Roaming\jupyter\runtime\kernel-1776.json
[JupyterQtConsoleApp] Starting kernel: ['C:\\Anaconda3\\python.exe', '-m', 'ipykernel_launcher', '-f', 'C:\\Users\\jortho\\AppData\\Roaming\\jupyter\\runtime\\kernel-1776.json']
[JupyterQtConsoleApp] Connecting to: tcp://127.0.0.1:50182
[JupyterQtConsoleApp] connecting shell channel to tcp://127.0.0.1:50179
[JupyterQtConsoleApp] Connecting to: tcp://127.0.0.1:50179
[JupyterQtConsoleApp] connecting iopub channel to tcp://127.0.0.1:50180
[JupyterQtConsoleApp] Connecting to: tcp://127.0.0.1:50180
[JupyterQtConsoleApp] connecting stdin channel to tcp://127.0.0.1:50181
[JupyterQtConsoleApp] Connecting to: tcp://127.0.0.1:50181
[JupyterQtConsoleApp] connecting heartbeat channel to tcp://127.0.0.1:50183
[JupyterQtConsoleApp] WARNING | kernel died: 3.0002939701080322
[JupyterQtConsoleApp] WARNING | kernel died: 3.0147621631622314
[JupyterQtConsoleApp] Received history reply with 32 entries
[JupyterQtConsoleApp] Starting kernel: ['C:\\Anaconda3\\python.exe', '-m', 'ipykernel_launcher', '-f', 'C:\\Users\\jortho\\AppData\\Roaming\\jupyter\\runtime\\kernel-1776.json']
[JupyterQtConsoleApp] Connecting to: tcp://127.0.0.1:50182
[JupyterQtConsoleApp] shutdown: {'status': 'ok', 'restart': True}

**Comment by wmvanvliet** [comment]
It could be that the kernel is importing some python package, which for some reason takes ages. Do you have any packages autoloading in your config?

**Comment by jorgenthode** [comment]
Not that I have defined explicitly. I am now running a clean installation of the latest anaconda release. How can I check this autoloading configuration? As you can see from the log, there is no jupyter_qtconsole_config file at least.

**Comment by wmvanvliet** [comment]
I see. This is tricky. Do a plain `python` console and an `ipython` console show similar slowdowns?

**Comment by wmvanvliet** [comment]
Another thought: is your windows running a firewall of some sort that is blocking incoming connections, even from localhost? If the TCP connections are all timing out, that could explain the slowness.

**Comment by jorgenthode** [comment]
Thanks a lot,

To your first question - No, both python and iPython work like a charm. My (work) computer is set up with windows defender firewall, but unfortunately I do not have permissions to configure the firewall, so I'll ask IT for further help on the issue. Have you got any specific suggestions for where to start?

**Comment by ccordoba12** [comment]
> The launch time on qtconsole has been extremely slow (5-10 minutes) since I installed this package:
> 
> https://pypi.org/project/qats/

When you did this, you completely broke Spyder, Navigator and qtconsole. After uninstalling Anaconda, you also need to remove by hand the directory where you installed it because the installer can't remove files installed by pip.

And for next please be more careful. Installing `pyqt5` (which was the dependency brought by qats and giving you problems) in any conda env will break your entire Anaconda installation.
