### ISSUE TITLE
JupyterConsole.svg icon file missing in qtconsole 4.0.0?

### ISSUE THREAD

**Issue by lebedov** [jupyter/qtconsole#39]
When I run qtconsole 4.0.0 (installed via pip in a conda environment), the following message is printed:

```
Cannot open file '/home/lev/Work/miniconda/envs/DEFAULT/lib/python2.7/site-packages/qtconsole/resources/icon/JupyterConsole.svg', because: No such file or directory
```

**Comment by lebedov** [comment]
The icon doesn't appear to be in the whl or tar.gz files on pypi. Shouldn't the icon file be listed in MANIFEST.in?

**Comment by minrk** [comment]
It was added to package_data in #37. This is a duplicate of #36.
