### ISSUE TITLE
Embedded Qt console: matplotlib plots are not displayed inline

### ISSUE THREAD

**Issue by maddukurisrinivasarao** [jupyter/qtconsole#392]
Jupyter QtConsole 4.2.1 is embedded in QT 5.6.0 application.
Execute following script in command window:
```
get_ipython().run_line_magic('matplotlib', 'inline')
import matplotlib.pyplot as plt
x1=[1,2,3]
y1=[2,4,2]
plt.plot(x1,y1)
plt.show()
```

**Expected results:** a plot displayed in command window

**Observed results:** no plots displayed

![image](https://user-images.githubusercontent.com/16398677/68373174-56a37180-0168-11ea-8d46-1321549ae2a6.png)

_**Versions:**
Jupyter QtConsole 4.2.1
Python 3.5.4
IPython 6.2.1
matplotlib 3.0.3
Qt 5.6.0_

**Comment by cmaureir** [comment]
I think this issue can be close, since it seems to has been fixed:
![2020-10-17-142437_594x439_scrot](https://user-images.githubusercontent.com/177982/96337089-8c452000-1084-11eb-9fb1-5f1a4ee4fe9e.png)
