### ISSUE TITLE
Option to make %colors Linux default in config

### ISSUE THREAD

**Issue by ahnafalrafi** [jupyter/qtconsole#395]
Hi, is there any way to make the behaviour after issuing `%colors Linux` default in `~/.jupyter/jupyter_qtconsole_config.py`? This is particularly useful when using a dark sytax style, since this does not get changed automatically and can make viewing error messages difficult and some parts of these messages nearly unreadable. As an example with the monokai syntax style:
![jupyter_qtconsole_bad_colors](https://user-images.githubusercontent.com/20092027/69070882-97b04700-09ee-11ea-88bc-0543bb4cee0e.png)
As you can see, after issuing the command in `In [1]`, parts of the error message are quite hard to read. After issuing `%colors Linux` in `In [2]`, the error message from `In [3]` has significantly improved readability. It is not ideal to have to have to issue `%colors Linux` every time the qtconsole is started or every time the kernel is restarted (tested - behaviour reverts to default each time). Also whilst in the messages above, the text can be read with some difficulty, it is not entirely impossible. However, there are some other error messages in other instances with virtually ureadable text in the same background prior to issuing `%colors Linux`.

**Comment by wmvanvliet** [comment]
This is a configuration option for the ipython kernel, which you can set in  
`.ipython/profile_default/ipython_kernel_config.py`:

```python
## Set the color scheme (NoColor, Neutral, Linux, or LightBG).
c.InteractiveShell.colors = 'Linux'
```

**Comment by ahnafalrafi** [comment]
Thanks!
