### ISSUE TITLE
Spyder says qtconsole is 4.5.1 when I have 4.6.0 installed

### ISSUE THREAD

**Issue by Code-Babylon** [jupyter/qtconsole#398]
I'm trying to use Spyder 4, but it says I have a missing dependency, that being qtconsole isn't up to date, but when I look at my Anaconda environments, it says that I have qtconsole 4.6.0 installed.

**Comment by ccordoba12** [comment]
It's up to you to solve that problem. Most probably you installed in one env and are starting Spyder from another one.
