### ISSUE TITLE
jupyter paths not accurate

### ISSUE THREAD

**Issue by cbeebe44** [jupyter/qtconsole#402]
The paths used by jupyter qtconsole and other apps are not correct. I want to know how to change them.  
They are currently pointing to the paths of another environment. I am using conda to manage environments. This faulty configuration only happens when I clone an environment that used pip to install jupyter. I'm not sure if that is important, I just want to know how to change it. I brought up the same issue in multiple repositories ([1](https://github.com/jupyter/jupyter_core/issues/180), [2](https://github.com/conda/conda/issues/9616), [3](https://stackoverflow.com/questions/59819150/jupyter-and-conda-error-when-cloning-environment)).  
Thanks

**Comment by ccordoba12** [comment]
Instead of opening several repos with the same question, please wait until your question is answered in jupyter_core (qtconsole doesn't have anything to do with that).

**Comment by cbeebe44** [comment]
Thank you. I didn't know where this issue belongs, is jupyter_core the right place?
