### ISSUE TITLE
Please set X11 window class and instance

### ISSUE THREAD

**Issue by Nikratio** [jupyter/qtconsole#41]
Hello,

The `ipython3 qtconsole` window comes up with `WM_CLASS(STRING) = "", ""` (`xprop` output). This makes it very hard to identify a Qtconsole window programmatically (e.g. to have the window manager put it on a specific workspace, or assign it a specific size).

It would be great if these values could be changed to something more meaningful than the empty string.

**Comment by ccordoba12** [comment]
This was already fixed in qtconsole version 4.1.1

**Comment by ccordoba12** [comment]
Sorry, that was fixed on Windows.

**Comment by ccordoba12** [comment]
This issue was already solved in pull request #16.
