### ISSUE TITLE
Finish removing support for Python 2

### ISSUE THREAD

**Issue by dalthviz** [jupyter/qtconsole#425]
For QtConsole 5.0.0
Pinging @ccordoba12

**Comment by ccordoba12** [comment]
Thanks @dalthviz! Good luck with this one.

**Comment by ccordoba12** [comment]
The last bits before closing this one are:

* Remove `ipython_genutils` from our dependencies.
* Don't build universal wheels anymore.
* Take a close look at `setup.py` to see if nothing else is missing from the switch to Python 3.
* Fix things in the conda-forge recipe too.
