### ISSUE TITLE
launcher on windows

### ISSUE THREAD

**Issue by stonebig** [jupyter/qtconsole#43]
on windows, I get a "scripts\jupyter-qtconsole" instead of a hopefully "scripts\jupyter-qtconsole.exe"

(that I have for `jupyter-notebook.exe')

![jupyter_launchers](https://cloud.githubusercontent.com/assets/4312421/9290375/613924cc-4390-11e5-99bb-743fda2b3276.GIF)

using  qtconsole-4.0.0-py2.py3-none-any.whl
 

seems similar issue as there, but not in anaconda: https://groups.google.com/forum/#!topic/jupyter/ayLm0eivcBs

**Comment by minrk** [comment]
Fixed by #42

**Comment by stonebig** [comment]
thanks ! an update on pypi would be appreciated.

**Comment by stonebig** [comment]
by the way, I see other jupyter files with the same problem in my screenshot, so maybe the fix may apply to `jupyter_nbconvert` ?

**Comment by minrk** [comment]
@stonebig yup, slowly rolling it out. Only notebook itself has been pushed at this point.
