### ISSUE TITLE
How do I see all options of custom CSS?

### ISSUE THREAD

**Issue by Lutalli** [jupyter/qtconsole#431]
In `jupyter_qtconsole_config.py`, we can write
```python
c.JupyterQtConsoleApp.stylesheet = '/path/to/css'
```
so that QtConsole will load our own CSS as theme. But what are all the options (CSS selectors)? I know some like
```
QPlainTextEdit, QTextEdit, .error, .in-prompt, etc.
```
But that's far from enough.

Thank you!

**Comment by ccordoba12** [comment]
There's no page that describes at the moment, sorry. So I'm afraid you'll have to browse our source code and learn what they do by reading it.

**Comment by Lutalli** [comment]
Okay, thanks for your reply!
