### ISSUE TITLE
Plot window freezes when choosing qt5agg with matplotlib.use method under qtconsole 4.7.5

### ISSUE THREAD

**Issue by greg500** [jupyter/qtconsole#441]
## Problem Description

When choosing matplotlib backend with the 'use' function from matplotlib the pop up window freezes.
The problem won't show up when using %matplotlib magic command.

### What steps reproduce the problem?

`import matplotlib.pyplot as plt`
`from matplotlib import use`

`use('qt5agg')`
`plt.plot([1,2,3])`

![Capture2](https://user-images.githubusercontent.com/36016034/92380255-240c3180-f109-11ea-98ec-d2f7bd9afb1c.PNG)

## Versions
    
    qtconsole 4.7.5
    matplotlib 3.2.2
    Qt version: 5.9.7
    PyQt version: 5.9.2
    Ipython 7.16.1
    Python version: 3.8.3
    Operating System name/version: windows 10 x64

**Comment by wmvanvliet** [comment]
What happens when you first do `%matplotlib qt`?

**Comment by wmvanvliet** [comment]
The ipython kernel needs to run an internal QT event loop, which is what the `%matplotlib` command activates. You can make this setting permanent by editing the ipython kernel config file.

**Comment by greg500** [comment]
Thank you!
c.InteractiveShellApp.gui = 'qt5' fixed the issue.

**Comment by lshaheen** [comment]
I'm having the same issue. Where do I add `c.InteractiveShellApp.gui = 'qt5'` ?
