### ISSUE TITLE
Pyside2 QTabWidget addTab qtconsole error

### ISSUE THREAD

**Issue by niuzhenjiang** [jupyter/qtconsole#444]
Pyside2 QTabWidget addTab qtconsole error，show : 

TypeError: 'PySide2.QtWidgets.QTabWidget.addTab' called with wrong argument types:
  PySide2.QtWidgets.QTabWidget.addTab(ConsoleWidget, str)
Supported signatures:
  PySide2.QtWidgets.QTabWidget.addTab(PySide2.QtWidgets.QWidget, str)
  PySide2.QtWidgets.QTabWidget.addTab(PySide2.QtWidgets.QWidget, PySide2.QtGui.QIcon, str)

how can i embed my pyside2 application？？

**Comment by niuzhenjiang** [comment]
my ConsoleWidget inherit RichJupyterWidget，but pyside2 not Identify RichJupyterWidget is PySide2.QtWidgets.QWidget type

**Comment by cmaureir** [comment]
Cannot reproduce your issue using `PySide2==5.15.1`
```
import sys
from PySide2.QtWidgets import QApplication, QTabWidget, QWidget
from qtconsole.rich_jupyter_widget import RichJupyterWidget

class MyWidget(QWidget):
    def __init__(self):
        QWidget.__init__(self)

class OtherWidget(MyWidget):
    def __init__(self):
        MyWidget.__init__(self)

class AnotherWidget(RichJupyterWidget):
    def __init__(self):
        RichJupyterWidget.__init__(self)


app = QApplication()
tab = QTabWidget()
tab.addTab(QWidget(), "a")
tab.addTab(MyWidget(), "b")
tab.addTab(OtherWidget(), "c")
tab.addTab(RichJupyterWidget(), "d")
tab.addTab(AnotherWidget(), "e")
tab.show()

sys.exit(app.exec_())
```
![2020-10-17-140247_594x415_scrot](https://user-images.githubusercontent.com/177982/96336628-75e99500-1081-11eb-8d95-f82abd6269fd.png)

**Comment by eyllanesc** [comment]
@niuzhenjiang  qtconsole uses qtpy so if before importing qtconsole you haven't imported either PyQt5 or PySide2 it will try to import one of them, and in your case it has probably imported PyQt5 so you shouldn't combine both libraries. The solution is to first import PySide2 and then qtconsole.
