### ISSUE TITLE
tqdm progress bar problem

### ISSUE THREAD

**Issue by AJJLagerweij** [jupyter/qtconsole#461]
Hi I have a related issue, but the fix mentioned in [tqdm/tqdm#394](https://github.com/tqdm/tqdm/issues/394#issuecomment-384743637) does not solve the issue that I have.

Long story short, running the following code in Jupiyer Notebook or from the terminal works, but fails in the Jupyter QtConsole. The QtConsole reports ```HBox(children=(HTML(value=''), FloatProgress(value=0.0), HTML(value='')))``` instead of the progress bar.
```py
from tqdm.contrib.concurrent import process_map
import time


def _foo(my_number, constant):
    """Execute work in paralel."""
    square = my_number * constant
    time.sleep(1)
    return square, my_number


index = list(range(0, 100))
constant = [10] * len(index)
data = (index, constant)

res = process_map(_foo, index, constant)
```

Terminal: launching this script which was called `test.py`
![afbeelding](https://user-images.githubusercontent.com/31255888/102395739-989a1a80-3fec-11eb-93db-6cb4feb80c1d.png)

Jupyter Notebook:
![afbeelding](https://user-images.githubusercontent.com/31255888/102395962-dbf48900-3fec-11eb-9950-126c562bf878.png)

Jupyter QtConsole:
I noticed the issue first in Spyder, but I verified that it was caused by Jupyter QtConsole when I tried executing the script using `jupyter qtconsole` from the terminal.
![afbeelding](https://user-images.githubusercontent.com/31255888/102396198-28d85f80-3fed-11eb-97f0-e98ed5e9e839.png)

Is there a way to fix this, and is the actual issue caused by jupyter qtconsole?

**Comment by ccordoba12** [comment]
> The QtConsole reports HBox(children=(HTML(value=''), FloatProgress(value=0.0), HTML(value=''))) instead of the progress bar.

It seems `tqdm` is incorrectly detecting Qtconsole as a Jupyter notebook. That's a common mistake and not an easy one to solve.

I think (but I'm not really sure) that the problem needs to be solved on their side by also sending a progress bar representation that can be redender in QtConsole.

**Comment by AJJLagerweij** [comment]
If I understand you correctly, `tqdm` tries to serve us the fancy version of the bar, meant for Jupyter Notebook, whereas it should use the basic version which should look and work similar to the one in the terminal window?

**Comment by ccordoba12** [comment]
> If I understand you correctly, tqdm tries to serve us the fancy version of the bar, meant for Jupyter Notebook

Yes, you got exactly the point. My guess is that `tqdm` assumes it's running in a notebook because it runs a validation for to detect a Jupyter kernel. However, Qtconsole (and other Jupyter frontends) also rely on Jupyter kernels to work.

> whereas it should use the basic version which should look and work similar to the one in the terminal window?

By design, in the Jupyter architecture it's not possible to tell what frontend (Notebook or Qtconsole) sent something to run to a kernel. So it's not possible for `tqdm` to reliably send back to the frontend only the html or terminal representations. And it's also important to understand that multiple frontends can be connected to a single kernel at the same time.

To deal with that, libraries need to send all possible representations of their objects and leave the frontend the decision about how to render them. In our case, Qtconsole will drop the html representation (because it can't display it) and use instead the terminal one.

**Comment by AJJLagerweij** [comment]
Your feedback is on point, I now understand more and the [documentation](https://tqdm.github.io/docs/contrib.concurrent/#process_map) of `tqdm.contrib.concurrent.process_map` makes sense now. Especially the optional key called `tqdm_class`. So as you assumed the problem is how `tqdm` tries to detect what frontend is used with `tqdm.auto.tqdm` as to decide what `tqdm` class should be used. My solution is to force it the use of the basic tqdm class, as is shown in the following script.

```py
from tqdm import tqdm
from tqdm.contrib.concurrent import process_map
import time


def _foo(my_number, constant):
    """Execute work in paralel."""
    square = my_number * constant
    time.sleep(1)
    return square, my_number


index = list(range(0, 100))
constant = [10] * len(index)
data = (index, constant)

res = process_map(_foo, index, constant, tqdm_class=tqdm)
```
I'm happy to use this, although it is sad that it doesn't automatically adapt to the frontend that I use. (sometimes I do use Notebooks). I'll however still open an issue at `tqdm` to inform them about the problem with `tqdm.auto.tqdm` and refer them to this discussion.

**Comment by ccordoba12** [comment]
> Your feedback is on point

Great! Glad to know it was useful for you.

> I'll however still open an issue at tqdm to inform them about the problem with tqdm.auto.tqdm and refer them to this discussion.

Thanks! That's really helpful.

**Comment by AJJLagerweij** [comment]
This is the [issue at tqdm](https://github.com/tqdm/tqdm/issues/1098), if ever required for future reference or user reading this issue.

**Comment by casperdcl** [comment]
> By design, in the Jupyter architecture it's not possible to tell what frontend (Notebook or Qtconsole) sent something to run to a kernel. So it's not possible for tqdm to reliably send back to the frontend only the html or terminal representations. About this, it's also important to understand that multiple frontends can be connected to a single kernel at the same time.

Yup this annoyance. Will see about sending both representations...

**Comment by AJJLagerweij** [comment]
`tqdm` has implemented the proposed solution to send both the html and basic progress bar, see the `devel` branch. However they mention that it is impossible to force an update of the widget containing both the html and text representation. 

> > there is no way to force updating in a Jupyter console
> 
> Specifically, no way to force update a widget afaik. You can always use plain `tqdm.tqdm` though.
> 
> The issue is `tqdm.notebook` displays a widget which has an HTML and a text representation. It will update both representations but it's up to the frontend (i.e. browser/notebook or console) to actually update the display...

Is there a way to enable this, and should I open a new issue regarding it?

**Comment by ccordoba12** [comment]
> Is there a way to enable this, and should I open a new issue regarding it?

We have to delve into the things tqdm expects from the frontend to adjust things here. Unfortunately, we don't have time for that right now, sorry.

You're welcome to give it a try though.

**Comment by casperdcl** [comment]
essentially, this is what `tqdm.notebook` does:

```python
class TqdmHBox(ipywidgets.HBox):
    def __repr__(self, pretty=False):
        if not hasattr(self, "format_dict"):
            return super(TqdmHBox, self).__repr__()
        return tqdm.tqdm.format_meter(**self.format_dict)

container = TqdmHBox(children=[ipywidgets.HTML(), ipywidgets.FloatProgress(min=0, max=100)])
container.format_dict = {"n": 0}
display(container)

for i in range(100):
    container.format_dict["n"] = i
    container.children[1].value = i
```

When this runs in a browser, the browser itself (magically? maybe `.value` is a `@property` which handles this?) renders `HBox` updates.

It's possible this should be made an issue at the `ipywidgets` repo requesting console/text representation support.

**Comment by AJJLagerweij** [comment]
Thanks for the information. I'll have a look over at `ipywidgets` to see how they handle things from their end. But from what you tell me it seems that `ipywidgets` automatically updates when `container.children[1].value` is changed. It does indeed makes sense to me how that would not create any interaction in the console/text based printing.

I'll try to ask around at their git.
