### ISSUE TITLE
qconsole without jupiter?

### ISSUE THREAD

**Issue by mcondarelli** [jupyter/qtconsole#469]
Is there a way (possibly an easy way) to use just the terminal widget without any of the kernel-related features?

I am looking for a Qt Widget to display "rich text" (i.e.: at least "xterm-256color") in a window, with possibility to connect it to a serial line or a console application (possibly ncurses-aware).

I need something like QTermWidget (which does not support Pyside2, though).

Can qtconsole be used this way (and with lots less dependencies)?

**Comment by wmvanvliet** [comment]
Sadly, propably not. For starters, Qtconsole is not a proper teminal emulator, so it doesn't have all the functionality you require. What it can do is really tailored to Jupyter.

**Comment by mcondarelli** [comment]
Thanks. I feared that would have been the answer.
