### ISSUE TITLE
Jupyter QtConsole 4.0.1 copy on selection ignores the last char

### ISSUE THREAD

**Issue by zhangxaochen** [jupyter/qtconsole#47]
When I upgrade to the latest ipython-qtconsole v4.0, I find the window name is changed to *Jupyter QtConsole* now. My versions / settings are now as below:

```
Jupyter QtConsole 4.0.1
Python 2.7.7 |Anaconda 2.2.0 (32-bit)| (default, Jun 11 2014, 10:41:43) [MSC v.1500 32 bit (Intel)]
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python
```

The usage seems to be the same as before, while when I was trying to do copy / paste after selecting  some texts: the last character is missing after pasting!

I shutdown & reopened the kernel, using either the command:
`D:\Anaconda\pythonw.exe D:\Anaconda\pkgs\ipython-4.0.0-py27_0\Scripts\ipython-script.py qtconsole`
or
`jupyter qtconsole`
or
`jupyter-qtconsole.exe`

yet the issue still be there. So this seems to be a replicable bug to me -- not a fatal error, but annoying ;/

Has anyone come across the same issue as mine?

**Comment by bashtage** [comment]
I have the exact same issue on RHEL 6 using anaconda - last copy is always stripped unless I copy raw text, in which case it works correctly.

**Comment by cy18** [comment]
Exactly same problem in qtconsole, as well as in spyder.

**Comment by ccordoba12** [comment]
This is already fixed in master, and will be released in qtconsole 4.1.

@minrk, please close this one :-)

**Comment by minrk** [comment]
@ccordoba12 I added you to the repo, so you can close/merge now, too.

**Comment by ccordoba12** [comment]
Thanks a lot @minrk! I promise to hep where I can :-)
