### ISSUE TITLE
Stop disabling bold ANSI escape sequence

### ISSUE THREAD

**Issue by aroberge** [jupyter/qtconsole#472]
In file ansi_code_processor.py, one finds:
```python
class AnsiCodeProcessor(object):
    """ Translates special ASCII characters and ANSI escape codes into readable
        attributes. It also supports a few non-standard, xterm-specific codes.
    """

    # Whether to increase intensity or set boldness for SGR code 1.
    # (Different terminals handle this in different ways.)
    bold_text_enabled = False  #   <---- This
```
As far as I can tell, the line pointed at completely prevents bold from being ever set. Changing this to `True` makes it possible to set bold - at least in terminal that supports it. Would is be possible to change that settings?

**Comment by aroberge** [comment]
I just realized that this is related to issue #273 and might be considered a duplicate: changing the value of `bold_text_enabled` is likely all that is needed to do this.

**Comment by ccordoba12** [comment]
Closing then. If you want to submit a pull request for this, please do.
