### ISSUE TITLE
Cmd-Left and Cmd-Right not as expected on MacOS

### ISSUE THREAD

**Issue by battaglia01** [jupyter/qtconsole#483]
On MacOS, Cmd-Left and Cmd-Right are supposed to be basically the same as "Home" and "End."

However, in QtConsole, Cmd-Left has a strange behavior: it literally brings you to the beginning of the line - aka before the prompt. Then, since the cursor is positioned at an "invalid" location, once you type anything it brings you right back to the end of the line.

Adding 8 lines of code to `_event_filter_console_keypress(self, event)` in `console-widget.py` yields the correct behavior:

```
...
    def _event_filter_console_keypress(self, event):
        """ Filter key events for the underlying text widget to create a
            console-like interface.
        """
        intercepted = False
        cursor = self._control.textCursor()
        position = cursor.position()
        key = event.key()
        ctrl_down = self._control_key_down(event.modifiers())
        alt_down = event.modifiers() & QtCore.Qt.AltModifier
        shift_down = event.modifiers() & QtCore.Qt.ShiftModifier

#### BEGIN INSERT
        cmd_down = \
            sys.platform == "darwin" and \
            self._control_key_down(event.modifiers(), include_command=True)
        if cmd_down:
            if key == QtCore.Qt.Key_Left:
                key = QtCore.Qt.Key_Home
            elif key == QtCore.Qt.Key_Right:
                key = QtCore.Qt.Key_End
#### END INSERT
        #------ Special modifier logic -----------------------------------------
...
```

You could also probably make a `_cmd_down_remap` similar to the `_ctrl_down_remap` that you already have, but this seemed simpler.

**Comment by ccordoba12** [comment]
@battaglia01, thanks for wanting to help us with this.

@impact27, what do you think about this one?

**Comment by battaglia01** [comment]
Also a quick note that Cmd-Up and Cmd-Down are supposed to be basically equivalent to Ctrl-Home and Ctrl-End on Windows, so I've slightly modified the above to have

```
        cmd_down = \
            sys.platform == "darwin" and \
            self._control_key_down(event.modifiers(), include_command=True)
        if cmd_down:
            if key == QtCore.Qt.Key_Left:
                key = QtCore.Qt.Key_Home
            elif key == QtCore.Qt.Key_Right:
                key = QtCore.Qt.Key_End
            elif key == QtCore.Qt.Key_Up:
                ctrl_down = True
                key = QtCore.Qt.Key_Home
            elif key == QtCore.Qt.Key_Down:
                ctrl_down = True
                key = QtCore.Qt.Key_End
```

This with #483 seems to work pretty well; everything seems pretty good on Mac.

**Comment by impact27** [comment]
Similar problem I have with qtconsole: The prompt is `"in[0]: "` with a space at the end. When I click on the beginning of the line befaore the space: 
`In[1]:| abcd`
the cursor jumps to the end: (Here typing `0`)
`In[1]: abcd0`
when I would want:
`In[1]: 0abcd`
So I propose that:
 - If the cursor is above the current line, keep the current behavior
 - If the cursor is before the input buffer but on the same line, move the cursor to the beginning of the buffer instead.

**Comment by impact27** [comment]
For cmd + up / down, have you seen: https://github.com/jupyter/qtconsole/pull/475

**Comment by battaglia01** [comment]
@impact27 very interesting. It looks like on Mac, just remapping Cmd-up to Ctrl-home and Cmd-down to Ctrl-end already does the correct behavior. I'm not sure if it makes any difference if I map Cmd-up to Ctrl-up and go with your method instead.

One thing that is really annoying is that ctrl-c doesn't ditch the current line mid-type and make a new one, at least on Mac, so I'm thinking I should add that as well.

**Comment by ccordoba12** [comment]
> How does this usually work on Windows, where Ctrl-C equals copy?

Yeah, that's what it does.

**Comment by battaglia01** [comment]
Makes sense. OK, so forgetting that - it seems like the way I'm doing the
cmd remapping is alright, so I'll put these things together in a new PR.

@impact27, your thought about checking the line number is good; I don't
know the easiest way to do that though. Maybe best in a separate issue...

Mike

**Comment by battaglia01** [comment]
OK, PR submitted in #488.
