### ISSUE TITLE
Pressing Shift causes window to scroll back to current prompt if scrolled up

### ISSUE THREAD

**Issue by battaglia01** [jupyter/qtconsole#484]
If you are trying to scroll up to copy/paste some text from further up, you might do this:

1. Scroll up to where you want the selection to begin
2. Click to put the cursor at the selection begin point
3. Hold the "shift" button
4. Scroll to where you want the selection to end
5. Click to put the cursor at the selection end point

The problem is that when you type "shift", qtconsole causes the text cursor to jump back to the prompt, so you can't copy or paste anything. This happens with quite a few keys - shift, option, etc - but not ctrl.

It's because of this in `console_widget.py`, at the very end of `_event_filter_console_keypress(self, event)`

```
        if not (self._control_key_down(event.modifiers(), include_command=True)
                or key in (QtCore.Qt.Key_PageUp, QtCore.Qt.Key_PageDown)
                or (self._executing and not self._reading)):
            self._keep_cursor_in_buffer()
```

That call to `self._keep_cursor_in_buffer()` is what causes it to reset the position.

There are quite a few modifiers that cause this - not just shift but literally any key except for the three exceptions above - page up, page down, and control. It seems to me that the cleanest way to do this is to simply add the following line

```
        if not (self._control_key_down(event.modifiers(), include_command=True)
                or key in (QtCore.Qt.Key_PageUp, QtCore.Qt.Key_PageDown)
                or (self._executing and not self._reading)
                or (event.text() == "" and not key in (QtCore.Qt.Key_Up, QtCore.Qt.Key_Down))): ## <-- ADDED!
            self._keep_cursor_in_buffer()

```

This only scrolls back to the bottom only if the user actually typed something which has text in it, like a character, rather than just typing some modifier or special key (e.g. shift, page up/page down, maybe print screen), with the one exception of if they've typed the up or down keys (which should scroll through the history). Then everything seems to work the way you'd expect.

**Comment by ccordoba12** [comment]
> This only scrolls back to the bottom only if the user actually typed something a character which has text in it, rather than just typing some modifier or special key (e.g. shift, page up/page down, maybe print screen), with the one exception of if they've typed the up or down keys (which should scroll through the history)

Seems quite reasonable to me. Please open a pull request with your proposed change so we can include it in our next release.

**Comment by battaglia01** [comment]
Thanks.

Also modified the above slightly to also check for shift_down

```
        if not (self._control_key_down(event.modifiers(), include_command=True)
                or key in (QtCore.Qt.Key_PageUp, QtCore.Qt.Key_PageDown)
                or (self._executing and not self._reading)
                or (event.text() == "" and not
                    (not shift_down and key in (QtCore.Qt.Key_Up, QtCore.Qt.Key_Down)))):
            self._keep_cursor_in_buffer()
```

This way the cursor only jumps for up/down and not for Shift-up/down (so that they can select).

This revealed another small quirk which is that, strangely, shift-up currently isn't being handled properly - only shift-down, kind of - so another tiny change in `_event_filter_console_keypress(self, event)` for that

``` 
           elif key == QtCore.Qt.Key_Up and not shift_down: # added "and not shift_down"
                if self._reading or not self._up_pressed(shift_down):
                    intercepted = True
                else:
                    prompt_line = self._get_prompt_cursor().blockNumber()
                    intercepted = cursor.blockNumber() <= prompt_line

            elif key == QtCore.Qt.Key_Down and not shift_down: # added "and not shift_down"
                if self._reading or not self._down_pressed(shift_down):
                    intercepted = True
                else:
                    end_line = self._get_end_cursor().blockNumber()
                    intercepted = cursor.blockNumber() == end_line
```

and now things are good. Once I get clarification on #483 I'll submit a small PR with all these little keyboard changes...

**Comment by battaglia01** [comment]
OK, PR submitted in #488.

**Comment by ccordoba12** [comment]
> This revealed another small quirk which is that, strangely, only shift-down is currently being handled properly, not shift-up or shift-left or shift-right

Why is this necessary? Sorry, I don't understand it.

**Comment by battaglia01** [comment]
Because it was treating shift up like just "up," rather than selecting text.

**Comment by ccordoba12** [comment]
Ok, I understand now. Thanks for the clarification.
