### ISSUE TITLE
The standard streams' method `isatty()` should return `True`.

### ISSUE THREAD

**Issue by real-yfprojects** [jupyter/qtconsole#486]
Current behaviour:
```python3
>>> import sys
>>> sys.stdout.isatty()
False
```
In my opinion this should return `True`.

A stream's method `isatty` should 
> Return whether this is an 'interactive' stream.

I think that means whether it is an interactive console.

This is especially important when working with `colorama`. This python module for terminal colouring checks this method's return value to decide whether to strip *ANSI codes* or not.
In the current state the *qtconsole* lacks colorama support.

It seems like the standard output and error streams are of type `ipykernel.iostream.OutStream` in the qtconsole. The issue might actually lie there.
I think this class directly inherits `isatty()` from `io.TextIoBase` which isn't an  'interactive' stream by default.

**Comment by wmvanvliet** [comment]
QtConsole is not a full terminal (TTY emulator), and doesn't support all ANSI codes. Then again, it certainly is an interactive stream.

**Comment by ccordoba12** [comment]
@real-yfprojects, thanks for reporting. Please open this issue in the ipykernel repo because we can't solve it here and a change as the one you're suggesting will also affect the Jupyter notebook and JupyterLab.

https://github.com/ipython/ipykernel/

**Comment by real-yfprojects** [comment]
> we can't solve it here

@ccordoba12
 Why can't you subclass `ipykernel.iostream.OutStream` and override the `isatty` method?

**Comment by ccordoba12** [comment]
Qtconsole is only a frontend for the kernel, so it doesn't directly handle anything related to it.

But if you think you can easily subclass `OutStream` here and override `isatty()`, please submit a PR for it.

**Comment by peendebak** [comment]
@ccordoba12 @wmvanvliet The `isatty` method is a bit all or nothing, which is not perfect for situations like this (e.g. qtconsole not being a full tty, but supporting much of the "common" functionality).

For `ipykernel` there is now an option to set the value of `isatty` https://github.com/ipython/ipykernel/pull/683. How can we use that to provide color support in spyder? I looked in this repo where the ` ipykernel.iostream.OutStream`  is created, but could not find it.
And since this package is used by other packages besides spyder, should we make it optional here and set the option from spyder?

**Comment by ccordoba12** [comment]
@peendebak, you need to pass a different `OutStream` class to the kernel app, as shown here:

https://github.com/ipython/ipykernel/blob/079f072a8e90422dc74270992589c56ad9f7f9f2/ipykernel/kernelapp.py#L161-L162

That means that for this to work it's required to subclass IPKernelApp and the kernel itself.

Fortunately, that's what we do in Spyder already with our [`spyder-kernels`](https://github.com/spyder-ide/spyder-kernels) package. Please open an issue there so I can give you detailed instructions on how you can achieve this.

**Comment by eendebakpt** [comment]
@ccordoba12 I created https://github.com/spyder-ide/spyder-kernels/issues/302. Could you give instructions there?
