### ISSUE TITLE
Should the Qt console be treated as a tty?

### ISSUE THREAD

**Issue by swt30** [jupyter/qtconsole#50]
Came here from https://github.com/astropy/astropy/issues/2297, where a updateable progress bar isn't printing inside the Qt console. It looks like this is because, in the console, `sys.stdout.isatty()` is False. Should this be the case? I don't know enough about what a tty actually is to judge whether this is something that needs to be fixed, or whether we shouldn't be using `isatty` to judge whether we can treat the console like one.

**Comment by ccordoba12** [comment]
Qtconsole is written entirely in Qt. It emulates the look and feel of a real console (i.e. a tty one) but it doesn't have to do anything with it.

**Comment by swt30** [comment]
OK thanks - sounds like something that needs to be worked round on the other end then.
