### ISSUE TITLE
qtconsole with PyQt6

### ISSUE THREAD

**Issue by tomgoddard** [jupyter/qtconsole#504]
It would be great to have qtconsole working with PyQt6.  qtconsole uses qtpy as a shim to allow use of PyQt5 or PySIde2.  qtpy is currently being updated (qtpy 2.0 code at github, not yet on PyPi) to support PyQt6.  Using the github qtpy I tried making changes to qtconsole to get it working in a molecular visualization application I develop called ChimeraX.  It mostly required adding namespaces to enumeration values, for instance, Qt.AlignRight becomes Qt.AlignmentFlag.AlignRight.

I've attached a patch of the few hundred changes I made to qtconsole to get it working with PyQt6.  Very likely there is more work to do.  I just fixed up what was needed in my use case.  This patch is against PyPi qtconsole version 5.1.1.

[qtconsole_pyqt6.patch.txt](https://github.com/jupyter/qtconsole/files/7438608/qtconsole_pyqt6.patch.txt)
.

**Comment by tomgoddard** [comment]
The qtpy developers say in this comment that  they will try to allow unscoped enumeration value names for PyQt6 

https://github.com/spyder-ide/qtpy/issues/233#issuecomment-954941133

**Comment by ccordoba12** [comment]
Yeah, as I said, we were not sure about that, but now we decided to support unscoped enums in qtpy.

**Comment by tomgoddard** [comment]
With qtpy 2.0 which supports PyQt 6, several changes to qtconsole are still needed to work with PyQt 6.  I've attached a patch with the changes I needed for my use of qtconsole.  

Here is a summary of the needed changes.

1) use Qt.MiddleButton instead of Qt.MidButton
2) use event.globalPosition().toPoint() instead of event.globalPos()
3) use QTextEdit setTabStopDistance() instead of setTabStopWidth()
4) use QWidget mapToGlobal() instead of desktop().screenGeometry(w)

My patch against qtconsole 5.2.2 is only to make it work in Qt 6.  To make it work in both Qt 5 and Qt 6 will take more work that I do not have time to pursue.

[qtconsole.zip](https://github.com/jupyter/qtconsole/files/7800262/qtconsole.zip)

**Comment by tomgoddard** [comment]
I improved my qtconsole patch so it works with PyQt5 and PyQt6 since I am working on migrating my app ChimeraX and need it to work on both.  Here is the improved patch against qtconsole 5.2.2.

[qtconsole.zip](https://github.com/jupyter/qtconsole/files/7810256/qtconsole.zip)

**Comment by ccordoba12** [comment]
@tomgoddard, please create a pull request from your patch so we can review your work and eventually merge it.

**Comment by tomgoddard** [comment]
I do not expect to have time to create the pull request.  Hopefully the patch which took a few hours of debugging and testing will help the next developer.

**Comment by ccordoba12** [comment]
This is very low priority for us, so if you want to see qtconsole working with PyQt6 soon, please give us a hand with this.
