### ISSUE TITLE
HTML with inline png images does not appear to be generated correctly

### ISSUE THREAD

**Issue by twmacro** [jupyter/qtconsole#51]
To reproduce:
1.  From within Spyder, Tools->Preferences->IPython console->Graphics, set the Graphics backend to “Inline”.
2.  Close Spyder and restart.
3.  Run this to display an inline plot (for example):
   
   ```
                  import matplotlib.pyplot as plt
                  plt.plot([1, 3, 1, 6, 10, 4])
   ```
4.  Hit control-s, choose a file name and save as “HTML with PNG figures”, click “save”.
5.  Select “Inline” when it asks “Would you like inline PNGs …” 
6.  Neither FireFox nor IE will display the figure.

The HTML ends up with code like this:

```
     <img src="data:image/png;base64,b'iVBORw0KGgoAAAAN...'
```

To get the figure to display, I manually deleted the leading b' and the trailing '.

I finally tracked the source of this down to the file ‘rich_jupyter_widget.py’, in the routine ‘RichJupyterWidget._get_image_tag()’.  The offending code is:

```
    re.sub(r'(.{60})',r'\1\n',str(ba.toBase64()))
```

Modifying this to:

```
    re.sub(r'(.{60})',r'\1\n',str(ba.toBase64())[2:-1])
```

works, but I don’t know the what the best fix is or if this causes other issues somewhere else.

**Comment by twmacro** [comment]
This is a Python 2 to Python 3 thing. The code must have been developed for Python 2. A better fix that works for both versions is to change the offending line to:

     format,re.sub(r'(.{60})',r'\1\n',
                   str(ba.toBase64().data().decode())))

**Comment by wmvanvliet** [comment]
yup, that seems to work ok.
