### ISSUE TITLE
qtconsole execution inside jupyter terminal

### ISSUE THREAD

**Issue by Muhammad-Bo** [jupyter/qtconsole#523]
Hello,

I am using Jupyter Notebook for educational purposes. My main requirement is that I have a running jupyter notebook (connected to a python kernel). I need one more connection to the same kernel for printing some stored variable. Here, the qtconsole is the solution. However, my students get connected to my jupyter server remotely, and there is no way to to open qtconsole gui app on clients(student) side.

Is there anyway to run qtconsole inside the provided teminal in the jupyter (hence everything will be on the web). I only need some string printing via qtconsole connection to existing kernel. 

BR,
Mohammad

**Comment by ccordoba12** [comment]
Hey @Muhammad-Bo, unfortunately, starting Qtconsole from a notebook only works when running it locally.

> Is there anyway to run qtconsole inside the provided teminal in the jupyter (hence everything will be on the web)

This functionality is already available in JupyterLab. If you don't like it, you should know that the old Jupyter notebook is transitioning to use JupyterLab components right now, so you could ask for such a feature here:

https://github.com/jupyterlab/retrolab
