### ISSUE TITLE
Menubar does not appear on MacOS X 10.9 or 10.10

### ISSUE THREAD

**Issue by astrofrog** [jupyter/qtconsole#53]
I've had a similar issue with other Qt4 projects. On MacOS X 10.9 and 10.10, the menubar does not appear at first even though the console is in the foreground:

<img width="719" alt="screen shot 2015-09-14 at 9 29 06 pm" src="https://cloud.githubusercontent.com/assets/314716/9859589/aef7b1a2-5b27-11e5-89a9-927c8b2b82cc.png">

If I click on another application then go back to the Qt console, it then appears:

<img width="715" alt="screen shot 2015-09-14 at 9 29 16 pm" src="https://cloud.githubusercontent.com/assets/314716/9859597/bc507cee-5b27-11e5-914b-cdc222f1732d.png">

This works fine on MacOS X 10.8 though. Any ideas on what could be causing this?

**Comment by ccordoba12** [comment]
What's your Qt version?

**Comment by astrofrog** [comment]
I'm using the latest versions of Qt4 in conda:

Qt: 4.8.6
PyQt: 4.11.3

**Comment by astrofrog** [comment]
I've been digging around a little on my side and have posted a message on the PyQt mailing list about this:

https://www.riverbankcomputing.com/pipermail/pyqt/2015-September/036405.html

Someone initially suggested it was a Qt issue, not PyQt, but I could not replicate the issue using Qt directly:

https://www.riverbankcomputing.com/pipermail/pyqt/2015-September/036412.html

**Comment by rkern** [comment]
I've had similar issues with other applications using PySide and Qt 4.8.6 in both OS X 10.8 and 10.10. Usually `Cmd-Tab` over to some other application then `Cmd-Tab` back works around it.

It might have something to do with not being in a proper `.app`.

**Comment by astrofrog** [comment]
@rkern - yes, the workaround is just to switch to another application and back. Also, I just checked and indeed it happens with PySide too. I've never seen the issue on OSX 10.8 though.

This is frustrating because most users might not guess that workaround, and it will basically affect all Qt applications on MacOS X not distributed as apps but e.g. through conda. Anyway, feel free to close this if you think there is no workaround for qtconsole and this is not something that can easily be fixed upstream, and sorry for the noise.

**Comment by astrofrog** [comment]
Ah it turns out that this issue does *not* happen when using Python from MacPorts, only conda (for me). @rkern - are you also using conda?

**Comment by rkern** [comment]
No, Canopy.

**Comment by ccordoba12** [comment]
@astrofrog, maybe it has something to do with the fact that Anaconda's Qt is not a framework build.

**Comment by astrofrog** [comment]
@ccordoba12 - ah, very good point, and that could maybe explain Canopy too (I think?)

**Comment by rkern** [comment]
Canopy's Qt libraries are `.frameworks`.

**Comment by astrofrog** [comment]
Right, I don't think it's a framework thing after doing more digging. I compiled qt4 from scratch in non-framework mode and did a C++ test (https://github.com/astrofrog/qt-build-sandbox) and it all worked fine.

This is all puzzling especially because it works with the MacPorts installation.

**Comment by ccordoba12** [comment]
You could check if MacPorts is patching PyQt4 somehow to fix this behavior.

**Comment by astrofrog** [comment]
During my testing, it turns out that installing a package in conda caused an old version of the qt console to be installed, which is what confused me. The latest version runs just fine. Sorry for the noise!

Since I was having this issue with other packages, in case anyone googles this issue and ends up here:

- If you are running a Python script yourself, be sure to run it with ``pythonw`` instead of ``python`` when using PyQt4 (or any GUI)

- If you are developing a conda package, you need to be sure you include these lines in your package description:

```
build:
  osx_is_app: True
```

See http://conda.pydata.org/docs/building/meta-yaml.html#python-app
