### ISSUE TITLE
Disconnect the Widget from the IPython kernel

### ISSUE THREAD

**Issue by Jojain** [jupyter/qtconsole#541]
Hello, 

So I am building an Qt app where I use an In process QtConsole. I like the way the console works but all the machinery around the IPython kernel adds complexity to my code and is of no use for me. 

So my question is: Is it possible to use the RichJupyterWidget without a kernel and with it directly connected to the Interpreter running the app ?

I know that it is probably not possible out of the box but the question is more, is it feasible to adapt the code or is it so much tied together that it would be better to rebuild something from the ground up ?

I tried to get my answer by reading the implementation but it is quite complex and I feel I would be better asking people who knows rather than wasting my time trying to find the answer alone.

Thank you !

PS : And if it is possible, I would appreciate guidelines for the way to achieve it

**Comment by ccordoba12** [comment]
> So my question is: Is it possible to use the RichJupyterWidget without a kernel and with it directly connected to the Interpreter running the app ?

QtConsole is designed to work with a kernel and the in-process kernel is the way to connect it to the interpreter running the app that embeds the console. So, I'm afraid I don't understand what you're asking for.

> I know that it is probably not possible out of the box but the question is more, is it feasible to adapt the code or is it so much tied together that it would be better to rebuild something from the ground up ?

I don't think that's possible, sorry. The in-process kernel is sort of a hack because QtConsole's most important use case is to connect to an external kernel. So anything that goes in the direction of changing that won't be accepted by us, sorry.

**Comment by Jojain** [comment]
Thanks for you response.
I think I have not made myself clear. I'm not expecting you to adapt the code for doing what I want, I want your advice as developer of qtconsole to tell me if I could do that readapting the code myself or if it's a waste of time !

**Comment by ccordoba12** [comment]
Then I'd say it'd be very hard to do what you want because the console basically expects a kernel to connect to.

**Comment by Jojain** [comment]
Alright thank you for the insight :)

**Comment by ccordoba12** [comment]
Ok, closing this one then.
