### ISSUE TITLE
 Syntax highlighting broken with multiline inputs

### ISSUE THREAD

**Issue by impact27** [jupyter/qtconsole#546]
To reproduce:
`jupyter qtconsole`
Then paste a multiline statment, e.g.:
```
"""
s
"""
a = 1
```
This results in:
![Screenshot 2022-06-14 at 15 42 42](https://user-images.githubusercontent.com/6740194/173592367-bcdab364-e314-4a33-8eb7-d0ee88503379.png)
Only the first line is highlighted

**Comment by ccordoba12** [comment]
This probably happens because we're using Pygments to highlight single lines. And I think that's the only way to use Pygments interactively (i.e. not for entire documents).
