### ISSUE TITLE
%%HTML magic not working.

### ISSUE THREAD

**Issue by account-login** [jupyter/qtconsole#55]
Below is the symptom.
```
In [1]: %%html
   ...: sdf<b>fads</b>
<IPython.core.display.HTML object>

In [2]:
```

This bug exists in IPython qtconsole too.
The `_handle_execute_result` & `_handle_display_data` in `rich_jupyter_widget.py` are missing code that handle html data. After adding 4 lines of code, the %%HTML magic works again.
<pre>
    def _handle_execute_result(self, msg):
        """Overridden to handle rich data types, like SVG."""
        self.log.debug("execute_result: %s", msg.get('content', ''))
        if self.include_output(msg):
            self.flush_clearoutput()
            content = msg['content']
            prompt_number = content.get('execution_count', 0)
            data = content['data']
            metadata = msg['content']['metadata']
            if 'image/svg+xml' in data:
                self._pre_image_append(msg, prompt_number)
                self._append_svg(data['image/svg+xml'], True)
                self._append_html(self.output_sep2, True)
            elif 'image/png' in data:
                self._pre_image_append(msg, prompt_number)
                png = decodestring(data['image/png'].encode('ascii'))
                self._append_png(png, True, metadata=metadata.get('image/png', None))
                self._append_html(self.output_sep2, True)
            elif 'image/jpeg' in data and self._jpg_supported:
                self._pre_image_append(msg, prompt_number)
                jpg = decodestring(data['image/jpeg'].encode('ascii'))
                self._append_jpg(jpg, True, metadata=metadata.get('image/jpeg', None))
                self._append_html(self.output_sep2, True)
            elif 'text/latex' in data:
                self._pre_image_append(msg, prompt_number)
                self._append_latex(data['text/latex'], True)
                self._append_html(self.output_sep2, True)
            <b>elif 'text/html' in data:
                self._append_html(data['text/html'], True)</b>
            else:
                # Default back to the plain text representation.
                return super(RichJupyterWidget, self)._handle_execute_result(msg)

    def _handle_display_data(self, msg):
        """Overridden to handle rich data types, like SVG."""
        self.log.debug("display_data: %s", msg.get('content', ''))
        if self.include_output(msg):
            self.flush_clearoutput()
            data = msg['content']['data']
            metadata = msg['content']['metadata']
            # Try to use the svg or html representations.
            # FIXME: Is this the right ordering of things to try?
            self.log.debug("display: %s", msg.get('content', ''))
            if 'image/svg+xml' in data:
                svg = data['image/svg+xml']
                self._append_svg(svg, True)
            elif 'image/png' in data:
                # PNG data is base64 encoded as it passes over the network
                # in a JSON structure so we decode it.
                png = decodestring(data['image/png'].encode('ascii'))
                self._append_png(png, True, metadata=metadata.get('image/png', None))
            elif 'image/jpeg' in data and self._jpg_supported:
                jpg = decodestring(data['image/jpeg'].encode('ascii'))
                self._append_jpg(jpg, True, metadata=metadata.get('image/jpeg', None))
            elif 'text/latex' in data and latex_to_png:
                self._append_latex(data['text/latex'], True)
            <b>elif 'text/html' in data:
                self._append_html(data['text/html'], True)</b>
            else:
                # Default back to the plain text representation.
                return super(RichJupyterWidget, self)._handle_display_data(msg)
</pre>

Sorry for my poor english.

**Comment by minrk** [comment]
The QtConsole supports such a limited subset of HTML, that it really shouldn't pretend to support HTML at all. So we have removed text/html from the list of supported output types, since most real examples we found targeted the notebook, and didn't actually work in the QtConsole.
