### ISSUE TITLE
init_printing() problem

### ISSUE THREAD

**Issue by XingYaoA** [jupyter/qtconsole#552]
# problem
When I'm using the Jupyter QtConsole (version is 5.3.1), I do init_printing(use_latex='mathjax') in the SymPy. But it doesn't work:
![screenshot](https://user-images.githubusercontent.com/102949335/177476942-a56c9124-184f-4434-b2d8-d323419b2e7b.png)
Although it cannot work on Jupyter QtConsole, it can work on Jupyter Notebook:
![screenshot1](https://user-images.githubusercontent.com/102949335/177476991-01dcfc4f-5055-4fea-838f-24b8d1319bf4.png)

# Related Information
My operating system: Windows 7
My Python version: 3.8.10

**Comment by ccordoba12** [comment]
Hey @hemoumouda, thanks for reporting. Qtconsole doesn't support MathJax because that's a web technology and so it doesn't work in desktop applications.

To have Latex printing in Qtconsole you need to install Latex and make sure that is in your PATH.

**Comment by hemoumouda** [comment]
Hi @ccordoba12,I have installed Latex:
![screenshot](https://user-images.githubusercontent.com/102949335/177671967-2bbef1af-21d1-40e6-a63e-2cacc81ec422.png)
and make sure that is in my PATH too.
but it still doesn't work:
![screenshot1](https://user-images.githubusercontent.com/102949335/177672575-526e1e97-d172-4e8a-a726-1e1c65a69e9a.png)

**Comment by ccordoba12** [comment]
Please reread my answer. I clearly said:

> Qtconsole **doesn't support MathJax** because that's a web technology and so it doesn't work in desktop applications.

However, you keep using the `mathjax` option in `init_printing`.

Please read the docs for `init_printing` to learn how to properly use it:

https://docs.sympy.org/latest/tutorial/printing.html

If you have more doubts about it, please post your question on the Sympy repo:

https://github.com/sympy/sympy

**Comment by hemoumouda** [comment]
Thanks!
