### ISSUE TITLE
Can't change the background color on an embedded QtConsole

### ISSUE THREAD

**Issue by gmolinart** [jupyter/qtconsole#559]
Hi, first of all thanks for all the amazing work on this project. I'm asking this after trying to find a solution for a few days. I'm launching the console following [this](https://github.com/jupyter/qtconsole/blob/master/examples/embed_qtconsole.py) example, and I'm running  in the init method: 

self.set_default_style('linux') 

which gives me : 
<img width="676" alt="Screen Shot 2022-09-29 at 12 43 58 PM" src="https://user-images.githubusercontent.com/13454334/193090063-ed254948-38db-437a-be9f-2ce276ce3138.png">

My question is how do I change the background color to black , I've also tried setting the stylesheet attribute with no luck. 

Thanks in advance.

**Comment by ccordoba12** [comment]
Hey @gmolinart, thanks for reporting. Please go to the menu `View > Syntax style`. You'll find there several styles with a dark background.
