### ISSUE TITLE
AttributeError: 'QtInProcessChannel' object has no attribute 'closed'

### ISSUE THREAD

**Issue by twizmwazin** [jupyter/qtconsole#576]
After commit ff57647679e1b20be56acaf90273e36f74d3601d, FrontendWidget calls `closed` on `self.kernel_client.iopub_channel`. This commit introduced that `closed` attribute to QtZMQSockerChannel. No such attribute exists for `QtInProcessChannel` however, so this exception is raised.

**Comment by ccordoba12** [comment]
Correct. Since this issue is no longer valid, I'm going to close it.
