### ISSUE TITLE
Qt bindings version outdated in documentation

### ISSUE THREAD

**Issue by gdementen** [jupyter/qtconsole#579]
Since qtconsole requires qtpy >= 2, it effectively does not support Qt4 any more. Also, from the changelog, it seems like PyQt6/PySide6 is supported but both the README and the installation documentation lists Qt4 + Qt5 bindings instead of Qt5 + Qt6.

**Comment by ccordoba12** [comment]
Hey @gdementen, thanks for reporting. You're welcome to submit a pull request with more up to date information about our dependency on Qt.

**Comment by gdementen** [comment]
Sorry... but I will do this when I have some time... i.e. probably never. I can hardly maintain my own projects.
