### ISSUE TITLE
Stop using `IPythonLexer` from ` IPython.lib.lexers`

### ISSUE THREAD

**Issue by Czaki** [jupyter/qtconsole#588]
In release 8.17.0 the ipython remove `IPythonLexer` from `IPython.lib.lexers` as cleanup of python 2 code. However qtconsole still import its: 

https://github.com/jupyter/qtconsole/blob/2accd52e7af226bc857a89099260e55c5740efe1/qtconsole/jupyter_widget.py#L17

That leads to crash on import time. 

I have opened issue in python repository:
https://github.com/ipython/ipython/issues/14227

But long term solution should be to not depend on `IPythonLexer`, especially that project ins python 3.7+.

**Comment by Carreau** [comment]
I've yanked the release and will revert, but `IPythonLexer` is for Python 2 so there is no reason to Import it the package does not support Python 2.

**Comment by ccordoba12** [comment]
Leaving this for the next minor version of QtConsole (5.6.0) because Spyder still supports Python 2 kernels and some users let us that they rely on that functionality.

**Comment by Carreau** [comment]
No problem, i can delay removing from IPython as well.
