### ISSUE TITLE
TypeError due to wrong spelling in keyword

### ISSUE THREAD

**Issue by AndreiSavici** [jupyter/qtconsole#591]
The call to `compute_item_matrix` function in https://github.com/jupyter/qtconsole/blob/master/qtconsole/completion_html.py#L315 uses the `displaywidth` keyword, but the implementation in https://github.com/jupyter/qtconsole/blob/master/qtconsole/util.py#L144 has is spelled as `displaywith` (no second d). This cause a type error when called in the code

**Comment by ccordoba12** [comment]
Hey @AndreiSavici, thanks for reporting and for finding the solution to this problem.

We'd really appreciate if you could submit a pull request with the fix you described because we're really busy with other things.
