### ISSUE TITLE
It would be nice for jupyter_qtconsole to request installation if PyQt if is not there...

### ISSUE THREAD

**Issue by damianavila** [jupyter/qtconsole#6]

**Comment by minrk** [comment]
I'm not sure I understand. PyQt (or PySide) is a dependency. They aren't pip-installable, so we can't express them as setuptools dependencies, though.

**Comment by damianavila** [comment]
I expressed myself in a very bad way, I modified the title accordingly... I wanted to express my intentions to have some automatic way to install pyqt if it is not detected... but that's depend on the platforms and package manager... 
Essentially, I would like to see jupyter-qtconsole trying to install pyqt if:
* pyqt is not detected but 
* conda is detected... 
but maybe is going to much with conda... IDK, just thinking a nice way to start the console w/o thinking in any kind of installation...

**Comment by minrk** [comment]
I don't think that's the right thing to do. The qtconsole conda package has a proper dependency on PyQt, as does the qtconsole apt package, so I think this is covered for most users. When you install with pip, one of the limitations is you only get pip-resolvable dependencies automatically. I think the absolute most we should do in that case is display a message.

**Comment by damianavila** [comment]
>I think the absolute most we should do in that case is display a message.

OK, thinking again on this, I agree with you... I guess was a kind of desire to solve problems for people using pip in a conda-way... and that's not right. Just closing. Thanks for the feedback and the alert about my bad way to express my idea :wink:

**Comment by minrk** [comment]
We just need to get PyQt to be pip-installable!
