### ISSUE TITLE
Support pyreadline

### ISSUE THREAD

**Issue by thekafkaf** [jupyter/qtconsole#60]
Hi, I'm currently trying to introduce QtConsole to our workflow, but a key feature is missing - support of libraries using pyreadline(e.g ipdb as a noticeable example).
This is a REALLY big issue for us, and so, I want to participate and fix this issue so badly! But as I'm not that familiar with the IPython code-base(yet), I would like your help.

Freely speaking, I'm not sure why this is such a hard problem to tackle, as the IPython kernel itself uses pyreadline, so can't we hook usages of the module and "rewire" our endpoints(history/auto-complete) to the new "readline"?

Thanks!

**Comment by ccordoba12** [comment]
I think this is not possible because qtconsole uses Qt widgets and features to emulate the behavior of real console (i.e. a tty one, where readline works), but it doesn't use any of its technologies.

**Comment by thekafkaf** [comment]
Hi @ccordoba12, first of all - no such thing as "impossible" :)

Now, I get how the qtconsole works and that it doesn't really uses the readline - but we can hook the readline calls, for example - if as a first challenge readline uses `raw_input` which blocks the kernel - we can overwrite it and send a signal to the frontend and wait for a return, we can basically rewire our endpoints("complete_info", "execute" and the history saved by HistoryWidget) to emulate a use of readline.

What do you think?

**Comment by thekafkaf** [comment]
Bumping, can we at least try to think of a way, it's possible, I'm just asking for some guidance for the best possible solution.

When the kernel is blocking in a `While True`, and querying the channel for an input from the frontend, we can query the other endpoints as well, am I missing something?

**Comment by ccordoba12** [comment]
I think it would be a mess to try to support readline and it's not worth the effort.

Besides, I can't provide guidance because I don't have enough knowledge of the Jupyter internals to do so ;-)

**Comment by minrk** [comment]
I think we shouldn't use readline in the qtconsole. The kernel produces completions entirely without readline. Readline is just one way of putting those completions into a *terminal* UI. Since we don't use a terminal UI, readline doesn't offer much value in the qtconsole.

**Comment by CRP** [comment]
what features of readline do you need? if it is just a matter of getting history and completion in pdb, then probably forcing in readline isn't the corret route...

**Comment by thekafkaf** [comment]
It's not about adding value, it's about supporting the current python libs.
QtConsole is a shell, and as such should keep compatibility with the console, right now libs that use readline are broken/half-usable, IMO this is awful.

To solve this, we could either patch, so qtconsole would behave nicely with readline, or support multiple Consoles\Kernels in a single screen(which you said once, you will never support).
What do you think? Can we try to solve this?

**Comment by ccordoba12** [comment]
> ipdb as the obvious one

ipdb doesn't work because of a limitation of the frontend/kernel architecture, not because qtconsole lacks readline support. I think the kernel blocks once you enter pdb, and that's why you can't have history browsing and all other nice features you have in terminal IPython.

> it should strive to be a complete IPython terminal!

No need of it. As I said, trying to force qtconsole to be a real terminal would be a mess. If you want a real terminal, you can just open one :-)

> Sounds interesting, but how is that simpler? Can you give an example?

Please take a look at how history browsing works in qtconsole. Or how `Ctrl+K` and similar shortcuts work.

----

Given that @minrk and me are -1 on this idea, I think you're on your own if you want to implement it, and even then it could not be merged. Sorry, but IMHO this is not something that deserves to be discussed further.

**Comment by nikohansen** [comment]
> what features of readline do you need?

I am (desperately) missing control-k (kill text to end of line).

**Comment by ccordoba12** [comment]
That works on qtconsole, I use it regularly :-)

**Comment by nikohansen** [comment]
I installed Anaconda a few days ago on MacOS (Sierra), and it doesn't for me. Any hints how to make it work? Could it be left overs from previous installations?

```
Jupyter QtConsole 4.2.1
Python 2.7.12 |Anaconda 4.2.0 (x86_64)| (default, Jul  2 2016, 17:43:17) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
```

**Comment by wmvanvliet** [comment]
Ctrl+Shift+K works for me, Ctrl+K does not work on my mac.

**Comment by nikohansen** [comment]
Same here, it works with shift. That's pretty weird that the key is different only for `qtconsole`. I don't see how I will get used to this.

**Comment by ccordoba12** [comment]
Ctrl+K works for me on Linux and Windows. @wmvanvliet, would you like to take a look at this one for Mac?

**Comment by wmvanvliet** [comment]
see #164

**Comment by wmvanvliet** [comment]
Closing this. The volunteers working on qtconsole will not add readline support anytime soon. Feel free to take a stab at it yourself if you feel up to it.
