### ISSUE TITLE
LaTeX that matplotlib fails on should fallback to the next renderer

### ISSUE THREAD

**Issue by asmeurer** [jupyter/qtconsole#63]
There is a lot of advanced LaTeX that the matplotlib renderer cannot handle. If an object defines a LaTeX repr that it can't handle, it just shows the error message. It should fallback to the next renderer.

This is causing an issue for us with SymPy (see https://github.com/sympy/sympy/issues/9962). SymPy is able to print expressions using Unicode, but when the renderer fails (in this case, for matrices), it just shows the error 

```
Failed to render latex: 
\left[\begin{matrix}1 & 2\\3 & 4\end{matrix}\right]
      ^
Expected "\right" (at char 6), (line:1, col:7)
```

To reproduce:

- First, make sure you don't have `latex` installed in your PATH (or else it will just use that and not matplotlib)
- Install the latest version of SymPy
- Start the qtconsole and run

```
from sympy import *
init_session()
Matrix([[1, 2], [3, 4]])
```

**Comment by asmeurer** [comment]
I am willing to send a fix for this if someone can indicate what the correct fix should be. My thinking is:

- Make the latex printer special in that it falls back if the formatter fails.
- Don't print the warning in the console (is there some kind of debug log I can print it to instead?)

**Comment by ccordoba12** [comment]
Thanks @asmeurer. This is also related to issue #56 and PR #57.

I'll look into it for 4.2.

**Comment by asmeurer** [comment]
I didn't see those. Thanks for the reference.

I think this boils down to the fact that there is no way for frontends to change the printer precedence (in the qtconsole or the notebook). This is something that SymPy would like to have as well (we basically work around it by having options to `init_printing` that cause various printers to not be enabled at all). That's a much bigger issue to fix, though. 

That PR looks extreme, and would probably break things for people. For SymPy, it would actually work, because our printing isn't enabled without calling `init_printing()` anyway, and we define our own png repr using latex/dvipng or matplotlib (and our printers do the right thing in this case, falling back to the text printer if matplotlib can't handle the LaTeX).

I'm not clear if the fix I'm suggesting would fix @flying-sheep's issue, unless it is also coming from LaTeX that matplotlib cannot render.

**Comment by asmeurer** [comment]
Here is a fix https://github.com/jupyter/qtconsole/pull/65. It's maybe not the cleanest thing, but it works.
