### ISSUE TITLE
Start qtconsole using pythonw on Windows

### ISSUE THREAD

**Issue by tmr232** [jupyter/qtconsole#64]
Is it possible to make the `jupyter qtconsole` script launch the console using `pythonw.exe` instread of `python.exe`?

Presently, it causes a shell window to be displayed in addition to the qtconsole, and is quite annoying.
I use `pythonw -m qtconsole` as an alternative to avoid that, but would prefer a proper solution.

**Comment by willingc** [comment]
@ccordoba12 There was another windows issue reported in the jupyter/jupyter repo that seems related to this issue.

**Comment by tmr232** [comment]
@willingc Seems like the other issue was related in symptoms but not in cause, as it had `ipconfig.exe` processes spawning and not `python.exe` ones.

**Comment by ccordoba12** [comment]
@minrk, could you take a look at this one? I'm not familiar enough with how Jupyter application commands work to solve it.

**Comment by takluyver** [comment]
I think this might have been resolved by #97.

**Comment by ccordoba12** [comment]
Yes, I think you're right! :-)
