### ISSUE TITLE
RichJupyterWidget.execute() leads to exception

### ISSUE THREAD

**Issue by lorton** [jupyter/qtconsole#68]
When trying to execute code before showing the `RichJupyterWidget`, an exception is thrown.  When I traced the code, it makes sense, as neither parent class of `FrontendWidget` has a `_handle_execute_reply` function, but there is a code path that will call `super(FrontendWidget, self)._handle_execute_reply`.  The traceback is below:

```
Traceback (most recent call last):
  File ".../qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File ".../qtconsole/jupyter_widget.py", line 182, in _handle_execute_reply
    super(JupyterWidget, self)._handle_execute_reply(msg)
  File ".../qtconsole/frontend_widget.py", line 496, in _handle_execute_reply
    super(FrontendWidget, self)._handle_execute_reply(msg)
AttributeError: 'super' object has no attribute '_handle_execute_reply'
```

I can try to find a suitable solution and submit a pull request if there's interest in it?

**Comment by ccordoba12** [comment]
It seems you're trying to execute something before the widget is connected to a kernel. So I think there's nothing to fix here, but perhaps I'm wrong.

@minrk?

**Comment by lorton** [comment]
Hi, sorry I should have posted the code - I don't *think* that's the problem, but am very new to the code.  When I read it I don't see how `super(FrontendWidget, self)._handle_execute_reply(msg)` could ever not except, so I think there is a pathway that is a guaranteed exception without a clear warning.

Here's the code I was testing with (slight change to the example script):
```
from qtconsole.qt import QtGui
from qtconsole.rich_jupyter_widget import RichJupyterWidget
from qtconsole.inprocess import QtInProcessKernelManager


def show():
    global ipython_widget  # Prevent from being garbage collected

    # Create an in-process kernel
    kernel_manager = QtInProcessKernelManager()
    kernel_manager.start_kernel(show_banner=False)
    kernel = kernel_manager.kernel
    kernel.gui = 'qt4'

    kernel_client = kernel_manager.client()
    kernel_client.start_channels()

    ipython_widget = RichJupyterWidget()
    ipython_widget.kernel_manager = kernel_manager
    ipython_widget.kernel_client = kernel_client
    ipython_widget.execute("%matplotlib inline")
    # ipython_widget.execute("import my_library_I_always_want_available")
    ipython_widget.show()


if __name__ == "__main__":
    app = QtGui.QApplication([])
    show()
    app.exec_()
```

**Comment by lorton** [comment]
Hi - this is affecting my ability to use qtconsole, if its agreed that this is a real bug, I can submit a pull request?  My one fear is that I don't understand the code well enough and my code might not be addressing all scenarios, so it'll probably need to be reviewed by someone who understands it really well.  Is this reasonable?

**Comment by ccordoba12** [comment]
Yes, please submit a pull request. We'll help you to review it.

**Comment by jvkersch** [comment]
I found this issue after googling the same AttributeError. @lorton did you get anywhere with writing a fix? I'm in the same position as you (not super familiar with the code, but willing to fix things), anything I can do to help?

**Comment by lorton** [comment]
I got bogged down with some other projects right when this came up, though I'll still need to fix this in order to use qtconsole. I'll try to give this a shot in the next couple of days.

**Comment by lorton** [comment]
I've submitted a pull request for this, though I'm not sure if it's the correct fix.  Looking forward to any feedback.
