### ISSUE TITLE
Docs Typo

### ISSUE THREAD

**Issue by schodge** [jupyter/qtconsole#74]
There's a typo at:

http://jupyter.org/qtconsole/stable/config_options.html

>>
These options can be set in ~/.jupyer/jupyter_qtconsole_config.py, or at the command line when you start it.
<

Note the missing 't' in `.jupyter`.  I was looking for the docs to fix and submit a pull request, but it looks like the source rst file `docs/source/config_options.rst` is excluded from the repo via `.gitignore`...?

**Comment by minrk** [comment]
It's a generated file. Fixed by #75

**Comment by schodge** [comment]
Ah, it was autogenerated from the code, not the rst. Thanks !

Non-ideal input device. Please excuse typos.
