### ISSUE TITLE
After a kernel reset, input line hangs

### ISSUE THREAD

**Issue by dashesy** [jupyter/qtconsole#76]
Windows with Jupyter QtConsole 4.1.1 but I have seen this on Linux on iPython too.
- Add these lines to `ipython_config.py`, because I want `pylab` mode and `autoreload` for my development.

``` python
    c.InteractiveShellApp.extensions = ['autoreload', 'pylab']
    c.InteractiveShellApp.exec_lines = ['%autoreload 2', '%pylab']
```
- Then use <kbd>ctrl</kbd>+<kbd>.</kbd> to reset the kernel.

If I am running `QtConsole` for some time, sometimes the input hangs. I will have to close the application and open it again. 

This is not a big issue, but wanted to see if I am alone in seeing this problem and if there is any workaround, or if I could help debugging this.

**Comment by ccordoba12** [comment]
What's you Matplotlib backend?

**Comment by dashesy** [comment]
It is `Qt4Agg`

**Comment by ccordoba12** [comment]
Please disable one of your startup magics, and then the other, to 
determine which one is causing this problem.

Sorry for not being more helpful, but I haven't seen this problem before.

**Comment by dashesy** [comment]
It seems sometimes the std output of the startup magic leaks into the input stream after reboot. 

When I hit enter when input hangs I got this:

```
NameError: name 'atplotlib' is not defined
```

Which is result of trying to execute the console output of:
```
Using matplotlib backend: Qt4Agg
```

**Comment by dashesy** [comment]
Here is the log file when input hangs:

```text
[JupyterQtConsoleApp] WARNING | kernel restarted
[JupyterQtConsoleApp] execute_input: {u'execution_count': 1, u'code': u'\n\n\n\n'}
[JupyterQtConsoleApp] execute: {u'status': u'ok', u'execution_count': 0, u'user_expressions': {}, u'payload': []}
QTextCursor::setPosition: Position '80967' out of range
QTextCursor::setPosition: Position '80967' out of range
QTextCursor::setPosition: Position '80967' out of range
QTextCursor::setPosition: Position '80967' out of range
[JupyterQtConsoleApp] execute_input: {u'execution_count': 1, u'code': u'\n'}
[JupyterQtConsoleApp] execute: {u'status': u'ok', u'execution_count': 0, u'user_expressions': {}, u'payload': []}
[JupyterQtConsoleApp] Starting kernel: ['/home/dashesy/.virtualenvs/qtconsole/bin/python', '-m', 'ipykernel', '-f', u'/run/user/1000/jupyter/kernel-3011.json']
[JupyterQtConsoleApp] Connecting to: tcp://127.0.0.1:44711
QTextCursor::setPosition: Position '29967' out of range
[JupyterQtConsoleApp] shutdown: {u'status': u'ok', u'restart': True}
[JupyterQtConsoleApp] stream: {u'text': u'Using matplotlib backend: TkAgg\nPopulating the interactive namespace from numpy and matplotlib\n', u'name': u'stdout'}
QTextCursor::setPosition: Position '29993' out of range
```

1. Every time it hangs I see `QTextCursor::setPosition` **after** the line about `stream`
2. Only Enter is hanged, I can type:

  a. either I have to type a very long character string for buffer to be ready again
  b. or I can use Backspace! which deletes the line `Populating the interactive namespace from numpy and matplotlib` but then I can press Enter again

It is reproducible too. I use this [script](https://github.com/ipython/ipython/issues/1392) it generates lots of `QTextCursor::setPosition` messages, then I restart the kernel (usually twice) fast. This sounds contrived but has the effect of reproducing the error.

**Comment by dashesy** [comment]
Ok it is this line that results in `QTextCursor::setPosition` warnings:

    cursor.setPosition(self._append_before_prompt_pos)

Why it results in input stream hung I will try to figure out

**Comment by dashesy** [comment]
Another way to reproduce input hang, without restarting the kernel:

1. Run this [script](https://github.com/ipython/ipython/issues/1392) for little while
2. Run `np?`
3. Try Enter key or arrows, and the input hangs and terminal will have lots of QTextCursor::setPosition: Position 'X' out of range
 warnings

**Comment by takluyver** [comment]
We've had recurring problems with those 'Position xyz out of range' warnings followed by input hanging.
