### ISSUE TITLE
The magic command %guiref not available in IPython 4, but is listed in QtConsole startup text

### ISSUE THREAD

**Issue by FSund** [jupyter/qtconsole#78]
The line magic function %guiref is no longer available in IPython (version 4.0 and above I think, see the IPython [docs](http://ipython.readthedocs.org/en/stable/interactive/magics.html)), and should probably be removed from the text printed when starting Jupyter QtConsole, or replaced with a working command.

When I start Jupyter QtConsole (I'm on Windows 10 64 bit, using the latest Anaconda3) the following is printed

    Jupyter QtConsole 4.1.1
    Python 3.5.1 |Anaconda 2.4.1 (64-bit)| (default, Dec  7 2015, 15:00:12) [MSC v.1900 64 bit (AMD64)]
    Type "copyright", "credits" or "license" for more information.

    IPython 4.0.1 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.
    %guiref   -> A brief reference about the graphical user interface.

But when I try %guiref I get an error

    In [1]: %guiref
    ERROR: Line magic function `%guiref` not found.

**Comment by takluyver** [comment]
I think that most of the text in `%guiref` should be moved from IPython (it's currently stored in `IPython.core.usage`) to the Qt console itself, as it describes things like keyboard shortcuts and the pager, which aren't specific to the IPython kernel. It should be an option in the *Help* menu of the console. This could be a relatively simple task for a new contributor who has some familiarity with Qt.
