### ISSUE TITLE
tab completion in cd with filenames with space on Windows

### ISSUE THREAD

**Issue by pbienst** [jupyter/qtconsole#79]
I'm trying to use QtConsole as a complete shell replacement, but when I do

cd My<tab>

I can e.g. choose a path so that my prompt becomes

cd My\ Library

which gives my

[Error 3] The system cannot find the path specified: u'My\\ Library', probably because there is something wrong with the way the spaces are escaped.

**Comment by ccordoba12** [comment]
I think this has to be solved in `ipykernel`, right @minrk?

**Comment by minrk** [comment]
100% an IPython bug, and a duplicate of ipython/ipython#1021
