### ISSUE TITLE
[docs] Redirect to readthedocs

### ISSUE THREAD

**Issue by Carreau** [jupyter/qtconsole#82]
Now that qtconsole docs [works on readthedocs](http://qtconsole.readthedocs.org/) we should migrate the various links and replace the current pages on http://jupyter.org/qtconsole/stable/ with redirects.

**Comment by willingc** [comment]
@Carreau Agreed.

I'm going to update the README to refer to readthedocs.

If someone with repo maintenance privileges can update the link next to the repo description to https://qtconsole.readthedocs.org/en/stable/ that would be great.

**Comment by Carreau** [comment]
> If someone with repo maintenance privileges can update the link next to the repo description to https://qtconsole.readthedocs.org/en/stable/ that would be great.

Good point. Done.

**Comment by willingc** [comment]
@Carreau Thanks for the repo link update.

Here's a PR #85 to update the README. I'll open another PR for any link changes in the source docs. Then I'll take a look at the gh-pages if needed.
