### ISSUE TITLE
Output more possibilities on tab-completion

### ISSUE THREAD

**Issue by anntzer** [jupyter/qtconsole#84]
Currently, tab completion only displays a small list of possibilities at a time:
![completion](https://cloud.githubusercontent.com/assets/1322974/12287196/73f817fc-b97f-11e5-8414-b3b22311ddf7.png)
The list is also always displayed in three columns, even if they don't fit (then the last column is just invisible) or if the window is much wider than that.
Given that the qtconsole can erase the unused completions I'd suggest just displaying the whole list instead (which is also useful as a quick substitute to calling `dir`/`vars`).
(Actually, a pager-like behavior would be more useful in the console ipython, which currently outputs the whole list without erasing it afterwards.)

**Comment by takluyver** [comment]
The Qt console doesn't get much active development now, so significant changes like this are only likely to happen if someone is interested enough to work on it themselves.

**Comment by ccordoba12** [comment]
@anntzer, that's just the default completion behavior. You can get the whole list of completions by starting qtconsole with this option

    jupyter qtconsole --JupyterWidget.gui_completion='plain'

Or you can make qtconsole to use a completion widget for completions with

    jupyter qtconsole --JupyterWidget.gui_completion='droplist'

In fact, that's the default we use in Spyder because we also use a completion widget for our Editor and Python Consoles.

**Comment by anntzer** [comment]
That's already better, thanks for the suggestion.

**Comment by ccordoba12** [comment]
@anntzer, could we close this issue then?

**Comment by anntzer** [comment]
Well, the issue is still there for the default completer.  If you want to close it as wontfix, I don't really care.

**Comment by ccordoba12** [comment]
So you propose to change the default completer to `plain`?

Pinging @jdmarch to see what he thinks about that for Canopy

**Comment by anntzer** [comment]
I'd rather have the ncurses completer improved (after all you *can* display more choices over three columns than over one).  On the other hand I don't plan to actually work on it, thus the remark about wontfix.

**Comment by jdmarch** [comment]
Thanks @ccordoba12, checking with Canopy dev team.

**Comment by takluyver** [comment]
Anyone who's interested in this, please take a look at #92 (thanks @vidartf)
