### ISSUE TITLE
Override QT_API when a Qt binding is already loaded?

### ISSUE THREAD

**Issue by anntzer** [jupyter/qtconsole#87]
I would like to suggest not obeying QT_API when a specific Qt binding has already been loaded, and just use it, rather than raising an exception: the error is probably just a misconfigured environment variable and there's a clear, single, well-defined recovery.

**Comment by takluyver** [comment]
Do you mean in the Qt console code itself - which would only be relevant when embedding it in a larger application - or in the kernel where user code runs?

**Comment by anntzer** [comment]
I was thinking about the embedding case.

**Comment by takluyver** [comment]
Either way, it sounds reasonable to me. Want to make a PR?

**Comment by anntzer** [comment]
Sure.
