### ISSUE TITLE
Occasionally, Qtconse stops responding to some keystrokes

### ISSUE THREAD

**Issue by taerath** [jupyter/qtconsole#94]
I am using Jupyter QtConsole 4.1.1 from Continuum's Anaconda. 

Every once in a while, the Qtconsole windows stops accepting some keystrokes. I can still enter most characters and numbers, but if I press e.g. return or backspace, nothing happens.

Sometimes I can get things to work again by either:
- Opening a new tab (and then switching back to the old one)
- Pressing Ctrl-p or Ctrl-y repeatedly

Is there anything I can do to debug this further?

**Comment by takluyver** [comment]
Is there any message in the terminal where you started the qtconsole? Try running with `--debug`.

There's a problem that comes up occasionally where you get an error message in the terminal saying something like 'cursor position out of bounds'. I think some progress was made with that, but it seems there are still some bugs lurking.

**Comment by taerath** [comment]
On 01/30/2016 10:30 AM, Thomas Kluyver wrote:
> Is there any message in the terminal where you started the qtconsole?
> Try running with |--debug|.
>
> There's a problem that comes up occasionally where you get an error
> message in the terminal saying something like 'cursor position out of
> bounds'. I think some progress was made with that, but it seems there
> are still some bugs lurking.

Yeah, I get lot's of exactly these messages on the terminal:

QTextCursor::setPosition: Position '31539' out of range
QTextCursor::setPosition: Position '31539' out of range
QTextCursor::setPosition: Position '31539' out of range
QTextCursor::setPosition: Position '31539' out of range
QTextCursor::setPosition: Position '31539' out of range
QTextCursor::setPosition: Position '31539' out of range
QTextCursor::setPosition: Position '31539' out of range
QTextCursor::setPosition: Position '31539' out of range


Best,
-Nikolaus

**Comment by thertz** [comment]
Hi,

I am also getting similar messages to the ones reported above. I have found that on mac running El-Capitan (but also true on previous versions) if I run jupyter-qtconsole 4.1.1 (installed by anaconda) from the shell, certain keystrokes (which I have not tracked down) cause the qtconsole to hang and I get messages of the following format to appear in the shell:

QTextCursor::setPosition: Position '22702' out of range
QTextCursor::setPosition: Position '22702' out of range

The only solution I have found is to quite the ipython shell and start again. It seems to me that this is happening more than it did in previous versions of the qtconsole.

I have googled and found no information regarding this bug, or how to resolve it.

Best,
--Tomer

**Comment by dashesy** [comment]
This issue [here](https://github.com/ipython/ipython/issues/1392) can be reproduced with latest Juputer.

    Jupyter QtConsole 4.3.0.dev
    IPython 4.1.1 
    Python 2.7.10

**Comment by jrovegno** [comment]
I open (File > New Tab with Same Kernel) after the problem occurred. 
Then I close the hanged tab and I work in the new tab.

**Comment by wmvanvliet** [comment]
See #145
